### PR TITLE
Add subjectAltName to development cert

### PR DESCRIPTION
**Pull request by johnboxall**
Resolves https://github.com/webpack/webpack-dev-server/issues/854

**What kind of change does this PR introduce?**

Regenerates the included development cert with alt names for both `localhost` and `127.0.0.1` and adds a script to recreate the cert with the configuration used to create what is committed.

**Summary**

In Chrome 58, support for commonName matching in certificates was dropped:

https://www.chromestatus.com/features/4981025180483584

On OSX, for folks who have added the existing committed cert to their keychain, they'll now see issues as detailed here:

https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/

Constantly clicking through this warning is old, so we'll want to add the SAN to the dev cert.

To verify the existing behaviour, try adding the current cert to your Keychain (Always Trust!) and browse to a running Webpack server configured for HTTPS. Note that you get an error :|

Now switch over to this version, delete the old cert from your Keychain, add the new one and try again. It works!

**Does this PR introduce a breaking change?**

Because the cert is updated, folks who have used the Keychain work around will now need to remove the old entry and add the new one.

image

image
pasted image at 2017_03_20 06_48 pm
pasted image at 2017_03_20 06_46 pm

If you want to verify the values in the cert you can paste it into something like https://certificatetools.com/ or just serve it locally yourself and verify in your browser.

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Just a note that I haven't forgotten this, I'm very busy these days but I hope I have some time in the weekend to review.

**Comment by thrandre** [comment]
Friendly bump. Chrome 58 started rolling out in Norway this morning.

**Comment by johnboxall** [comment]
If we wanted to extend this to Windows – we could generate the `.p7b` file format that Windows likes from the `.pem` using:

```bash
openssl crl2pkcs7 \
    -nocrl \
    -certfile server.pem
    -out server.p7b
```

**Comment by sidshetye** [comment]
@shellscape : what's the final solution ? Seems this is closed and #942 is in limbo.

**Comment by shellscape** [comment]
@siddhadev use `devcert`. I'm not longer a maintainer on this project.

**Pull request closed without merging**
