### PR TITLE
Allows absolute URL as `openPage` option

### LINKED ISSUE #1594: Allow absolute URL as the `openPage` option
* Operating System: Ubuntu 18.04
* Node Version: 11.2.0
* NPM Version: 6.4.1
* webpack Version: 4.26.1
* webpack-dev-server Version: 3.1.10

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
{
    entry: './src/index.js',
    output: {
        filename: 'main.[hash].js',
        path: path.resolve(__dirname, 'dist'),
    },
    devServer: {
        contentBase: path.resolve(__dirname, 'dist'),
        historyApiFallback: true,
        open: true,
        openPage: 'http://test.example/',
        allowedHosts: [
            'test.example',
        ],
    },
}
```

### Expected Behavior

Browser should open a page at http://test.example/

### Actual Behavior

Browser opens a page at http://localhost/http://test.example/

### For Features; What is the motivation and/or use-case for the feature?

The app that I am developing has a different behavior based on the hostname that it runs on. I never test it on `localhost` as it does not have a specific behavior under that hostname. It is kind of annoying to have to change the host name each time I start the server. Hence I would like to specify an absolute URL as the `openPage`.

### PR DESCRIPTION
**Pull request by misterdev**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
No, I'm going to work on this

### Motivation / Use-Case
Solves bug https://github.com/webpack/webpack-dev-server/issues/1594

### Breaking Changes
No

### CODE REVIEW

**Comment by misterdev** [comment]
I'm new to webpack development, may I ask for some guidance writing tests for this?
I don't know how to get the URL of the page served by the running server..

**Comment by evilebottnawi** [comment]
@misterdev you need mock here (information https://sinonjs.org/releases/latest/mocks/), just mock module and check after run server we call `opn` with right values

**Comment by misterdev** [comment]
I'm having some difficulties working this:

1. How to run the server: from my understanding using `lib/Server` or `test/helper` doesn't work since none of these actually execute [`utils.status`](https://github.com/misterdev/webpack-dev-server/blob/fix-openpage-with-url/bin/utils.js#L41). I also tried using `require('../bin/webpack-dev-server')` in my code but I don't feel is the right approach and I don't know how to pass my configurations to the server.
2. How to spy `opn`: I'm trying spying it this way without success:
```javascript
const open = require('opn');
this.sinon.spy(open);
assert(spyOpn.calledOnce);
```

The final (not working) result is:

```javascript
const assert = require('assert');
const open = require('opn');

describe('check openPage option', function testHttps() {
  let spyOpn;

  before(function before() {
    // const options = {
    //   openPage: 'http://localhost:9090/'
    // };
    spyOpn = this.sinon.spy(open);
    const server = require('../bin/webpack-dev-server');
  })

  it('should allow absolute URL', (done) => {
    assert(spyOpn.calledOnce)
    done();
  });
});
```

I know this should be easy, any suggestion on what I'm doing wrong is welcome.
Thanks @evilebottnawi for your patience and help.

**Comment by misterdev** [comment]
Any help is welcome! 🎄

**Comment by evilebottnawi** [comment]
@misterdev sorry for delay, holidays, you need add tests in CLI tests (you can find how we run webpack-dev-server in tests) and use spy how you do above

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-dev-server/issues/1594#issuecomment-457657239

**Pull request closed without merging**
