### PR TITLE
feat: expose socket client for external integrations

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No

### Motivation / Use-Case

Fix https://github.com/webpack/webpack-dev-server/issues/4261
Fix https://github.com/webpack/webpack-dev-server/pull/4304/

### Breaking Changes

None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Let's add test

**Comment by snitin315** [comment]
How should we test this? Just check if this is exported?

**Comment by alexander-akait** [comment]
Yep, just create puppeteer test and try to get client from external script

**Comment by snitin315** [comment]
@alexander-akait not sure how to get client from an external script. Can you give example?

**Comment by alexander-akait** [comment]
Just import dev server client and test value

**Pull request closed without merging**
