### PR TITLE
fix: fix live reload for child compiler scenario

### LINKED ISSUE #3971: live reload does not works when the change is happened on entry of child compiler
### Bug report

I have a plugin which creates a child compiler and use a different entry for the compilation. It happens at parent's `compilation.hooks.processAssets` at `Compilation.PROCESS_ASSETS_STAGE_SUMMARIZE` stage . When I modify the child entry, it does not have a live reload but webpack did re-compile.

### Actual Behavior
webpack did re-compile but webpack-dev-server does not have a live reload when the change is done in the child entry 

### Expected Behavior

webpack-dev-server should have reload when child compilation has change

### How Do We Reproduce?

I have a fix ready. See my PR

### PR DESCRIPTION
**Pull request by wood1986**
fix #3971

- [X] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Currently, webpack-dev-server only cares `stats.hash` but this hash does not count child compilation when you run the childCompiler after parent's `seal` stage.

### CODE REVIEW

**Comment by wood1986** [comment]
Hey @alexander-akait, may I know if you are still looking at this issue?

**Comment by alexander-akait** [comment]
@wood1986 Yes, sorry for delay, tomorrow I will look, some busy

**Comment by wood1986** [comment]
Thanks for letting me know!! FYI, I can confirm that it was working before webpack-dev-server 4.0.0

**Comment by alexander-akait** [comment]
@wood1986 Can you provide example for v3?

**Comment by wood1986** [comment]
Here is https://github.com/wood1986/demo/tree/wds3

I have just found. It always has auto reload when it is a new change. However when you undo the previous saved change, it will not have auto reload. I cannot reproduce in own repository but I can find it in this repository

```
`->` means "Save"

1st change ->                         reload
1st change -> 2nd change ->           reload
1st change -> undo 1st change ->      no reload
```

**Comment by alexander-akait** [comment]
@wood1986

> Here is https://github.com/wood1986/demo/tree/wds3

> I have just found. It always has auto reload when it is a new change. However when you undo the previous saved change, it will not have auto reload. I cannot reproduce in own repository but I can reproduce it in this repository


I see, this related to https://github.com/webpack/webpack-dev-server/issues/3794, due `hot: true` by default (I think we really need to fix it), i.e. try to hot, if no modules, check hash, is hash was changed, do live reload

Generally we have two problems here:
1. `hot` is `true` by default and we need fix a bug described above
2. need to update hash of compilation (WIP on solution for you)

**Comment by alexander-akait** [comment]
Oh, I see running `childCompiler.runAsChild` inside `compilation.hooks.processAssets` is too late, we already calculate `hash` of `compilation` (main) here, so we need update it manually, just do it:
```
compilation.hash = `${compilation.hash}${childCompilation.hash}`;
```

Should fix the problem, feel free to feedback

**Comment by wood1986** [comment]
I did mention this fix

See
```js
parentCompilation.fullHash = parentCompilation.fullHash + childCompilation.fullHash
parentCompilation.hash = parentCompilation.fullHash
 ```

but it is not a native webpack hash. And do you think if other 3rd parties will have some logic related to this field `compilation.hash`?

**Comment by alexander-akait** [comment]
@wood1986 It is valid solution, for multi compiler mode we do the same, just concat two hashes in string, we have this logic https://github.com/webpack/webpack-dev-server/blob/master/client-src/utils/reloadApp.js#L12, i.e. `indexOf`, so invalidation works fine

> but it is not a native webpack hash. And do you think if other 3rd parties will have some logic related to this field compilation.hash?

Hash is just string and can have any length (types), so even a plugin will have logic for `hash` it should not broken

**Comment by wood1986** [comment]
It works. Thanks!!! I am curious the multi compiler mode implementation. Is it possible to show me the which files have hash concat?

**Comment by alexander-akait** [comment]
@wood1986 All used modules, you can track it in `creatHash` and look at used values

**Comment by alexander-akait** [comment]
@wood1986 Can we close?

**Pull request closed without merging**
