### PR TITLE
ci: add node v18 workflow

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]
I think should work now

**Review by anshumanv — APPROVED** [review]

**Review by rishabh3112 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
hm, we should fix our tests @snitin315 Can you look at this?

**Comment by snitin315** [comment]
Yeah, something wrong with MacOS tests. I'll look into it.

**Comment by alexander-akait** [comment]
@snitin315 Can we try to rebase and update all deps and test it again? Thank you

**Comment by alexander-akait** [comment]
hm, looks like some tests are broken, I will look

**Comment by snitin315** [comment]
closing in favor of #4599

**Pull request closed without merging**
