### PR TITLE
ci: debug

### PR DESCRIPTION
**Pull request by alexander-akait**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No need

### Motivation / Use-Case

Try to fix ci again

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
Weird, it happens only on macos, @snitin315 Can you check our tests locally again (maybe multiple times)?

**Comment by snitin315** [comment]
I was unable to reproduce locally on macOS

**Comment by alexander-akait** [comment]
I really don't understand... It is always random fail...

**Comment by alexander-akait** [comment]
@snitin315 I just set `jest.retryTimes(3)` and now our tests are passed, I tried many things to debug and still haven't found why it happens sometimes, maybe migrate on `playwire` https://github.com/webpack/webpack-dev-server/issues/2843 will solve the problem, let's postpone (we have an issue for this)

**Comment by snitin315** [comment]
Yes. Let's migrate to playwright in near future.

**Pull request merged**
