### PR TITLE
use validateSchema Directly

### PR DESCRIPTION
**Pull request by ev1stensberg**
**What kind of change does this PR introduce?**

Enhancement / Bugfix
**Did you add or update the `examples/`?**
N/A
**Summary**

Trying to run the devServer makes the validationSchema throw. Maybe webpack has changed their implementation, so I used the module directly. This is probably also better? Feel free to repro and investigate, happy to provide more information

**Does this PR introduce a breaking change?**
No

**Other information**
devServer version is: 2.9.7

skjermbilde 2017-12-18 kl 21 49 16

### CODE REVIEW

**Comment by shellscape** [comment]
@ev1stensberg PR says you're using 2.9.7 - does the same issue exist for 3.0.0? I'm not really sure what your screenshot is trying to convey, I think it's better to use text than images so we can quote, etc.

**Comment by ev1stensberg** [comment]
@shellscape Ran WDS from a spawned process for the serve feature, I'll get a repro test for you tomorrow, and test it against 3.0.0 👌

**Comment by ev1stensberg** [comment]
Version 3 ( next branch ) ran without errors. I guess this is because the cli and wds depends on different versions of webpack, closing this for now

**Comment by ev1stensberg** [comment]
@shellscape could you ping me a bit before the `next` branch goes into master, so we can get the new cli version out and some warnings during installation away?

**Pull request closed without merging**
