### PR TITLE
chore: update `schema-utils`

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
No

### Motivation / Use-Case

update `schema-utils` to v4.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
Please use `dev-1` branch

**Comment by snitin315** [comment]
in `webpack-dev-server` ?

**Comment by alexander-akait** [comment]
oh, all is fine, I think it was sent in other repo

**Review by alexander-akait — COMMENTED** [review]
Feel free to merge when CI will be green, also make sense to check other deps

**Comment by snitin315** [comment]
Will check 👍🏻

**Pull request merged**
