### PR TITLE
fix: include 'browserslist' in webTarget

### PR DESCRIPTION
**Pull request by chenxsan**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Not yet.

### Motivation / Use-Case

Close https://github.com/webpack/webpack-dev-server/issues/2758

It's a naive fix, might need more research.

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
It is not the best solution, but it is good as a temporary workaround

**Comment by chenxsan** [comment]
> It is not the best solution, but it is good as a temporary workaround

Seems `browserslist` can target Node.js too, I think I see what you mean now.

**Comment by chenxsan** [comment]
@evilebottnawi 

It seems the socket information is no longer written to stdout under webpack 5 causing a [CI failure](https://dev.azure.com/webpack/webpack-dev-server/_build/results?buildId=11594&view=logs&j=7017e997-0701-5bcc-6df9-62b58130093b&t=5f1240bf-dadc-5bfe-98f9-3b5cb760465e&l=1235):

```
yarn run v1.22.4
$ NODE_ENV=development webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/sam/Downloads/Webpack.HMR.bug.repro
ℹ ｢wds｣: 404s will fallback to /index.html
(node:45764) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
ℹ ｢wdm｣: asset src.js 405 KiB [emitted] (name: src)
asset index.html 248 bytes [emitted]
runtime modules 24 KiB 10 modules
cacheable modules 333 KiB
  modules by path ./node_modules/webpack-dev-server/ 21.2 KiB
    modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
    modules by path ./node_modules/webpack-dev-server/node_modules/ 296 bytes 2 modules
  modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
  modules by path ./node_modules/html-entities/lib/*.js 57.9 KiB 4 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB
    ./node_modules/querystring/index.js 127 bytes [built] [code generated]
    ./node_modules/querystring/decode.js 2.34 KiB [built] [code generated]
    ./node_modules/querystring/encode.js 2.04 KiB [built] [code generated]
  modules by path ./node_modules/url/*.js 23.1 KiB
    ./node_modules/url/url.js 22.8 KiB [built] [code generated]
    ./node_modules/url/util.js 314 bytes [built] [code generated]
./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
webpack 5.0.0-rc.3 compiled successfully in 627 ms
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by chenxsan** [comment]
CI on Node 6 and Node 8 failed because [webpack 5 supports Node.js 10+](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#minimum-nodejs-version).

**Comment by evilebottnawi** [comment]
Yep, can you fix it?

**Comment by chenxsan** [comment]
@evilebottnawi Are we going to support both webpack 4 and webpack 5 in webpack-dev-server v3? If yes, I guess we need to update the CI to test against both.

**Comment by evilebottnawi** [comment]
I think yep, we need support two, not all developers migrate on webpack@5

**Comment by leodr** [comment]
According to the [webpack docs](https://webpack.js.org/configuration/target/#browserslist), `browserslist:last 2 versions` would also be a valid browser target that this patch would not pick up, or am I wrong?

**Comment by chenxsan** [comment]
@leodr You are right here, it won't cover those cases as it's a naive fix at the moment.

**Comment by evilebottnawi** [comment]
@chenxsan sorry for delay, can you switch on `v4` branch these changes?

**Comment by chenxsan** [comment]
@evilebottnawi The fix is so naive that I was going to drop this PR. If you still want to accept it, I'll take care of  it tomorrow.

**Comment by evilebottnawi** [comment]
@chenxsan I want to merge it, we will improve more target logic in the future, this fix is enough

**Review by evilebottnawi — COMMENTED** [review]
target can be array, so I think we need improve it too, anyway thanks for the PR

**Comment by chenxsan** [comment]
Maybe close this one in favor of https://github.com/webpack/webpack-dev-server/pull/2841? Seems like @ylemkimon can fix it soon, hence no need to merge a workaround like this one.

**Pull request closed without merging**
