### PR TITLE
fix script name

### PR DESCRIPTION
**Pull request by kakty3**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

Change script name to match it with `npm run` command

### CODE REVIEW

**Comment by snitin315** [comment]
Let's change the command to `npm run serve` instead.

**Comment by alexander-akait** [comment]
No need, you can modify self this in own `package.json`

**Comment by snitin315** [comment]
Actually, we have shown `serve` in package.json snippet and then running `npm run start:dev` in readme https://github.com/webpack/webpack-dev-server#with-npm-scripts

**Comment by alexander-akait** [comment]
@snitin315 oh, yes, let's fix it, ideally we should write here two solutions:
1. Using `webpack serve` without commands in `package.json`
2. Custom name and run it

**Comment by snitin315** [comment]
I will update soon 👍🏻

**Pull request closed without merging**
