### PR TITLE
Fix invalid url when path is relative, sockHost='' then we must force…

### PR DESCRIPTION
**Pull request by radut**
Fix invalid url when path is relative, sockHost='' then we must force protocol ='' to properly load /sockjs-node instead of http:/sockjs-node
  

- [X] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

If you want to make your setup with relative path, to load your dev server from any ip / any other pc you cannot get it to work because it builds invalid url http:/sockjs-node instead of being actually relative: /sockjs-node

### Breaking Changes

No

### CODE REVIEW

**Comment by radut** [comment]
Tried to run the tests on master branch before I did my changes...
screenshot1609


I don't know where to start..

**Comment by evilebottnawi** [comment]
Something wrong in environment, can you provide what tests are failed?

**Comment by radut** [comment]
Running : Ubuntu 18.04.2 LTS

Runned again, but got different results : 
test suites 1 vs 3 failed
tests: 5 vs 7 failed
```
 FAIL  test/server/proxy-option.test.js (65.505s)
  ● Console

    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
      Error: listen EADDRINUSE 127.0.0.1:8080
          at Server.setupListenHandle [as _listen2] (net.js:1286:14)
          at listenInCluster (net.js:1334:12)
          at GetAddrInfoReqWrap.doListen (net.js:1460:7)
          at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)

  ● proxy option › should supports http methods › GET method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › HEAD method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/x-www-form-urlencoded)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/json)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › DELETE method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

Summary of all failing tests
 FAIL  test/server/proxy-option.test.js (65.505s)
  ● proxy option › should supports http methods › GET method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › HEAD method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/x-www-form-urlencoded)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/json)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › DELETE method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)


Test Suites: 1 failed, 58 passed, 59 total
Tests:       5 failed, 7 skipped, 446 passed, 458 total
Snapshots:   176 passed, 176 total
Time:        67.226s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-dev-server@3.7.2 test:only: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-dev-server@3.7.2 test:only script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tr/.npm/_logs/2019-07-02T13_18_30_559Z-debug.log

```

**Comment by radut** [comment]
3rd run... different results
```
 FAIL  test/server/proxy-option.test.js (64.614s)
  ● Console

    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:289
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:290
      Error: listen EADDRINUSE 127.0.0.1:8080
          at Server.setupListenHandle [as _listen2] (net.js:1286:14)
          at listenInCluster (net.js:1334:12)
          at GetAddrInfoReqWrap.doListen (net.js:1460:7)
          at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)

  ● proxy option › should supports http methods › GET method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › HEAD method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/x-www-form-urlencoded)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/json)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › DELETE method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

Summary of all failing tests
 FAIL  test/e2e/Client.test.js (27.526s)
  ● reload › inline › on browser client › should reload with page refresh

    expect(received).toBeTruthy()

    Received: false

      155 |                           expect(color).toEqual('rgb(0, 0, 255)');
      156 |                           expect(color2).toEqual('rgb(255, 0, 0)');
    > 157 |                           expect(refreshed).toBeTruthy();
          |                                             ^
      158 |                           done();
      159 |                         });
      160 |                       });

      at toBeTruthy (test/e2e/Client.test.js:157:45)

 FAIL  test/server/proxy-option.test.js (64.614s)
  ● proxy option › should supports http methods › GET method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › HEAD method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/x-www-form-urlencoded)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › POST method (application/json)

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● proxy option › should supports http methods › DELETE method

    Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 60000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)


Test Suites: 2 failed, 57 passed, 59 total
Tests:       6 failed, 7 skipped, 445 passed, 458 total
Snapshots:   176 passed, 176 total
Time:        66.505s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-dev-server@3.7.2 test:only: `jest`
npm ERR! Exit status 1

```

i'm running node : v10.11.0

npm : 6.4.1

**Comment by evilebottnawi** [comment]
Something on `127.0.0.1:8080`, maybe we need improve tests on detecting, use `node_modules/.bin/jest path/to/test` and `.only` for implement your test(s)

**Comment by radut** [comment]
nothing running on that port.

```
curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

but yeah, a detection of already used ports / find available ports and use them when testing would be great.

**Comment by radut** [comment]
the change requested is very small / easy to test, maybe you can do it, as you environment is properly set-up  : @evilebottnawi

**Comment by evilebottnawi** [comment]
@radut can't understand, we need test to avoid regressions

**Comment by radut** [comment]
yes, understood that I was hoping that you could write the test..(if you have time)

basically when including :
```
entrypoint : ['webpack-dev-server/client?']
```
with nothing more after ?, you should be able to see sockjs-node connect to same host (ip+ port ) / (localhost+port) ..etc.

I tried again to run the suite from master, on another pc .. still get some failed tests, and I don't know actually where to 'hook' my test, and how to write it(it needs to have different config than the tests already present, and must be tested trough browser chromium headless/phantomjs to validate relative path).

**Comment by alexander-akait** [comment]
Refactored in v4 ahd should not happens, if you faced with this problem again feel free to open an issue

**Comment by radut** [comment]
I will try it, thank you

**Pull request closed without merging**
