### PR TITLE
fix: remove basicConstraints extension from certificate

### LINKED ISSUE #2313: HTTPS broken on Chromium browsers
- Operating System: Arch Linux
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome 78

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// relevant part of the config
const config = {
  webpack: {
    publicPath: '/wp-content/themes/doge/dist/',
    serverAddress: 'doge.local',
    wordpressUR: 'https://doge.local',
  }
}
const { webpack } = config
const devServerPlugin = (opts = {}) => {
  const isWin = /^win/.test(process.platform)
  const isMac = /^darwin/.test(process.platform)

  // Override publicPath
  const publicPath = (isHTTPS ? 'https' : 'http') + `://${host}:${port}${webpack.publicPath}`

  return merge({
    devServer: {
      host,
      port,
      https: isHTTPS,
      stats: 'errors-only',

      overlay: {
        errors: true,
        warnings: false,
      },

      watchOptions: {
        poll: isWin || isMac ? undefined : 1000,
        aggregateTimeout: 300,
      },

      open: process.env.OPEN !== 'false',
      hotOnly: true,
      clientLogLevel: 'none',
      publicPath,

      proxy: {
        '/': {
          target: webpack.wordpressURL,
          changeOrigin: true,
          autoRewrite: true,
          secure: false,
          headers: {
            'X-Proxy': 'webpack-dev-server',
          },
        },
      },

      // Allow access to WDS data from anywhere, including the standard non-proxied WP
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
        'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization',
      },
    },

    plugins: [
      new WriteFile({
        test: /^(?!.*(hot)).*/,
      }),
      new HotModuleReplacement(),
    ],

    output: {
      publicPath,
    },
  })
}
```

### Expected Behavior
Not this.

image

### Actual Behavior

Can't access the development site because the browser doesn't let me. Downgrading to 3.8.2 fixes the issue. 

"... the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later."

### For Bugs; How can we reproduce the behavior?
Install 3.9 on Linux and use a chromium browser.

### PR DESCRIPTION
**Pull request by akx**
This fixes TLS on Chromium Linux (see #2313).

Based on https://github.com/webpack/webpack-dev-server/issues/2313#issuecomment-558400603 – thanks to @gigafied for the fix!

fixes #2313

- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No tests – I did give it a spin on Linux Chromium (via Docker and Xquartz, which is why it's shown with macOS window decoration here). As discussed in #2313, we now only get ERR_CERT_AUTHORITY_INVALID, which is skippable.

Screenshot 2019-11-26 at 10 20 30

### Motivation / Use-Case

Restores TLS functionality on Linux Chromium.

### Breaking Changes

This should not break anything, though I don't have macOS Catalina (see #2274) to test with.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I am afraid it is can break https in other browsers, we should test this on chrome/firefox/safari, anyway thanks for PR

**Comment by akx** [comment]
> I am afraid it is can break https in other browsers, we should test this on chrome/firefox/safari, anyway thanks for PR

Sorry! I forgot to mention I did test it on Chrome on macOS too, and it works:

Screenshot 2019-11-26 at 12 35 49


 Let me just fire up (heh) Firefox real quick... yep, it works 😄 

Screenshot 2019-11-26 at 12 34 57

**Comment by evilebottnawi** [comment]
@akx thanks for PR, i will look on this in near future and do more tests :+1:

**Comment by evilebottnawi** [comment]
@akx good test :+1: 

/cc @Loonride @hiroppy

**Comment by evilebottnawi** [comment]
Don't work on linux chrome :disappointed:

**Comment by hiroppy** [comment]
@evilebottnawi do you know the reason? I have only Mac...

**Comment by evilebottnawi** [comment]
@hiroppy can you try to remove `extKeyUsage` (maybe we should do revert) and check it

**Comment by hiroppy** [comment]
I think it might be better to change the targeted branch from master to next.

**Comment by evilebottnawi** [comment]
@hiroppy right now https is broken for chrome on linux, it should be not next, it is bug and we need fix it

**Comment by hiroppy** [comment]
I'm not sure this change's inpact. Anyway someone can check this change on Windows?

**Comment by evilebottnawi** [comment]
@hiroppy i think we should open issue in chrome bug tracker, because some options works on macos chrome but doesn't on linux chrome and versa vice, for me it is very strange behavior and we need more information from developers why it is happens

**Pull request merged**
