### PR TITLE
feat: add `setupMiddlewares` option

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [X] This is a **feature**
- [X] This is a **code refactor**
- [X] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes.

### Motivation / Use-Case

```js
setupMiddleware: (arrayOfMiddlewares, devServer) => {

  arrayOfMiddlewares.push('something');

  return arrayOfMiddlewares;
}
```

**TODO:** 

- [x] Deprecate `onAfterSetupMiddleware` and `onBeforeSetupMiddleware`.
- [x] E2E tests
- [x] Add examples in docs

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
Refactored and updated examples + improve perf for `setHeaders`, we don't need to attach middleware if we don't have headers

**Comment by alexander-akait** [comment]
Also refactor some places, so we now try to use `connect` [insta](https://github.com/senchalabs/connect) instead express and maybe even other servers, so in future we can migrate on any application

**Comment by alexander-akait** [comment]
@snitin315 Ideally we need add new options `server: { type: "connect", options: ...options }`, `type` can be "string" (i.e. package name or `require.resolve("connect")`) or `function`, and ideally we should tests all our functions on compatibility with connect - I think we can create new CI pipeline and setup tests to using `connect` instead `express` using jest aliases

**Comment by snitin315** [comment]
> @snitin315 Ideally we need add new options `server: { type: "connect", options: ...options }`, `type` can be "string" (i.e. package name or `require.resolve("connect")`) or `function`, and ideally we should tests all our functions on compatibility with connect - I think we can create new CI pipeline and setup tests to using `connect` instead `express` using jest aliases

Yes, I think we can create a separate pipeline for `connect`. I will try adding one.

**Comment by alexander-akait** [comment]
@snitin315 I was wrong, we need `application: { type: "connect", options: ...options }` (default value is `express`) in long term we should migrate on `connect` or maybe something more simple, express is not get updated a long time, but we need to support `http2`/`https` without any problems and workarounds, I think now we can setup our tests and fix code for `connect` and them add this options, so we can have two-three PRs

**Comment by Airkro** [comment]
The API is not easy to understand like before, what's the advantage of `setupMiddlewares`?

**Comment by alexander-akait** [comment]
What is misleading? It was implemented to allow developers use own middlewares and even replaces built-in

**Pull request merged**
