### PR TITLE
chore: ask for webpack-cli version in issue template

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

Ask for `webpack-cli` version.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by anshumanv — COMMENTED** [review]
I think webpack@serve is relevant too?

**Review by rishabh3112 — CHANGES_REQUESTED** [review]
Left a suggestion.

**Review by rishabh3112 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]
nicenicenice

**Comment by rishabh3112** [comment]
Thanks

**Pull request merged**
