### PR TITLE
fix: respect the `client.logging` option for HMR logging

### LINKED ISSUE #2932: Cannot mute `[HMR] Waiting for update signal from WDS...` in browser console
- Operating System: macOS 11.1
- Node Version: v14.12.0
- NPM Version: v6.14.8
- webpack Version: v5.10.1
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: Chrome & Safari

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
{
  ...
  devServer: {
    client: {
      logging: 'none',
     ...
    },
    ...
  },
}
```

### Expected Behavior

Setting client logging to `none` should suppress completely all client log, including from the hot chunk.

### Actual Behavior

The log `[HMR] Waiting for update signal from WDS...` is still outputted to browser console when loading the page.

### For Bugs; How can we reproduce the behavior?

Simply start webpack-dev-server with any kind of configuration (just don't pass `hot: false`), and check the browser console when the page has loaded.

From what I understood, that's because [the default logging level of the hot chunk is `info`](https://github.com/webpack/webpack/blob/master/hot/log.js#L1), and it is overwritten by webpack-dev-server client by calling [the exported `setLogLevel` function](https://github.com/webpack/webpack/blob/master/hot/log.js#L45).

But that function is only called once the webpack-dev-server client receives [a `logging` command](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L73) that is send [when creating the socket server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L560). That only happens [after the web server has been started and is listening](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L687).

That specific logging happens [as soon as the hot chunk is loaded](https://github.com/webpack/webpack/blob/master/hot/dev-server.js#L58), which is before the webpack-dev-server client receives that `logging` command from the socket server.

I don't have enough context to know which would be the best way to solve this, but let's start a discussion about it in here.

### PR DESCRIPTION
**Pull request by alexander-akait**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

fixes #2946 fixes #2932

### Motivation / Use-Case

Allow to disable extra logging from webpack

### Breaking Changes

No

### Additional Info

- I keep logging api, so other modules can change it in runtime
- fix broken `currentScript` parsing
- support `new URL()` and Node.js legacy format
- refactor
- more tests

### CODE REVIEW

**Comment by alexander-akait** [comment]
Will finish tomorrow, need improve client for `file` protocol and test https with localhost

**Comment by snitin315** [comment]
@alexander-akait  what is still in TODO here?

**Comment by alexander-akait** [comment]
WIP on tests, broken only on Node.js 10 due bug in `url` module implementation

**Comment by snitin315** [comment]
Node 10 is about to reach its end of life 😞

**Comment by alexander-akait** [comment]
Yep, but I think webpack-dev-server v4 will have short time, we should refactor it to plugin, I'll show you how to do it

**Comment by alexander-akait** [comment]
We will improve coverage after refactor `public`/`client.sock*` properties

**Pull request merged**
