### PR TITLE
chore(deps): update chokidar to v3

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

This PR is separated from other updated deps PRs because I want to know how chokidar goes.

### Breaking Changes

yes, chokidar doesn't support Node@6.

### CODE REVIEW

**Comment by paulmillr** [comment]
Do you know why there are two chokidar versions in package-lock.json? I see 2.1 and 3.3.

**Comment by hiroppy** [comment]
I think another package depends on Chokidar. I don't have a laptop now but I'll check it.(maybe dev-middleware)

**Comment by paulmillr** [comment]
All good. That was `@babel/cli` and it's devDependency, which means end-users won't install it.

**Comment by paulmillr** [comment]
There is zero need to make the close method async. Don't you know a promise is just an abstraction over a callback function?

```js
  close(cb) {
    this.sockets.forEach((socket) => {
      this.socketServer.close(socket);
    });
    this.sockets = [];
    let prom = Promise.all(this.contentBaseWatchers.map(watcher => watcher.close()));
    this.contentBaseWatchers = [];
    this.listeningApp.kill(() => {
      this.middleware.close(() => {
        prom.then(cb);
      });
    });
  }
```

**Comment by evilebottnawi** [comment]
@paulmillr bad idea, tests will be unstable + jest will be warning about unclosed processes + other code can use `close` as method that guarantees close, so multiple listen/close could potentially cause a failing due to memory consumption

**Comment by evilebottnawi** [comment]
@paulmillr makes sense, but we still have to fix it because our code now closes everything synchronously

**Comment by paulmillr** [comment]
That is not true. Your close method specifically expects a callback. It then passes the callback below, to `this.middleware.close()`. If `middleware.close` expects a callback, then obviously your `close` method **is not** syncronous.

**Comment by evilebottnawi** [comment]
@paulmillr 

> That is not true

What is not true ? :confused: 

We close chokidar watchers synchronously here https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L804 in master. What are you talking about?

**Comment by paulmillr** [comment]
Yean, you can just apply my patch above and nothing from those are going to break. The external api for them will remain the same. 

>yep we can potential will break many boilerplates like vue-cli, CRA

**Comment by evilebottnawi** [comment]
@paulmillr I already said that this is a good idea/makes sense, what is the problem?

**Pull request closed without merging**
