### PR TITLE
fix: add none and warning to clientLogLevel

### PR DESCRIPTION
**Pull request by hiroppy**
fixes: #1899
ref: #1825

- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

hotfix and modify tests

### Motivation / Use-Case

see #1899

### Breaking Changes

no

### CODE REVIEW

**Comment by hiroppy** [comment]
I didn't modify the description of `bin/options.js` and `lib/options.json` because these values should be deprecated.

**Comment by hiroppy** [comment]
I created a ticket. https://github.com/webpack/webpack-dev-server/projects/1#card-21668614

**Comment by evilebottnawi** [comment]
Need update shapshot, maybe we can rewrite this test from shapshot to other testing style

**Comment by hiroppy** [comment]
Yes, I forgot that I have rewritten client-src. 😇

**Comment by hiroppy** [comment]
updated

**Comment by evilebottnawi** [comment]
let's ignore `npm audit` (i don't know what the hell with npm again)

**Comment by hiroppy** [comment]
CI is green

**Pull request merged**
