### PR TITLE
Put in existence check for document so live reload will work in webworker

### PR DESCRIPTION
**Pull request by matthewdenobrega**
This is a fix for #308

### CODE REVIEW

**Comment by gdi2290** [comment]
:+1: I need this too

**Comment by jteplitz602** [comment]
:+1: Also running up against this issue

**Comment by ocombe** [comment]
:+1: 
Easy fix, could you merge this please, it would help for unusual environments such as webworkers :)

**Comment by gdi2290** [comment]
can you rebase

**Comment by matthewdenobrega** [comment]
#298 is a fix for the same thing and includes an extra check - unless there's an issue with the extra check I'd suggest #298 gets used for this.

**Comment by jFensch** [comment]
Any progress on this?  Would be awesome to get working with Angular2 supporting web workers.

**Comment by TheLarkInn** [comment]
@matthewdenobrega could you please check and see if you can resolve conflicts on your side first?

**Comment by sokra** [comment]
No longer needed, because webpack-dev-server/client accepts a query string which contains the hostname.

`webpack-dev-server/client?http://url-to-webpack-dev-server:port/`

This will omit the access to `document`

**Pull request closed without merging**
