### PR TITLE
feat: async API

### PR DESCRIPTION
**Pull request by alexander-akait**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

WIP

### Motivation / Use-Case

new async API + new callback API for compatibility purposes

### Breaking Changes

No

### Additional Info

`listen` and `close` depreacted

### CODE REVIEW

**Comment by alexander-akait** [comment]
@snitin315 after this PR we should rewrite out tests on new API (async API) and remove `test/helpers/test-server.js` in favor `const server = new Server(); await server.start(); /* Test logic */ server.close()`. Should be easy task

**Comment by snitin315** [comment]
I will update 👍🏻

**Comment by alexander-akait** [comment]
Now our tests is smaller due async API

**Comment by alexander-akait** [comment]
The next step - migration webpack-cli on the new async API, WIP

**Pull request merged**
