### PR TITLE
fix: content security policy issue in client log

### PR DESCRIPTION
**Pull request by raix**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

Fix CSP issue client logger, idea for solving #3062

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Good solution, let's unmark it from draft

**Comment by snitin315** [comment]
Rebased to https://github.com/webpack/webpack-dev-server/pull/3078

**Comment by alexander-akait** [comment]
Fixed, thanks for PR

**Comment by raix** [comment]
Thanks for the merge :)

**Pull request closed without merging**
