### PR TITLE
refactor: tests

### PR DESCRIPTION
**Pull request by evilebottnawi**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

not required

### Motivation / Use-Case

Refactor test part #1

### Breaking Changes

No

### Additional Info

Ideally each option **should have**:
1. Unit test (own)
2. Integration test (Server.test.js)
3. E2E test (can be avoided for non client options)
4. CLI test (can be avoided right now)

We should concentrate on `1` and `2` points right now.

Other changes what we should do:
- avoid using `--runInBand` it is decrease time on tests
- union option.test.js and validation.test.js (they do same)
- rewrite some test in more effective way
- better naming of tests

### CODE REVIEW

**Comment by hiroppy** [comment]
maybe we can not avoid using `--runInBand` because many tests have same port.

**Comment by evilebottnawi** [comment]
@hiroppy We can setup for tests using difference port :smile:

**Comment by hiroppy** [comment]
Yes, but we should consider managing ports because it is easy to conflict ports.

**Comment by evilebottnawi** [comment]
I think we can use `getPort` utils in test helper, it is require refactor, but it is possible and tests always use difference port

**Comment by evilebottnawi** [comment]
Anyway let's do it in other PRs, not here :smile:

**Comment by evilebottnawi** [comment]
Missing snapshot (updated)

**Pull request merged**
