### PR TITLE
refactor: exlcude `hot` for cli

### PR DESCRIPTION
**Pull request by snitin315**
- [X] This is a **bugfix**
- [ ] This is a **feature**
- [X] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Already present, CI should be green.

### Motivation / Use-Case

`webpack-cli` already defines `--hot`, so it is kind of just duplicate code.

Also right now it shows `--hot` two times because of this in suggestions on passing a wrong cli option.

## Before 
Screenshot 2021-07-12 at 5 35 42 PM

## After
Screenshot 2021-07-12 at 5 35 51 PM

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
here interesting case, I think we should solve it on webpack-cli level, here https://github.com/webpack/webpack-dev-server/pull/3522, for webpack-dev-server we support the `hot` option, but webpack-cli should merge them

**Comment by snitin315** [comment]
It looks like we may need it here, and should update code in webpack-cli to not show `--hot` multiple times.

**Comment by alexander-akait** [comment]
Yep, I think we should fix it in webpack-cli

**Comment by snitin315** [comment]
hmm, will fix it 👍🏻

**Comment by alexander-akait** [comment]
To be honestly I think we remove `--hot` from `webpack-cli`, for developers who want to use hot module replacement for non browser env should add plugin manually

**Comment by snitin315** [comment]
I think the same, let's remove from cli

**Comment by alexander-akait** [comment]
Yep, I think we can start to create the next branch in webpack-cli and start to working, drop webpack v4, drop node v10 and some other stuff, feel free to start and I will add small readmap (there are no a lot of work in webpack-cli for the next major release)

**Comment by snitin315** [comment]
Will do 👍

**Comment by alexander-akait** [comment]
@snitin315 Let's close here, it will be for webpack-cli@next

**Comment by snitin315** [comment]
Yep  we can close.

**Pull request closed without merging**
