### PR TITLE
chore: regenerate lockfile

### PR DESCRIPTION
**Pull request by rishabh3112**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
N/A

### Motivation / Use-Case
regenerate lock file

### Breaking Changes
No

### Additional Info
No

### CODE REVIEW

**Comment by snitin315** [comment]
Cn you run `npm audit fix`?

**Comment by rishabh3112** [comment]
> Can you run `npm audit fix`?

Yeah I already did. `glob-parent` comes from `babel-cli` and they have not patched it.

**Comment by rishabh3112** [comment]
Here is screenshot for the sake of it
image

**Review by snitin315 — APPROVED** [review]

**Comment by alexander-akait** [comment]
hm, so bug in babel package?

**Review by alexander-akait — APPROVED** [review]
Let's merge, I will fix it later

**Pull request merged**
