### PR TITLE
Include the listening port number in the server object

### PR DESCRIPTION
**Pull request by doughamlin**
**What kind of change does this PR introduce?**
feature

**Did you add or update the `examples/`?**
no

**Summary**
Exposes the listening port number in the server object. 
Implements request in #998.

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by doughamlin** [comment]
I just realized this doesn't fully address the request in #998 because there is no `listening` event. It is easy enough to extend Server from EventEmitter and emit the `listening` event when the server starts listening, but I question the need for that when the server object is accessible inside the `server.listen` callback.

**Comment by shellscape** [comment]
Much appreciate you taking the time to open a PR 🍻  however #998 seems to me to request automatic port assignment, rather than just exposing the port assigned. I'm not sure you're on the same page as the issue author here.

**Comment by doughamlin** [comment]
@shellscape Yeah, I don't know why I thought portfinder was already being used in lib/Server.js already. It is used in bin/webpack-dev-server.js and could be added to Server.js. Would you want to remove it from webpack-dev-server.js in that case?

**Comment by shellscape** [comment]
closing in favor of #1054. thanks again for the PR.

@doughamlin I _think_ portfinder is still needed to check to see if the specified port is in use.

**Pull request closed without merging**
