### PR TITLE
fix: improve error handling for WebsocketServer

### PR DESCRIPTION
**Pull request by snitin315**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case
Fix https://github.com/webpack/webpack-dev-server/issues/5018

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Let's add a test case or a small todo to add a test case, I know it is the right solution, but I don't have time right now to test it

**Comment by snitin315** [comment]
added a todo.

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Tests are stable on linux and windows, but still unstable on macos I will look in future

**Comment by alexander-akait** [comment]
Thank you

**Comment by WillieHabi** [comment]
> Tests are stable on linux and windows, but still unstable on macos I will look in future

Has this been fixed on MacOS? Still seeing this error with webpack-dev-server

**Pull request merged**
