### PR TITLE
chore(deps): update dependencies

### PR DESCRIPTION
**Pull request by GChuf**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

Updates dependencies

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
What we update? Just regenerate lock file? Can you accept CLA?

**Comment by GChuf** [comment]
Yes, just regenerate lock file. I accepted CLA already, look above :)

**Comment by GChuf** [comment]
@evilebottnawi @Loonride @hiroppy please check this pull request again, all tests have passed now.

**Comment by evilebottnawi** [comment]
Let's merge

**Pull request merged**
