### PR TITLE
chore(deps): update chokidar

### PR DESCRIPTION
**Pull request by seancrater**
- [ x ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Tests might be N/A for this since it's just a deps update

### Motivation / Use-Case
See #2505 

### Breaking Changes
N/A

### Additional Info
Only manually upgraded `chokidar`

### CODE REVIEW

**Comment by ashfordneil** [comment]
Errors coming from 3 places:
- NodeJS download giving 500s when CI was running (probably just needs a rerun, I hope)
- Tests actually failing (test/e2e/Iframe.test.js - Client iframe console.log › hot disabled)
- Failures to compile new chokidar version using test setup.

The first one I don't think you can do anything about, but hopefully it was just bad luck and it stops happening next time.

The second one maybe try running the test locally on your branch and the branch before the upgrade to see if the upgrade broke it or not?

The third one, chokidar's latest version changed the close function to be async. The definition of the now-async close method is registering as a syntax error during jest's compile stage. See if there's something weird going on with babel's async / runtime transform step? And see if it builds normally on your machine, I guess, while not in test mode.

**Comment by evilebottnawi** [comment]
Please stop send a chokidar updates, it is breaking change and we can't merge it. It is already done for next branch

**Comment by seancrater** [comment]
Fair enough @evilebottnawi, can you guys please cut a release soon then? There are serious security issues with your current release from that package

**Comment by evilebottnawi** [comment]
There are no serious security issues, please update lock file, no ETA right now

**Comment by seancrater** [comment]
You aren’t supposed to manually manipulate lock files...and there are, check here: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

**Comment by evilebottnawi** [comment]
snyk is not reaindexed our repo

**Comment by seancrater** [comment]
GitHub is flagging the dependency on this old version of minimalist from webpack-dev-server as a risk. Sure, I’ll hack edit my package-lock for now but in the future I’d ask that you guys consider minor releases to keep deps updated since devs shouldn’t be manually editing their package-lock since it’s an automatically generated file.

**Pull request closed without merging**
