### PR TITLE
feat: remove caret in @types/ws package version

### PR DESCRIPTION
**Pull request by JansenMoscol**
I have error with version 8.5.5

node_modules/@types/ws/index.d.ts(328,18): error TS2315: Type 'Server' is not generic.

### CODE REVIEW

**Comment by alexander-akait** [comment]
Why?

**Comment by JansenMoscol** [comment]
Because I have error with version 8.5.5

node_modules/@types/ws/index.d.ts(328,18): error TS2315: Type 'Server' is not generic.

**Comment by alexander-akait** [comment]
Please fix your typescript, it is transitive dependency

**Comment by JansenMoscol** [comment]
It's not my code, the new version @types/ws 8.5.5 broke the library. You can try doing a clean install.

**Comment by alexander-akait** [comment]
@JansenMoscol In this case please open an issue in `@types/ws`, i.e. in https://github.com/DefinitelyTyped/DefinitelyTyped

**Pull request closed without merging**
