### PR TITLE
refactoring and replacing bin/webpack-dev-server

### PR DESCRIPTION
**Pull request by shellscape**
**What kind of change does this PR introduce?**
Replaces `bin/webpack-dev-server` with `cli.js` and a `bin` entry in `package.json`
Removes `bin/webpace-dev-server`
Refactors the entire CLI codebase.

**Did you add or update the `examples/`?**
Not as yet. This will be done once the refactor is approved.

**Summary**
The intention behind the refactor is to provide a more modular CLI codebase that can be tested along with the API to improve coverage and consistency between releases. This refactor will also lend to the future effort of synch'ing the CLI and API.

This PR also aims to improve the readability and maintainability of the code.

**Does this PR introduce a breaking change?**
The goal is not to :)

**Other information**
Once the refactor is approved the following will be added to this PR; tests will be created around the various modules for the CLI, the CLI will be tested against all examples, and the example READMEs will be updated to reflect the new CLI path. 

PR will remain open for comments until Monday Sept 25th. Note that this will be merged into the `beta` branch, and not `master` until v3 is complete.

### CODE REVIEW

**Comment by ev1stensberg** [comment]
Maybe this could align well with the CLI efforts to merge into webpack?

**Comment by shellscape** [comment]
@ev1stensberg my apologies, I'm not following. I'm not aware of an effort to merge this project with the main webpack project.

**Comment by shellscape** [comment]
please weigh in if you have comments on this refactor

**Comment by ev1stensberg** [comment]
I'll take a look at it tomorrow, may be no conflicts at all

**Comment by shellscape** [comment]
@ev1stensberg will likely merge and move forward tomorrow morning ET. not to say I can't make modifications should discussion warrant, but I let this sit for a week for comment and gotta get moving on the other aspects of the v4 milestone 😄

**Comment by ev1stensberg** [comment]
Sure, I think the only issue here would be that you'd ( in the future ) access an empty repo, and you'd need to change the imports to the cli instead of regular webpack, if you understand

**Pull request merged**
