### PR TITLE
chore: update selfsigned dependency for a security patch

### PR DESCRIPTION
**Pull request by darthsoup**
- [x] This is a **dependency update**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

Security vulnerability in the selfsigned dependency caused by node-forge

### CODE REVIEW

**Comment by afdev82** [comment]
any news on this? Thank you :)

**Comment by darthsoup** [comment]
> any news on this? Thank you :)

nope.... local testing works fine, unittests only crashes on azure testing instances

PS: sorry for the duplicated MR. I did not notice at first sight

**Comment by reginandrade** [comment]
is there an anticipated timeframe for fixing failing checks and getting this merged? thank you.

**Comment by smridge** [comment]
CVE function in question does not appear to be directly used in this repo or `forge`
https://github.com/digitalbazaar/forge/blob/588c41062d9a13f8dc91be3723b159c6cc434b15/CHANGELOG.md#L11-L42 .

@hiroppy / @evilebottnawi / @Loonride thoughts on using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or the [npm equivalent](https://github.com/rogeriochaves/npm-force-resolutions) until this is merged?

**Comment by smridge** [comment]
Apologies, I just realized this is a duplicate PR of https://github.com/webpack/webpack-dev-server/pull/2740 & https://github.com/webpack/webpack-dev-server/pull/2795 . Seems like using our own override in the interim would be the best solution until the CI gets fixed.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/pull/2740

**Pull request closed without merging**
