### PR TITLE
chore: make client overlay default to be true

### PR DESCRIPTION
**Pull request by rishabh3112**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Yes, will add

### Motivation / Use-Case
suggested by @alexander-akait 

### Breaking Changes
No

### Additional Info
No

### CODE REVIEW

**Comment by snitin315** [comment]
Let's fix CI.

**Comment by rishabh3112** [comment]
> Let's fix CI.

Any suggestions, I updated snapshots but it is now regressing on hash values, which will be different every time.

**Comment by snitin315** [comment]
You can replace hash in a snapshot with `<hash>`, like we do for ports https://github.com/webpack/webpack-dev-server/blob/5f649010f96bb8cee551fa5c4cb53ce7ea740406/test/helpers/test-bin.js#L61

**Comment by rishabh3112** [comment]
Okay, I will try

**Pull request closed without merging**
