### PR TITLE
fix: user server port for websocket connection by default

### PR DESCRIPTION
**Pull request by alexander-akait**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

bugfix/refactor

### Motivation / Use-Case

https://github.com/webpack/webpack-cli/pull/2624

### Breaking Changes

No

### Additional Info

Need test

### CODE REVIEW

**Review by anshumanv — DISMISSED** [review]

**Review by snitin315 — APPROVED** [review]

**Comment by alexander-akait** [comment]
Hope we don't break anything, proxy is really difficult cases, here possible values
- proxy by hostname, dev server is `0.0.0.0:8081` (port can be any due `findPort`), proxy on `my.site:8081`, no problems because port is the same, `0.0.0.0` can be changed on `self.locations.hostname`
- proxy by hostname and port,  dev server is `0.0.0.0:8081` (port can be any due `findPort`), proxy on `my.site:9091`, after this PR we should not have problems because we set `8081` port for client entry

**Comment by alexander-akait** [comment]
Possible cases for tests:
- different hostnames and different ports, example -  proxy on `site.loc` and port is `9090`, dev server on `127.0.0.1` and port is `8080`
- different hostnames and same ports, example -  proxy on `site.loc` and port is `8080`, dev server on `127.0.0.1` and port is `8080`
- same hostnames and different ports, example -  proxy on `127.0.0.1` and port is `9090`, dev server on `127.0.0.1` and port is `8080`
- same hostnames and same ports, impossible

**Comment by alexander-akait** [comment]
hm, I need time for better testing this

**Comment by alexander-akait** [comment]
Finished...

**Pull request merged**
