### PR TITLE
Added Proxy Options

### PR DESCRIPTION
**Pull request by vmaudgalya**
```
// Sample usage in webpack.config.js file
module.exports = merge(common, {
    devtool: 'eval-source-map',
    devServer: {
      historyApiFallback: true,
      hot: true,
      inline: true,
      progress: true,

      proxy: {
        "/first/api/*": "http://localhost:8100",
        "/second/api/*" : "http://localhost:8200",
        "/third/api/*" : "http://localhost:8300",
        "/fourth/api/*" : "http://localhost:8400",
        "/fifth/api/*" : "http://localhost:8500"
      },
      onProxyReq : function (proxyReq, req, res) {
        if (req.path.indexOf("/first/api") === 0) {
          console.log("Called first API!");
        }
        Object.keys(proxyHeaders).forEach(function (header) {
          proxyReq.setHeader(header, proxyHeaders[header]);
        });
      }
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin()
    ]
  });
```

Allows for listening to the ```onProxyReq``` event and performing actions accordingly (in this case setting headers)

### CODE REVIEW

**Comment by vmaudgalya** [comment]
I am currently using the bundled files, please let me know if/when you approve of the proxy options and I'll clean up this commit and revert ```3027379```

**Comment by jamsesso** [comment]
This ability was added in #359 (merged) along with onProxyRes and others.

**Comment by vmaudgalya** [comment]
@jamsesso Thanks for letting me know! If you don't mind, could you please provide me with an example of it being used with the use case I have above?

More specifically, how would I do this?
```
proxy: {
        "/first/api/*": "http://localhost:8100",
        "/second/api/*" : "http://localhost:8200",
        "/third/api/*" : "http://localhost:8300",
        "/fourth/api/*" : "http://localhost:8400",
        "/fifth/api/*" : "http://localhost:8500"
      },
      onProxyReq : function (proxyReq, req, res) {
        if (req.path.indexOf("/first/api") === 0) {
          console.log("Called first API!");
        }
        Object.keys(proxyHeaders).forEach(function (header) {
          proxyReq.setHeader(header, proxyHeaders[header]);
        });
      }
```

**Comment by vmaudgalya** [comment]
I figured it out: http://webpack.github.io/docs/webpack-dev-server.html
If anyone finds this, I used
```
{
    devServer: {
        proxy: {
            '/some/path*': {
                target: 'https://other-server.example.com',
                secure: false,
                bypass: function(req, res, proxyOptions) {
                    if (req.headers.accept.indexOf('html') !== -1) {
                        console.log('Skipping proxy for browser request.');
                        return '/index.html';
                    }
                },
            },
        },
    },
}
```
from the documentation and modified the headers I was sending out.

**Pull request closed without merging**
