### PR TITLE
Only load bonjour when needed

### LINKED ISSUE #955: Windows 10 Bash on Windows Error: addMembership EINVAL
After updating from 2.4.5 to 2.5.0 it starts to give an error during start up. It happens straight away. 
```bash
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors

 10% building modules 1/1 modules 0 activeevents.js:182
      throw er; // Unhandled 'error' event
      ^

Error: addMembership EINVAL
    at exports._errnoException (util.js:1016:11)
    at Socket.addMembership (dgram.js:579:11)
    at Socket.<anonymous> (/mnt/f/****/****/app/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at startListening (dgram.js:144:10)
    at _handle.lookup (dgram.js:249:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! *****@4.4.0 dev: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the *****@4.4.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/****/.npm/_logs/2017-06-22T13_00_13_678Z-debug.log
```
Hide some sensitive info by star symbol.

I'm using dev server on Bash on Windows (Ubuntu inside Windows 10). As error showes problem with sockets, it's impossible to use sockets or other core stuff on Bash on Windows only user mode. I guess error related to this limitation. How this can be fixed?  
Looks not good, some minor update completely breaks stuff.

### PR DESCRIPTION
**Pull request by joelface**
**What kind of change does this PR introduce?**
Bugfix for #955 

**Did you add or update the `examples/`?**
n/a

**Summary**
Fixes #955 so WDS will work again on Windows 10 Bash (as long as the --bonjour option isn't specified).

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by simnalamburt** [comment]
I tested it in my local WSL and it worked perfectly.

**Comment by rifflock** [comment]
Is this scheduled to be merged at any point? I'm currently using the workaround (which needs to be reimplemented after every npm install)

**Comment by simnalamburt** [comment]
Dear maintainers. If you're concerned about coding style, let's do it like this

```diff
diff --git a/bin/webpack-dev-server.js b/bin/webpack-dev-server.js
index f39b6ef..4f70797 100755
--- a/bin/webpack-dev-server.js
+++ b/bin/webpack-dev-server.js
@@ -8,7 +8,7 @@ const net = require("net");
 const portfinder = require("portfinder");
 const addDevServerEntrypoints = require("../lib/util/addDevServerEntrypoints");
 const createDomain = require("../lib/util/createDomain");
-const bonjour = require("bonjour")();
+const Bonjour = require("bonjour");

 // Local version replaces global one
 try {
@@ -455,6 +455,7 @@ function reportReadiness(uri, options) {
 }

 function broadcastZeroconf(options) {
+       const bonjour = Bonjour();
        bonjour.publish({
                name: "Webpack Dev Server",
                port: options.port,
```

###### Reference
- https://github.com/simnalamburt/webpack-dev-server/commit/4bafab1824c18d41be57bdd65a758c45448fc5e3

**Comment by AndyBarron** [comment]
Anything blocking this?

**Comment by drazisil** [comment]
It looks like @joelface needs to rebase. I'm not sure if that's blocking anything, but it's an issue per GitHub's PR UI that would prevent an easy merge.

**Comment by joelface** [comment]
@drazisil Taken care of.

I'm happy to make any changes necessary to get this merged in.

**Comment by drazisil** [comment]
@SpaceK33z Can you or another maintainer take a look at this PR?

It's somewhat blocking for Windows programmers, as npm/yarn install undoes the workaround each time.
Thank you in advance, and please let us know if anything else is needed.

**Comment by mredbishop** [comment]
Is this about to be merged in?

**Comment by shellscape** [comment]
folks, please try to hold off on the multiple comments asking about merge status and pinging contributors. it's awesome that you're all enthusiastic! but unfortunately it only serves to clutter the PR conversation and it's poor form. A much better way to go would be to add your reaction to the original post for this PR. maintainers, contributors, and admins will get to user submissions - webpack is a great org and makes sure that happens - but it's not our full time gig, and rest assured we see *_all_* of the notifications.

**Pull request merged**
