### PR TITLE
fix: do not inject client when hot and livereload disabled

### LINKED ISSUE #3276: [WDS] App updated. Recompiling... - Called many times in one go
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

`[WDS] App updated. Recompiling...` - Called many times. I see this log in the browser log.

My configue

```
module.exports = {
  stats: "normal",	
  mode: 'development',	
  entry: './src/index.js',
  devtool: 'inline-source-map',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js',
  },
 module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
	      {
		   loader: 'style-loader',
	      },
	      'css-loader'
        ],
      },
    ],
  },
  devServer: {
  	https: false,
  	liveReload: false,
  	hot: false,
  	overlay: false,
        contentBase: './dist',
        noInfo: true,
        after: function (app, server, compiler) {
             console.log('---------after-----------');
        }, 
        before: function (app, server, compiler) {
             console.log('---------before-----------');
        },   
  },  
};
```

When I change `./src/index.js` compilation must be done once. But it is performed at least twice in a row.
And if I update the javascript from another script, it gets executed multiple times.

As example:

With each call to the `refresh_script` function, the number of compilations will be multiplied by two.

- If call `refresh_script` **zero times**: compilations will be = 2 times at a time
- If call `refresh_script` **once times**: compilations will be = 4 times at a time
- If call `refresh_script` **two times**: compilations will be = 6 times at a time

**dist/index.html**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>123</title>
  </head>
  <body>
    <script src="./bundle.js"></script>
    <script>
	setTimeout(function(){ 

            refresh_script(
            	document.getElementsByTagName("script")[0]
            );

	}, 3000);


	setTimeout(function(){ 

            refresh_script(
            	document.getElementsByTagName("script")[0]
            );

	}, 6000);

  
        function refresh_script($old_node){
            const $new_node = document.createElement('script');

            Object.keys($old_node.attributes).forEach(function(i){
                $new_node.setAttribute(
                    $old_node.attributes[i].nodeName, 
                    $old_node.attributes[i].nodeValue
                );
            });

            $old_node.parentNode.replaceChild($new_node, $old_node); 
        }
    </script>
  </body>
</html>
```

**Other relevant information:**
webpack version:  5.36.2
Node.js version:  v10.16.3
Operating System:  Win 10 x64 build latest
Additional tools:

### PR DESCRIPTION
**Pull request by alexander-akait**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

fixes #3276

### Motivation / Use-Case

No need to inject client entry when hot and live reload disabled

### Breaking Changes

No

### Additional Info

WIP on tests

### CODE REVIEW

**Review by snitin315 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Most of e2e test are rewritten, I will rewrite `web-socket-server-url.test.js` test tomorrow and it will be pure and simple test

**Review by snitin315 — DISMISSED** [review]
Looks Good!

**Comment by alexander-akait** [comment]
Hope, all will be fine, we still need test improvements, but now it should be better

**Review by anshumanv — APPROVED** [review]

**Comment by alexander-akait** [comment]
I have our tests, really, it is magic

**Comment by alexander-akait** [comment]
Found other bug in `magicServe` feature, we does not wait when a compilation finished, fixed

**Comment by alexander-akait** [comment]
We have around 3 errors here, I want to merge it as is to continue fixing, due very very very bad out test we doesn't catch them, now we catch around 5-6 bugs

**Pull request merged**
