### PR TITLE
chore: migrate to `nanocolors`

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
No

### Motivation / Use-Case

Update to `colorette` v2

`options.enabled` was removed.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
I will look at this today :+1: Also on other comments

**Comment by alexander-akait** [comment]
@snitin315 Let's migrate on https://github.com/ai/nanocolors, for `webpack-cli` and `webpack-dev-middleware`

**Comment by snitin315** [comment]
I will migrate 👍

**Comment by snitin315** [comment]
Should we migrate to `nanocolors` here too?

**Comment by alexander-akait** [comment]
@snitin315 Yes

**Pull request merged**
