### PR TITLE
chore(deps): upgrade chokidar

### PR DESCRIPTION
**Pull request by Loonride**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Not yet

### Motivation / Use-Case

upgrade chokidar to v3.3

### Breaking Changes

chokidar doesn't support node v6

close should work the same

### Additional Info

Edit: didn't see https://github.com/webpack/webpack-dev-server/pull/2533 when I did this, I just applied the patch suggested there

### CODE REVIEW

**Comment by Loonride** [comment]
Didn't see https://github.com/webpack/webpack-dev-server/pull/2533, I just applied the patch suggested

**Comment by paulmillr** [comment]
Can we get a new release out?

**Comment by georgemillo** [comment]
> Can we get a new release out?

+1, I'm effectively blocked on one of my projects until I lose the dependency on Chokidar 2.

**Comment by evilebottnawi** [comment]
@paulmillr next week, we are very quickly working on fixes for new next release

**Comment by paulmillr** [comment]
@evilebottnawi how is the new release doing?

**Pull request merged**
