### PR TITLE
[NEXT]: rebase master on next branch

### PR DESCRIPTION
**Pull request by Loonride**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

N/A

### Motivation / Use-Case

/cc @hiroppy I decided to try rebasing next branch. It is fine if you don't want to do it this way, I just wanted to get the experience of this large rebase with git.

If I made a mistake with the rebase, is it fine to add additional commits fixing the problem? Or does it cause an issue that the commit in history now has a mistake?

### Breaking Changes

N/A

### CODE REVIEW

**Comment by hiroppy** [comment]
Thanks.

>  if you don't want to do it this way, I just wanted to get the experience of this large rebase with git.

Don't worry. 

> If I made a mistake with the rebase, is it fine to add additional commits fixing the problem? Or does it cause an issue that the commit in history now has a mistake?

Yes.

diff: https://github.com/webpack/webpack-dev-server/compare/master...next

**Comment by hiroppy** [comment]
@Loonride Can you change the commit message?

> fix(test): fix some lint problems

because this is lint problems so you should change to `refactor`, and we don't need to add this thing to CHANGELOG.md. If you use `fix`, it will be added automatically.

**Comment by hiroppy** [comment]
And I think your rebase is failed because we get only diff between master and next on this pr.

**Comment by Loonride** [comment]
> @Loonride Can you change the commit message?
> 
> > fix(test): fix some lint problems
> 
> because this is lint problems so you should change to `refactor`, and we don't need to add this thing to CHANGELOG.md. If you use `fix`, it will be added automatically.

Oh yes sorry. Also, there is some `async/await` stuff that I just skipped over in tests, just leaving the nested async functions instead. Should we update those things in a new PR?

**Comment by Loonride** [comment]
> > If I made a mistake with the rebase, is it fine to add additional commits fixing the problem? Or does it cause an issue that the commit in history now has a mistake?
> 
> Yes.
> 
> diff: [master...next](https://github.com/webpack/webpack-dev-server/compare/master...next)

You mean it is fine that I edited history in the way I did, or it is a problem?

Doesn't it make more sense to look at it this way: [next...master](https://github.com/webpack/webpack-dev-server/compare/next...master) Since I am placing these commits on top of `next` branch?

**Comment by Loonride** [comment]
Was the allowed length of a commit message changed? I think that is why Lint is failing.

**Comment by hiroppy** [comment]
e.g. 

These commits are the same but currently, the commit hash is changed.

this pr: https://github.com/webpack/webpack-dev-server/commit/f5791a0cfb51ff2fd0b0f8587b98abcf581f1125
master: https://github.com/webpack/webpack-dev-server/commit/cfbf229329a1474bce1f68bcef67125d2a5c9c8c

We don't have to involve commits of the master, we just move [the current commits](https://github.com/webpack/webpack-dev-server/compare/master...next) to the head.

**Comment by Loonride** [comment]
> These commits are the same but currently, the commit hash is changed.
> 
> this pr: [f5791a0](https://github.com/webpack/webpack-dev-server/commit/f5791a0cfb51ff2fd0b0f8587b98abcf581f1125)
> master: [cfbf229](https://github.com/webpack/webpack-dev-server/commit/cfbf229329a1474bce1f68bcef67125d2a5c9c8c)
> 
> We don't have to involve commits of the master, we just move [the current commits](https://github.com/webpack/webpack-dev-server/compare/master...next) to the head.

So I did it in the wrong order? I originally tried it in the reverse order as you can see here: https://github.com/Loonride/webpack-dev-server/compare/next...next-rebase-1. But I thought this was the wrong way since I get "Can’t automatically merge"

**Comment by hiroppy** [comment]
> So I did it in the wrong order?

Maybe yes.

Currently, I can't merge this pr because we should avoid these changes. May I take over?

**Comment by Loonride** [comment]
> > So I did it in the wrong order?
> 
> Maybe yes.
> 
> Currently, I can't merge this pr because we should avoid these changes. May I take over?

Sure

**Comment by hiroppy** [comment]
ok, anyway, thank you for trying rebasing.

**Comment by Loonride** [comment]
> ok, anyway, thank you for trying rebasing.

Can I try in the future when diff is much smaller?

**Comment by hiroppy** [comment]
> Can I try in the future when diff is much smaller?

you mean you want to continue to rebase in this pr?

**Comment by Loonride** [comment]
> you mean you want to continue to rebase in this pr?

No. I just meant I wanted to try doing a different rebase in the future, when there is only a few commits separating `master` and `next`.

**Comment by hiroppy** [comment]
> No. I just meant I wanted to try doing a different rebase in the future, when there is only a few commits separating master and next.

Yep

**Comment by hiroppy** [comment]
I rebased the `next` branch so I'm closing this pr.

**Pull request closed without merging**
