### PR TITLE
fix: re-throw error to kill server

### PR DESCRIPTION
**Pull request by emilyrohrbough**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

[Yes](https://github.com/webpack/webpack-dev-server/compare/master...emilyrohrbough:fix-swallowed-error?expand=1#diff-df6494c603411bc69e1b8a4b28c07f44R108)

### Motivation / Use-Case

Closes https://github.com/webpack/webpack-dev-server/issues/2624

Re-throw an error to kill the server instead of logging and hanging.

### Breaking Changes

Process will exit when an error occurs instead of hanging.

### Additional Info
Terminal output when error is thrown:
Screen Shot 2020-05-27 at 1 38 40 PM

### CODE REVIEW

**Comment by emilyrohrbough** [comment]
Are these test typically flaky? Is it possible to kick off another test run or do I miss a step required for tests?

**Comment by evilebottnawi** [comment]
@emilyrohrbough should no, server is freeze without throw?

**Comment by emilyrohrbough** [comment]
Yes, without throwing the error, the server fails to start while the webpack compilation continues

**Comment by emilyrohrbough** [comment]
@evilebottnawi I reverted my changes to see if they had an impact on the test. It seems they are still failing. Do you have any insights on how to resolve these?
> Client console.log › clientLogLevel is silent

    TypeError: DirectoryWatcher is not a constructor

      at WatcherManager.Object.<anonymous>.WatcherManager.getDirectoryWatcher (node_modules/watchpack/lib/watcherManager.js:20:35)
      at WatcherManager.watchFile (node_modules/watchpack/lib/watcherManager.js:31:15)
      at Watchpack.<anonymous> (node_modules/watchpack/lib/watchpack.js:38:51)
          at Array.map (<anonymous>)
      at Watchpack.watch (node_modules/watchpack/lib/watchpack.js:37:29)
      at NodeWatchFileSystem.watch (node_modules/webpack/lib/node/NodeWatchFileSystem.js:72:18)
They don't seem to be related to my changes.
Screen Shot 2020-06-04 at 8 59 39 AM

**Comment by Mayank1791989** [comment]
@evilebottnawi & @emilyrohrbough Any updates on this?

**Comment by evilebottnawi** [comment]
@emilyrohrbough can you change branch on v4?

**Comment by Mayank1791989** [comment]
@evilebottnawi Do you think there is any point of adding error listener if we anyways throwing and killing the server, This will already happen if we don't add listener.

**Comment by evilebottnawi** [comment]
@Mayank1791989 Some errors can be critical, some of them not, I think so, so we added it, but we probably need a little more tests, maybe you are right and we do not need a listener

**Comment by emilyrohrbough** [comment]
I could see value in both, depending on where / how this is being used, one could catch this error and handle it gracefully or just exit the process.

**Comment by evilebottnawi** [comment]
@emilyrohrbough Yes, but in our case, we should log it, maybe it is unnecessary here

**Comment by emilyrohrbough** [comment]
Shall I remove the log?

**Comment by evilebottnawi** [comment]
I think yes, because you already see error message :smile:

**Comment by emilyrohrbough** [comment]
okay great! I'll make that change & fix these merge conflict soon.

**Comment by evilebottnawi** [comment]
Thanks!

**Review by evilebottnawi — APPROVED** [review]
/cc @hiroppy @Loonride

**Comment by hiroppy** [comment]
@emilyrohrbough Why did you update package-lock.json? I think it's unnecessary

**Comment by emilyrohrbough** [comment]
@hiroppy I did update it. I can revert to the locked in versions.

**Comment by emilyrohrbough** [comment]
@hiroppy It seems one or more of the locked in dependencies aren't compatible with node 12. I think the package-lock updates are needed.

**Comment by hiroppy** [comment]
@emilyrohrbough sorry I can't understand. This pr changed only this.

```js
    this.listeningApp.on('error', (err) => {
      this.logger.error(err);
      throw err;
    });
```

And v4 branch's CI is fine v10, 12, and 14 even if we don't update package-lock.json.
see https://github.com/webpack/webpack-dev-server/pull/2592

**Comment by emilyrohrbough** [comment]
@hiroppy I'm looking at #2592 and it looks like lint /the node 12.x is failing. Is that from something else?
Screen Shot 2020-09-08 at 6 14 48 PM

**Comment by hiroppy** [comment]
@emilyrohrbough This is lint CI.

**Comment by emilyrohrbough** [comment]
Is it okay if lint on node 12 fails? That was the only check failing when the package-lock was not updated:
Screen Shot 2020-09-08 at 6 18 07 PM

**Comment by hiroppy** [comment]
@emilyrohrbough 
Screen Shot 2020-09-09 at 8 19 01

**Comment by hiroppy** [comment]
Thank you for rerunning. ok, understood. So did you run `npm audit fix`?

**Comment by emilyrohrbough** [comment]
@hiroppy Yes can do

**Comment by hiroppy** [comment]
@emilyrohrbough Thanks! This PR looks good to me and CI is green.

**Comment by emilyrohrbough** [comment]
@hiroppy The build is passed. Are you okay with these changes?

**Review by hiroppy — APPROVED** [review]

**Comment by hiroppy** [comment]
thanks

**Comment by emilyrohrbough** [comment]
thank you!

**Pull request merged**
