### PR TITLE
[Documentation] Grammar Fixes

### PR DESCRIPTION
**Pull request by Akshay0701**
- [x] This is a **docs update**

### For Bugs and Features; did you add new tests?
No

### Breaking Changes
No

### CODE REVIEW

**Review by anshumanv — CHANGES_REQUESTED** [review]
why? Old looks fine to me

**Comment by Akshay0701** [comment]
I understand,
this changes very small and negligible,
I am new to open source, wanted just get familiar with git and GitHub.

**Comment by anshumanv** [comment]
welcome :)

I find no grammatical improvements with this change, feel free to fix something else if something feels off

**Comment by Akshay0701** [comment]
Thanks! Closing the pr.

**Pull request closed without merging**
