### PR TITLE
Pass mimeTypes option to webpack-dev-middleware

### LINKED ISSUE #1700: Pass mimeTypes options to webpack-dev-middleware
- Operating System: macOS 10.14.3
- Node Version: `v11.10.0`
- NPM Version: `6.8.0`
- webpack Version: `4.29.6`
- webpack-dev-server Version: `3.2.1`

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

`webpack-dev-middleware` exposes an option to set custom mime types via passing a `mimeType` object, see https://github.com/webpack/webpack-dev-middleware#mimetypes

Currently, there is no easy way to define custom mime types used in DevServer just from `webpack.config.js`. 

### Expected Behavior

It would be nice if the user was able to set (for example) `devServer.mimeType` in `webpack.config.js` to pass custom mimes types to `webpack-dev-middleware`.

### Actual Behavior

The user has to one level lower and use `webpack-dev-middleware` directly to customize mimeTypes.

### For Features; What is the motivation and/or use-case for the feature?

Feature is handy in cases where custom mime types are required. No negative impact for all other cases.

### PR DESCRIPTION
**Pull request by dmohns**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes, tests for `createConfig`, a basic sanity check and test for changed mime type.

### Motivation / Use-Case

`webpack-dev-middleware` exposes an option to set custom mime types via 
passing a mimeType object, see 
https://github.com/webpack/webpack-dev-middleware#mimetypes

This commit allows the user to set `devServer.mimeType` in 
`webpack.config.js` to pass custom mimes types to 
`webpack-dev-middleware`

Closes #1700 

### Breaking Changes

No.

### Additional Info

As part of this change the documentation at https://webpack.js.org/guides/development/ needs to be updated as well. I couldn't yet figure out how this is done. And, whether or not the documentation has to be updated at the time (or can be updated later, once this PR is merged).

### ToDo

- [x] Add mimeType test
- [ ] Update documentation at https://webpack.js.org/guides/development/

### CODE REVIEW

**Comment by evilebottnawi** [comment]
We create new issue in `documentation` page after merge, please ping me when we can review your PR, anyway code looks good, thanks!

**Comment by dmohns** [comment]
@evilebottnawi this PR can be reviewed. I updated the description to mirror the changes from the latest commits. 

One question: In the test, I need to request `main.js` for the test to work, while it looks like other tests use `bundle.js`. Is this correct?

**Comment by evilebottnawi** [comment]
> One question: In the test, I need to request main.js for the test to work, while it looks like other tests use bundle.js. Is this correct?

Good questions, we need check what is file created after run build

**Comment by dmohns** [comment]
It seems the default naming (when no output.filename is given) is not really documented anywhere. But this comment https://github.com/webpack/webpack/issues/6543#issuecomment-367314843 suggests that the output filename will simply be the chunk name. While the chunk name again will be `main` because we are not using named (dict) entries but unnamed.
https://github.com/webpack/webpack-dev-server/blob/fa171314bee5fc08308fdfd942dd13053fb2155a/test/fixtures/simple-config/webpack.config.js#L6

**Comment by evilebottnawi** [comment]
@dmohns yep, let's look what file exists in output path for our test config (it should be simple)

**Comment by dmohns** [comment]
I am a little lost on this one. From the code, it simply looks like `filename` is not set (only `path`), see   https://github.com/webpack/webpack-dev-server/blob/34a4a26ccd8ea9f0349a9d3b257f686d43f027f8/test/fixtures/simple-config/webpack.config.js#L7-L9

**Comment by evilebottnawi** [comment]
@dmohns also please rebase on master

**Comment by hiroppy** [comment]
@dmohns Could you submit a pr about this to https://github.com/webpack/webpack.js.org?

**Pull request merged**
