### PR TITLE
fix: migrate flags to new configs format

### PR DESCRIPTION
**Pull request by anshumanv**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
NA

### Motivation / Use-Case
Migrates the flags to new format

### Breaking Changes
Shouldn't have

### Additional Info
- Do we need duplicate desc for all configs?

### CODE REVIEW

**Comment by anshumanv** [comment]
Do we need other properties? CLI seems to be only using type in config object

**Comment by alexander-akait** [comment]
> Do we need other properties? CLI seems to be only using type in config object

Yes, we need migrate all our commands on `configs`

**Comment by anshumanv** [comment]
all done

**Comment by anshumanv** [comment]
wip on test fix

**Comment by anshumanv** [comment]
@alexander-akait I think it will only work after webpack-cli release

**Review by alexander-akait — COMMENTED** [review]
Yes, and keep old `type` for backward compatibility, webpack cli prefer `configs` over `type`

**Comment by anshumanv** [comment]
Yes, thanks

**Comment by anshumanv** [comment]
@alexander-akait fixed

**Comment by alexander-akait** [comment]
I will do release in near future, so we need bump webpack-cli here to check all works fine

**Comment by anshumanv** [comment]
Will do

**Comment by anshumanv** [comment]
Or I can check locally to make sure we're not breaking anything

**Comment by alexander-akait** [comment]
Yep, it will be good too

**Comment by anshumanv** [comment]
yep lets do it

**Review by alexander-akait — APPROVED** [review]

**Review by snitin315 — APPROVED** [review]
Thanks

**Pull request merged**
