### PR TITLE
feat: pass in-memory fileSystem

### PR DESCRIPTION
**Pull request by gdi2290**

### CODE REVIEW

**Comment by SpaceK33z** [comment]
What exactly is your motivation behind this? Accessing the webpack filesystem can leads to various bugs and generally should not be done.

**Comment by SpaceK33z** [comment]
ping @gdi2290 ;).

**Comment by SpaceK33z** [comment]
Closing for now, as the in-memory filesystem is an implementation detail that should not be exposed to the user; also see the "Contributing" guidelines in the README.

**Comment by gdi2290** [comment]
I need it to serve files that are tracked ad or transformed by webpack rather than reading the file again

**Comment by gdi2290** [comment]
if that's the case there needs to be a way to grab the in-memory filesystem then this PR makes sense. If someone changed how the private in-memory filesystem is exposed then they have to make sure it's exposed here.

**Pull request closed without merging**
