### PR TITLE
feat(server): add ws heartbeat

### PR DESCRIPTION
**Pull request by Loonride**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes, and also restructured the test file for WebsocketServer slightly

### Motivation / Use-Case

Add ws heartbeat

#2403 (need investigate client code)

### Breaking Changes

None

### CODE REVIEW

**Comment by Loonride** [comment]
> Good job, what about client? Second part of https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

@evilebottnawi Good point. However, we are using a native browser WebSocket (https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API), not a `ws` client WebSocket. The browser WebSocket seems to not have a `ping` method, nor can it listen for pings from the server (https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser). Do you think I should just implement a "ping" message which is not a real ping but accomplishes the same task?

**Comment by evilebottnawi** [comment]
Hm, we need investigate that, i will look at that in near future

**Comment by evilebottnawi** [comment]
I looked and tested the solution, it works well, I’m not sure about the client code, but the current code can be merged, a little later I will investigate the client in more detail

**Comment by gamedev8** [comment]
@Loonride This is great, but I think you will still eventually get a timeout if you are stepping through your code in the browser dev tools. The browser is holding up the whole application so the client code  cannot communicate with the server. You can easily test this by setting a breakpoint and wait until it times out.

If that is true, then maybe the client code needs to be hardened as well. It should be able to reconnect to the server if it detects that the connection is broken.

**Comment by Loonride** [comment]
> @Loonride This is great, but I think you will still eventually get a timeout if you are stepping through your code in the browser dev tools. The browser is holding up the whole application so the client code cannot communicate with the server. You can easily test this by setting a breakpoint and wait until it times out.
> 
> If that is true, then maybe the client code needs to be hardened as well. It should be able to reconnect to the server if it detects that the connection is broken.

@gamedev8 I tested this and it seems that the WebSocket client can still be pinged by the server even while stepping through your code in dev tools. Could you test this yourself and confirm?

**Comment by gamedev8** [comment]
@Loonride I tested it a few days ago and produced the issue, but it is possible that I did not set up properly. I will try again.

**Pull request merged**
