### PR TITLE
Open default browser if --open option is given

### LINKED ISSUE #311: Automatically open browser
Please add a flag to `webpack-dev-server` that will automatically open the browser to the configured url.

### PR DESCRIPTION
**Pull request by SpaceK33z**
This will open your default browser with the app url if you add the `--open` option to the CLI.

Fixes #311

### CODE REVIEW

**Comment by claycephas** [comment]
Not sure if this is environmental for me, but I get this error:

    Error: ENOENT: no such file or directory, open '.....\node_modules\webpack-dev-server\client\live.bundle.js'

**Comment by sokra** [comment]
@claycephas `npm run prepublish` if you want to run it from git checkout.

@SpaceK33z it opens the wrong uri when `inline: false`.

**Comment by SpaceK33z** [comment]
@sokra, how did you test this? I'm using `cd example && node ../bin/webpack-dev-server.js --open`, and it opens `http://localhost:8080/` for me, which is correct.

Even when I add this it seems to work fine:

```js
devServer: {
    inline: false
}
```

**Comment by sokra** [comment]
It should open the printed url.

`http://localhost:8080/webpack-dev-server/` in non-inline mode.

**Comment by SpaceK33z** [comment]
Okay, I intentionally did it without the `/webpack-dev-server` part, but I see now that's quite confusing. It's fixed now :).

Thank you for merging all my PR's so far and the constructive feedback @sokra :).

**Comment by claycephas** [comment]
ok, I updated my package.json file to have this entry:

    "webpack-dev-server": "CodeYellowBV/webpack-dev-server#98fd2f45b4a81"

then ran

    npm install
    cd node_modules/webpack-dev-server
    npm run prepublish

now this works as expected

    ./node_modules/.bin/webpack-dev-server --open

Please merge!

**Comment by sokra** [comment]
Thanks...

Could you also update documentation page to include this CLI option?

**Comment by SpaceK33z** [comment]
@sokra, I have edited the wiki to include the `--open` option.

**Comment by sandwichsudo** [comment]
Is it possible to use this option when opening webpackDevServer from a node script?
eg

              const server = new WebpackDevServer(compiler, {
			hot : true,
			harmony : true,
			host : '0.0.0.0'
		});

**Comment by SpaceK33z** [comment]
@sandwichsudo, nope, not at the moment.

**Comment by Gopikrishna19** [comment]
This doesn't work for me.. am I missing something?
Here's my package:
```js
"scripts": {
  "start": "babel-node server/index.js | webpack-dev-server --open"
},
"devDependencies": {
  "webpack-dev-server": "^1.14.1"
}
```
And webpack.config:
```js
devServer: {
    contentBase: './dist',
    hot: true,
    noInfo: true
}
```

**Comment by SpaceK33z** [comment]
@Gopikrishna19, apparently it was not part of the 1.14.1 release. In the next 2.0 version it should work.

**Comment by GuyMograbi** [comment]
webpack is awesome!

just reached here. half a year later. is it possible to have a patch for this as 2.x is not out yet? I will gladly help if you guide me.

**Comment by SpaceK33z** [comment]
@GuyMograbi, I happen to be working on a v1 release.

**Comment by calledT** [comment]
It's better I could decide which url to open with the `--open` option is string.Because I want to add querystring to the open url or the default name of my html is not index.

**Comment by LucienLee** [comment]
Before webpack 2.0 released, I think using `[opn](https://www.npmjs.com/package/opn)` module is the simplest to open any url in browser.

**Comment by controversial** [comment]
Is it possible to specify this in `webpack.config.js`?

**Comment by alflennik** [comment]
I'd love to see this in the config.

```
devServer: {
  open: true
}
```

**Comment by jonkoops** [comment]
@alflennik Maybe open a new issue with that as a feature request?

**Comment by pavel06081991** [comment]
@SpaceK33z, how to pass open option when webpack-dev-server is used as module? (https://github.com/webpack/docs/wiki/webpack-dev-server#api)

**Comment by lucaritossa** [comment]
Is there a way to specify a different url path or the standard url `http://host:port` will be always used?
I need to open a url similar to `http://host:port/my-custom-path/` (angular project inside an ASP.NET MVC existing project)

**Comment by TrySound** [comment]
@pavel06081991 No way. It's only CLI feature.

**Pull request merged**
