### PR TITLE
chore(ci): upgrade node.js version from 11 to 12

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

just Node.js version update on CI

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Looks we need wait release node@12 on appveyer

**Comment by hiroppy** [comment]
related https://github.com/appveyor/ci/issues/2921

**Comment by evilebottnawi** [comment]
I think we need migrate on azure pipelines, i will do this in near future

**Comment by hiroppy** [comment]
We have already migrated to azure pipelines:)

**Pull request closed without merging**
