### PR TITLE
feat: allow multiple paths in contentBasePublicPath

### PR DESCRIPTION
**Pull request by jleifeld**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

I add tests to verify that multiple contentBasePublicPath's are working.

### Motivation / Use-Case

I need multiple static directories with different paths. The problem there is that there is no global root path for the assets.

### Breaking Changes

This PR is free of breaking changes and provide downwards compatibility.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
> I need multiple static directories with different paths. The problem there is that there is no global root path for the assets.

Can you provide real use case?

**Comment by jleifeld** [comment]
When you have several micro applications which all have custom static folders:

Application 1: `/application-one/static/`
Application 2: `/application-two/static/`
Application 3: `/application-three/static/`

**Comment by evilebottnawi** [comment]
@jleifeld just for information - you have one big app with own content static and multiple micro apps which used in on big app with own statics?

**Comment by jleifeld** [comment]
Yes, that is the case. The main application is extendable with plugins. These plugins have all their own static folder. In our case we have these static folders:

```
for the main application: '/administration/static',
for the plugins: '/pluginName/static'
```

This allows each plugin to have a scoped folder which does not get in conflict with other files from other plugins

**Comment by hiroppy** [comment]
I'll change the CI code of lint asap.

**Comment by hiroppy** [comment]
Need to update documentation.

**Comment by snitin315** [comment]
> Need to update documentation.
> https://github.com/webpack/webpack.js.org

I will do it if you agree.

**Comment by jleifeld** [comment]
@snitin315 Of course 👍

**Comment by evilebottnawi** [comment]
@hiroppy Feel free to merge after CI green

**Comment by hiroppy** [comment]
Thanks

**Pull request merged**
