### PR TITLE
feat: next

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

We are preparing for the next major release.

**TODO:**

- [x] Drop Node v12
- [x] Drop webpack 4
- [x] Remove deprecated options
- [ ] Resolve TODO wherever possible
- [x] Update to webpack-dev-middleware v6
- [x] remove `magicHtml` option

### CODE REVIEW

**Comment by snitin315** [comment]
@alexander-akait Should we remove the support of the `compiler` option as the first argument in this release?

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L218-L224


Also, I'm not sure what needs to be done in the following TODOs to resolve them:

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L446

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L490

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L532

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L817

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L829

https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L2054

**Comment by alexander-akait** [comment]
@snitin315 Let's rebase and I think we need finish it this month :smile: What we need to finish?

**Comment by snitin315** [comment]
@alexander-akait only this https://github.com/webpack/webpack-dev-server/pull/4655#issuecomment-1399217518

**Comment by alexander-akait** [comment]
> Should we remove the support of the compiler option as the first argument in this release?

Yeah, it will be pain, but we need to do it, our webpack-cli is ready for this?

> // TODO improve for the next major version - we should store `web` and other targets in `compiler.options.environment` 

We need to solve it on webpack side, because we don't have `compiler.options.environment` https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L928 and we can't know what env of developer, will be great to fix in on webpack side, just store `options.environment` in `compiler.options.environment`

>  // TODO maybe empty client 
> // TODO show warning about this
 
The first is a small bug, but I don't think somebody use it, the second just a warning improvement

> // TODO: do merge in the next major release 

Not sure what I want here :smiley: Maybe we should merge default options with provided, so developer dont' need to seutp all of them, need investigate what is default and what is our to avoid massive regressions

> // TODO remove in the next major in favor `context` and `router` options

It is very simple PR but and hard in the same time, `http-proxy-middleware` has this feature and you can achive it using `router`, but I am afraid we will break a lot, so let's generate a warning here, like "bypass is deprecated, please look at example of migration (link on examples/docs in http-proxy-middleware repo)"

**Comment by snitin315** [comment]
> >  // TODO improve for the next major version - we should store web and other targets in compiler.options.environment

> We need to solve it on webpack side, because we don't have compiler.options.environment https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L928 and we can't know what env of developer, will be great to fix in on webpack side, just store options.environment in compiler.options.environment


@alexander-akait You mean we should add a new option `environment` in webpack config and it should be union of [`target`](https://webpack.js.org/configuration/target/) and [`output.environment`](https://webpack.js.org/configuration/output/#outputenvironment)?

**Comment by snitin315** [comment]
> // TODO maybe empty client
> https://github.com/webpack/webpack-dev-server/blob/ff4c194dfdca5e15dbef37b29a96ee7d3bb369c2/lib/Server.js#L490

Do you mean if the user passed `client: {}`? Even then we normalize client options and it will be resolved to `{ webSocketURL: {}, overlay: true, reconnect: 10, logging: 'info' }`

**Comment by alexander-akait** [comment]
> Do you mean if the user passed client: {}?

Yeah, developer can use it, we just need to normalize to our default value

**Comment by alexander-akait** [comment]
> @alexander-akait You mean we should add a new option environment in webpack config and it should be union of [target](https://webpack.js.org/configuration/target/) and [output.environment](https://webpack.js.org/configuration/output/#outputenvironment)?

I think we need this https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L146 because we need to undestand what is enviroment, is it web or is it node is it something else

**Comment by alexander-akait** [comment]
@snitin315 Also, I think let's remove `magicHtml` option, it is broken for modules, don't see who used it, also it decrease perf, because we need to check it on every request

**Comment by alexander-akait** [comment]
@snitin315 Can you show me what is left, so I will plan our release and my work, thank you

**Comment by alexander-akait** [comment]
@snitin315 Yeah, let's start to write migration guide, because they are just fixes :+1:

**Comment by alexander-akait** [comment]
@snitin315 Sorry for pings :smile: Any progress?

**Comment by snitin315** [comment]
@alexander-akait Hi, I was away from home last week, I'll send PR for the migration guide tonight. In the meantime, let's not merge more deps PR in the master.

**Comment by alexander-akait** [comment]
Okay, I looked deeply on our TODOs, we need to finish

- TODO: do merge in the next major release 
- TODO improve for the next major version - we should store `web` and other targets in `compiler.options.environment` 

I will send PR in webpack for the latest, for the first we should need merge options with our defaults values

**Comment by alexander-akait** [comment]
@snitin315 Let's update webpack-dev-middleware to the latest version here too

**Comment by alexander-akait** [comment]
@snitin315 Did we resolve all TODOs here? Because after updating webpack-dev-middleware I want to merge it to the master/main

**Comment by snitin315** [comment]
@alexander-akait Following TODOs are pending:

https://github.com/webpack/webpack-dev-server/blob/5a6a1f1f43da5b25d1b7b9d82ab004c757ea2399/lib/Server.js#L471

https://github.com/webpack/webpack-dev-server/blob/5a6a1f1f43da5b25d1b7b9d82ab004c757ea2399/lib/Server.js#L515

https://github.com/webpack/webpack-dev-server/blob/5a6a1f1f43da5b25d1b7b9d82ab004c757ea2399/lib/Server.js#L471

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 Will you write the migration guide? Thank you

**Pull request merged**
