### PR TITLE
refactor: rename describe property to description for cli-flags

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
no

### Motivation / Use-Case
need use `description` instead of `describe` because `webpack` and `webpack-cli` both uses `description` property for options.

This is helpful in the `webpack --help` output. 

https://github.com/webpack/webpack-cli/blob/4dc1a05046aeaf5a17de878a9e595697852bcd32/packages/webpack-cli/lib/webpack-cli.js#L139-L141

### Breaking Changes
no

### Additional Info
no

### CODE REVIEW

**Review by hiroppy — CHANGES_REQUESTED** [review]
I think this refactoring is not necessary /cc @alexander-akait

**Comment by snitin315** [comment]
Actually, it's a  TODO in `webpack-cli`.

https://github.com/webpack/webpack-cli/blob/4dc1a05046aeaf5a17de878a9e595697852bcd32/packages/webpack-cli/lib/webpack-cli.js#L139-L141

**Comment by alexander-akait** [comment]
@hiroppy we need fix it, because webpack (inside core) uses `description` for options, so I think it is good fix

**Comment by hiroppy** [comment]
Yeah, I see but I didn't understand this context at first so please update the description. The current description of this PR is bad.

**Comment by snitin315** [comment]
Yeah, I should have used a better description. Updated 👍🏻

**Review by alexander-akait — APPROVED** [review]

**Comment by snitin315** [comment]
@alexander-akait can we remove this TODO https://github.com/webpack/webpack-cli/blob/4dc1a05046aeaf5a17de878a9e595697852bcd32/packages/webpack-cli/lib/webpack-cli.js#L139-L141 ?

or we need to wait for a stable `webpack-dev-server` v4 release.

**Pull request merged**
