### PR TITLE
test: don't use --runInBand and improve execution performance

### PR DESCRIPTION
**Pull request by hiroppy**
backport from #2005 to master branch

- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

modify only

### Motivation / Use-Case

see https://github.com/webpack/webpack-dev-server/pull/2005

### Breaking Changes

no

### CODE REVIEW

**Comment by hiroppy** [comment]
I'll change the setup code because Node6 doesn't support `Object.entries`.

**Comment by hiroppy** [comment]
@evilebottnawi PTAL

**Comment by evilebottnawi** [comment]
Something wrong with CI and need resolve conflict

**Comment by hiroppy** [comment]
Resolved

**Pull request merged**
