### PR TITLE
ci: npm audit and lint commit message

### PR DESCRIPTION
**Pull request by evilebottnawi**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no required

### Motivation / Use-Case

- npm audit
- commit message linting to ensure all commits are valid and we can use safely use `npm run release`

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Looks chrome new verison of headless chrome is unstable on windows, i think we can ignore this, if the problem is not solved in the near future we should comment out the test

**Comment by hiroppy** [comment]
I think it might be better to add commitlint to husky.

```json
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }  
  }
```

**Comment by hiroppy** [comment]
CI is Green!

**Pull request merged**
