### PR TITLE
feat: add more negative flags

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
No

### Motivation / Use-Case

Add some more negative flags.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Let's add tests

**Comment by ylemkimon** [comment]
I think we can programmatically build the `negatedDescription`, for instance:
1. if the `description` starts with `Enable`, replace it with `Disable`
2. otherwise, prepend it with `Do not ` and change the first letter to the lowercase
3. if the ` or ` or comma exists, use the segment before it

**Comment by snitin315** [comment]
It can introduce potential bugs as we have more than 100 negative flags (including flags from the core webpack) and the descriptions can change often. 

So we simply set a specific description for some flags if we need - 

https://github.com/webpack/webpack-cli/blob/3772148fda2b52d6498ad9d4f43e2dae0eb8f3a2/packages/webpack-cli/lib/webpack-cli.js#L219

**Comment by snitin315** [comment]
recreating on master.

**Pull request merged**
