### PR TITLE
test(helpers): rename to run-bin and run-server

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

Rename helper.js to `./helpers/run-server.js`.
Rename run-webpack-dev-server to `./helpers/run-bin.js`.

### Breaking Changes

no

### CODE REVIEW

**Comment by hiroppy** [comment]
Currently helpers directory has run-browser so I thought this file should be added “run” as a prefix. If you want to change this, I can change the value name of each test.

**Comment by evilebottnawi** [comment]
Maybe rename helper too? Or maybe we can rename helper as serve?

**Comment by hiroppy** [comment]
`helper` has already been renamed to `runServer`. OK, I'll change below.

```diff
- const helper = require('./helper');
+ const server = require('./helpers/run-server');
```

@evilebottnawi Is this ok?

**Comment by evilebottnawi** [comment]
Maybe
```js
const server = require('./helpers/test-server');
```
?

**Comment by hiroppy** [comment]
`server` is a very common variable name in tests, and it has already been used at some places.

So, I replaced below.

```js
const testServer = require('./helpers/test-server');
```

**Comment by evilebottnawi** [comment]
:+1:

**Pull request merged**
