### PR TITLE
docs: Fix CHANGELOG.

### PR DESCRIPTION
**Pull request by numb86**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Don't need.

### Motivation / Use-Case

#1937 is 3.6.0, not 3.7.0.
The link to compare also seems to be wrong.

### Breaking Changes

No.

### Additional Info

No.

### CODE REVIEW

**Comment by hiroppy** [comment]
Did you modify using `npm run release`?

**Comment by numb86** [comment]
No.
I edited `CHANGELOG.md` directly and committed it.
Were there any mistakes in my way?

**Comment by hiroppy** [comment]
CHANGELOG.md is generated automatically by the release command. So, if you want to  modify this file, you should run this command.

**Comment by numb86** [comment]
I checked about `standard-version`. But I did not find the proper way to fix the past log.
Do you know the correct solution for this case?

**Comment by hiroppy** [comment]
ok, understood. We cannot generate this version in CAHNGELOG.md, because I rebased this commit. This is my mistake.

**Comment by hiroppy** [comment]
@numb86 Please fix your commit message. `npm run commitlint`

**Comment by numb86** [comment]
I appreciate your gently advice.
I fixed it, so please review again.

**Comment by numb86** [comment]
Of course I know that the test has failed.
But, I cannot understand why only `Windows node-10` fails. In the first place, why edit `CHANGELOG.md` only and fail...
Is there anything I can do for resolve?

**Comment by evilebottnawi** [comment]
Randomly CI fail

**Comment by numb86** [comment]
I see. Thanks!

**Comment by hiroppy** [comment]
Thanks!

**Pull request merged**
