### PR TITLE
test: refactor

### PR DESCRIPTION
**Pull request by anshumanv**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
NA

### Motivation / Use-Case
removes dup tests

### Breaking Changes
no

### CODE REVIEW

**Review by snitin315 — COMMENTED** [review]
Let's fix CI

**Comment by anshumanv** [comment]
hmm macos CI strange

**Review by snitin315 — DISMISSED** [review]
LGTM

**Comment by alexander-akait** [comment]
Need small improve WIP

**Comment by alexander-akait** [comment]
I really hate macos on github actions...

**Pull request merged**
