### PR TITLE
fix(deps): security vulnerability in yargs-parser

### LINKED ISSUE #2559: yargs-parser vulnerability
- Node Version: 12.16.1
- NPM Version: 6.13.4
- OS: Ubuntu 19.10

- [x] This is a **bug**
- [ ] This is a **modification** request

Hey guys,

npm is reporting a Prototype Pollution vulnerability on the yargs-parser dependency

 Low             Prototype Pollution                                                                                                                           
 Package         yargs-parser                                                                                                                                
 Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2                                                                                             
 Dependency of   webpack-dev-server [dev]                                                                                                                      
 Path            webpack-dev-server > yargs > yargs-parser                                                                                                     
 More info       https://npmjs.com/advisories/1500

### PR DESCRIPTION
**Pull request by Ionaru**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No.

### Motivation / Use-Case

It fixes #2559

### Additional Info

Running `npm audit -production` for webpack-dev-server complains about `mkdirp` as well, this should be looked into by the Webpack team.

### CODE REVIEW

**Comment by hiroppy** [comment]
Need to fix CI at first.

**Comment by Ionaru** [comment]
@hiroppy do the CI failures on this PR have anything to do with the change I made? Tests on master fail as well, on my local machine I had 3 tests fail on master and the same amount after my change.

**Comment by hiroppy** [comment]
@Ionaru ok, sorry. But we can't merge this PR if CI fails. Currently, we are working on v4 branch to release the new major version.  V4 branch's CI is green so if you want to continue to work this PR, please change the targeted branch from master. (also actually, this change is a breaking change.) Thanks.

**Comment by Ionaru** [comment]
I don't think it's correct to have locked #2559.
This audit failure impacts many developers, pretty much everyone using Angular, and now it's locked because of "spam"? There's been no unrelated discussion on the issue, locking it prevents people from adding a :+1: as indication of priority or desire for the issue to be resolved.

I think the proper course of action is to either unlock it, or to have a Webpack member add a statement that the issue is being worked on.

**Comment by Ionaru** [comment]
> (also actually, this change is a breaking change.)
How is it a breaking change? As far as I'm aware, the public webpack API (or CLI) does not change.

**Comment by hiroppy** [comment]
@Ionaru Yes, I know.  So we decided to upgrade this package but we work on v4 branch to release the new major version ASAP. So I wanna say would you continue to work your PR?

**Comment by ashfordneil** [comment]
Given that this is a security fix rather than a regular PR, shouldn’t publishing it and making it available to users (angular was mentioned above, create react app also depends on this) be pushed through sooner rather than later. 

While I get that normally punting things to the upcoming release makes sense, in this context it feels like you’re refusing to back-port security updates to version 3 before version 4 is even out.

**Comment by evilebottnawi** [comment]
@Ionaru 

> This audit failure impacts many developers, pretty much everyone using Angular, and now it's locked because of "spam"? 

To avoid messages like: "same here", "please update" and etc

> While I get that normally punting things to the upcoming release makes sense, in this context it feels like you’re refusing to back-port security updates to version 3 before version 4 is even out.

No, we want to do release, just wait other developers

Merged, but give me time for testing locally, due problem on CI

**Pull request merged**
