### PR TITLE
Express middleware for History API fallback

### PR DESCRIPTION
**Pull request by cbas**
The Connect middleware has issues with dots in URLs due to how it
redirects the request. The Express middleware is much simpler and
leverages Request.sendFile (Express 4.8.0 or later) to serve a fixed
file (index.html) only if the express.static middleware failed to find
a file. No rewriting needed, no issues with special characters in paths.

BTW there are no tests for this project so I would appreciate help in reviewing the change.

### CODE REVIEW

**Comment by radotzki** [comment]
I'm having the same problem with connect-history-api-fallback.
This pull request solved the problem for me.

**Comment by ChrisJamesC** [comment]
Any update on this PR. It solves a problem I also have. Can I do something to help speed up the adoption of a fix? 
At test URL that failed before and now works is `http://localhost:3000/hello.world`

**Comment by ChrisJamesC** [comment]
An alternative fix is to replace the `historyApiFallback=true` line with: 
```
        historyApiFallback: {
          rewrites: [
            {
              from: /^\/app\/.*$/,
              to: function() {
                return 'index.html';
              }
            }
          ]
        },
```
This will make any page with a dot in the /app path to be redirected to index.html (as it should be if it were not considered as a file)
See https://github.com/bripkens/connect-history-api-fallback#rewrites for more info

**Comment by radotzki** [comment]
@ChrisJamesC  thank you, that works for me!

**Comment by domenkozar** [comment]
@sokra I'd consider this as the `.` limitation is really annoying. I mentioned this in https://github.com/bripkens/connect-history-api-fallback/issues/25#issuecomment-238037144, but since this has been reported before it doesn't seem it will get fixed upstream.

**Comment by bripkens** [comment]
This is now fixed in `connect-history-api-fallback` and the `.` character rule can now be disabled.

**Comment by SpaceK33z** [comment]
So, is this PR still relevant after the fix in `connect-history-api-fallback`?

**Comment by SpaceK33z** [comment]
Closing this since it is now possible to do this as an option. This PR is a breaking change, and I don't think it's worth it.

**Comment by davidhariri** [comment]
It would be helpful to mention that option we should specify @SpaceK33z

**Comment by tmcgann** [comment]
Use the `disableDotRule` found here: https://github.com/bripkens/connect-history-api-fallback#disabledotrule. For example:

``js
historyApiFallback: {
    disableDotRule: true,
}
```

I personally encountered issues with the rewrite rule--for some reason it changed the bundle that was used, which was really confusing. The symptom I observed was the hashes in my output files were different for the rewrite URLs; all the other URLs had the same hash in the output. Not sure why, may need to use the `context` argument as part of the rewrite (see https://github.com/bripkens/connect-history-api-fallback#rewrites). But the `disableDotRule` did the trick for me!

**Comment by roger-russel** [comment]
I tried with "disableDotRule: true"  but disabled the other files as .js or .css, which made my vuejs project broke.

The solution that I found was based on this [link](https://stackoverflow.com/questions/38576356/attempting-to-route-a-url-with-a-dot-leads-to-404-with-webpack-dev-server).

was change this:
app.use(require('connect-history-api-fallback')());

To this:
app.use(require('connect-history-api-fallback')({
  rewrites: [
    {
      from: /^\/ip\/allow\/.*$/,
      to: '/'
    }
  ]
}))

The trick is create a rewrite to every route that uses dot on it.

**Pull request closed without merging**
