### PR TITLE
test: migrate to snapshots

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
yes added snapshots

### Motivation / Use-Case

use snapshots for tests.

### Breaking Changes
No

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by snitin315** [comment]
fixing CI

**Review by anshumanv — DISMISSED** [review]

**Comment by snitin315** [comment]
We have a warning on node 12 for windows -

`(node:4752) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.`

Should we strip it in the snapshot?

**Comment by alexander-akait** [comment]
> Should we strip it in the snapshot?

Yep, let's remove it

**Review by anshumanv — APPROVED** [review]

**Comment by alexander-akait** [comment]
Let's merge this after https://github.com/webpack/webpack-cli/pull/2573, otherwise we need rebase again, it is painful for snapshots

**Comment by snitin315** [comment]
> Let's merge this after [webpack/webpack-cli#2573](https://github.com/webpack/webpack-cli/pull/2573), otherwise we need rebase again, it is painful for snapshots

Both PRs are in different repositories, am I missing something here?

**Comment by alexander-akait** [comment]
Oh, yes, my mistake

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
