### PR TITLE
do not swallow errors from http server.

### PR DESCRIPTION
**Pull request by 0xorial**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

I was not sure where I can put a test for it. If someone can guide me I will be happy to add one.

### Motivation / Use-Case

I was using WDS using node.js, made a trivial mistake (typed locahlost instead of localhost) and spent 10 minutes trying to find it. 

### Breaking Changes
None

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Can you provide example where we can reproduce this problem, thanks for PR

**Comment by 0xorial** [comment]
```TypeScript
      const config = require(configPath);
      const compiler = webpack(config);

      const log = require("webpack-log");

      const logger = log({
        name: "wds",
        level: "info",
        timestamp: true
      });
      const devServerInstance = new devServer(compiler, {}, logger);
      outputChannel.appendLine("about to listen...");

      // mistyped localhost
      devServerInstance.listen(8080, "locallllhost", (err: any) => {
        // never reached here :(
        if (err) {
          outputChannel.appendLine("listen error!");
          throw err;
        }
        outputChannel.appendLine('listening!');
      });
```

**Comment by 0xorial** [comment]
Just for some more context - I am trying to develop an extension for Visual Studio Code to integrate WDS.

**Comment by evilebottnawi** [comment]
@0xorial can you rebase and add tests?

**Pull request closed without merging**
