### PR TITLE
refactor: tweak style for overlay

### LINKED ISSUE #3689: improve our overlay
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

improve our default overlay:
1. Allow to catch `runtime` errors
2. Improve errors/warnings reporting (ideally we should have )
3. Improve styles
4. More?

CRA has `react-error-overlay`, I think we can union with them and create the one great overlay

/cc @raix  

### Expected Behavior

Better DX

### Actual Behavior

Our overlay is very simple and in some places have bad DX

### PR DESCRIPTION
**Pull request by malcolm-kee**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

Tweak the styles for overlay.

#### Before

image

#### After

after

image

### Additional Info

This is to partially resolves #3689

### CODE REVIEW

**Comment by malcolm-kee** [comment]
Right now I think the style improvement is not substantial. I'll add examples that use `ts-loader` as that print out some code snippet and iterate more.

Created this MR in case there is feedback.

**Comment by malcolm-kee** [comment]
I find out that `react-error-overlay` has extra logic to open file with error if the filename and line of code can be detected using [this middleware](https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/errorOverlayMiddleware.js).

Should I add this in as well or it's better that I implement it in another PR?

**Comment by alexander-akait** [comment]
@malcolm-kee Let's do it in another PR, can you update tests? Thank you for the PR

**Comment by snitin315** [comment]
@malcolm-kee you may have to update snapshot for webpack v4 as well.

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thank you, feel free to send more PRs which will improve overlay

**Pull request merged**
