### PR TITLE
BREAKING CHANGES: handle publicPath correctly

### PR DESCRIPTION
**Pull request by Loonride**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Not yet, should add tests for:

Routes: `dev` option setting `publicPath` and `index`. Setting `publicPath` in compiler options without setting it for dev middleware. Using single or multi compiler

### Motivation / Use-Case

Fixing how publicPath is handled

Requires: https://github.com/webpack/webpack-dev-middleware/pull/674 to work

### Breaking Changes

publicPath is no longer set at all by the dev server, the option is retrieved from webpack-dev-middleware, which falls back to webpack output publicPath if there is no dev middleware publicPath

### CODE REVIEW

**Comment by Loonride** [comment]
@evilebottnawi it's ready, the tests here that are failing are from instability fixed in https://github.com/webpack/webpack-dev-server/pull/2680

**Comment by hiroppy** [comment]
@Loonride please check this error of windows/node-10-canary.

```
FAIL test/server/utils/routes.test.js (362.772 s)
  ● routes util › multi config › should handle GET request to directory index and list all middleware directories

    Timeout - Async callback was not invoked within the 120000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

  ● routes util › multi config › should handle GET request to directory index and list all middleware directories

    : Timeout - Async callback was not invoked within the 120000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 120000 ms timeout specified by jest.setTimeout.Error:

      129 |     afterAll(testServer.close);
      130 | 
    > 131 |     it('should handle GET request to directory index and list all middleware directories', (done) => {
          |     ^
      132 |       req.get('/webpack-dev-server').then(({ res }) => {
      133 |         expect(res.headers['content-type']).toEqual('text/html');
      134 |         expect(res.statusCode).toEqual(200);

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/server/utils/routes.test.js:131:5)
      at Suite.<anonymous> (test/server/utils/routes.test.js:123:3)
      at Object.<anonymous> (test/server/utils/routes.test.js:9:1)
```

**Comment by evilebottnawi** [comment]
@Loonride Need rebase

**Comment by Loonride** [comment]
It seems that webpack@5 on windows had an issue with webpack options `output.path: '/'`. This should be valid behavior, since `/` is not a valid path on windows, correct?

**Pull request merged**
