### PR TITLE
sendMsg('Progress', data)

### PR DESCRIPTION
**Pull request by nojvek**
- [x] This is a **bugfix**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **typo fix**
- [ ] This is a **metadata update**

### Motivation / Use-Case
One line change.

Context: we maintain a module that shows a webpack status bar on the browser page. It handles ok, error, status e.t.c messages but since progress isn't sent out we can't respond to that.

https://github.com/mixpanel/webpack-dev-server-status-bar

The goal is to make the bar respond to progress by showing a fixed bar on top that increases in width as progress increases. For this to happen webpack-dev-server needs to send the event via `postMessage`

### Breaking Changes

No breaking changes.

### CODE REVIEW

**Comment by nojvek** [comment]
Travis CI failed because it couldn't install modules. Any chance someone can re-run that please?

**Comment by nojvek** [comment]
@SpaceK33z  @shellscape. Kind ping.

**Comment by shellscape** [comment]
Sorry, but I no longer maintain this repo and recommend people use `webpack-serve`.

**Comment by shellscape** [comment]
As far as I know @SpaceK33z is the only one still poking at this module. It's recommended that you try `webpack-serve`, as it's under active development. This package is still around for users that need support for browsers that are old or are way behind spec. Lots of users in China are in that group because the primary browsers there are very behind spec.

**Comment by nojvek** [comment]
Kind ping @SpaceK33z, any chance you'll be able to take a look at this and publish a patch version please?

Thanks.

**Comment by SpaceK33z** [comment]
Thanks! Will do a release soon.

**Comment by nojvek** [comment]
You da best! Thanks 🙏

**Pull request merged**
