### PR TITLE
Limit websocket retries

### PR DESCRIPTION
**Pull request by SpaceK33z**
**Please check if the PR fulfills these requirements**
- [ ] An example has been added or updated in `examples/` (for features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Before, the client script would retry for a websocket connection every two seconds.
This caused massive log spam. See #584, and #585.

**What is the new behavior?**

It will retry with an exponential timeout, and with a max of 10 retries.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SpaceK33z** [comment]
@gaearon, could you check this out? You initially complained about this :).

**Comment by gaearon** [comment]
Thanks for taking this seriously!

**Comment by gaearon** [comment]
Like https://github.com/webpack/webpack-dev-server/pull/579#issuecomment-247804636, any chance you would be interested in backporting this to 1.x?

**Comment by SpaceK33z** [comment]
@gaearon, allright, seems fair since v2 is taking longer then planned. I've backported those two PR's and released `1.16.0`.

**Comment by gaearon** [comment]
Appreciated!

**Pull request merged**
