### PR TITLE
fix: migrate server flags to new format

### PR DESCRIPTION
**Pull request by anshumanv**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
existing

### Motivation / Use-Case
we use this format across core flags, cli internal flags

### Breaking Changes
need to handle this format in cli, will do it after this version is released.

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
We should fix it firstly in webpack-cli and do release, i.e. supports new format

**Comment by anshumanv** [comment]
lets not merge till webpack-cli release, wip on cli

**Review by snitin315 — APPROVED** [review]
Looks Good!

**Comment by alexander-akait** [comment]
Let's merge this after we finish our options and CLI options to avoid unnecessary work

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack-dev-server/pull/3325, we need more work here, anyway big thanks

**Pull request closed without merging**
