### PR TITLE
test: refactor

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Yep refactoring, WIP

### Motivation / Use-Case
refactor tests, remove duplicate tests.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by snitin315** [comment]
with the `bonjour` test done, the rest looks good to me.

**Review by alexander-akait — COMMENTED** [review]
Why we just remove them? Do we already have tests for this?

**Comment by snitin315** [comment]
yes https://github.com/webpack/webpack-dev-server/blob/master/test/server/setupExitSignals-option.test.js

**Review by alexander-akait — APPROVED** [review]
Big thanks

**Review by anshumanv — APPROVED** [review]

**Pull request merged**
