### PR TITLE
refactor: remove publicPath log

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
updated existing tests.

### Motivation / Use-Case

Move this log to webpack-dev-middleware.

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Le't firstly improve this in `webpack-dev-middleware`, then I do release, then we update our version and remove it from here

**Review by alexander-akait — COMMENTED** [review]
@snitin315 Can you fix tests?

**Comment by snitin315** [comment]
@alexander-akait done 👍🏻

**Review by anshumanv — APPROVED** [review]
Great 👍

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
