### PR TITLE
test: use latest API methods

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case
use latest API methods

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
It is special test for old API, because we can't break it

**Comment by snitin315** [comment]
Are there any other instances we want to update? if not, I think we can close it.

**Comment by alexander-akait** [comment]
Need check please run test locally, ideally we should have only one test for old API (it is this test)

**Comment by snitin315** [comment]
I found a few instances in Server.test.js - 

https://github.com/webpack/webpack-dev-server/blob/974ce25669ef6a4f55e8a7576fc140bc7ccb55f1/test/server/Server.test.js#L65-L71

**Comment by alexander-akait** [comment]
Feel free to fix them

**Comment by snitin315** [comment]
I will update

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
