### PR TITLE
fix(example/util): use path.resolve

### LINKED ISSUE #1428: example for api/simple can't compile successfully
* Operating System:  Windows 10
* Node Version:  v7.10.1
* NPM Version:  4.2.0
* webpack Version:  ^4.1.1
* webpack-dev-server Version: 3.1.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

https://github.com/webpack/webpack-dev-server/blob/master/examples/api/simple/webpack.config.js

```js
  module.exports = setup({
  context: __dirname,
  entry: ['./app.js', '../../../client/index.js?http://localhost:8080/'],
  output: {
    filename: 'bundle.js'
  }
});
```

### Expected Behavior
 Compiled successfully and server starts up.

### Actual Behavior

hit error:

> ERROR in multi ./app.js ../../../client?http://localhost:8080/
> Module not found: Error: Can't resolve '../../../client/index.js?http://localhost:8080/' in 'C:\Users\kaiwen\webpack-dev-server-example\examples\api\simple'
>  @ multi ./app.js ../../../client?http://localhost:8080/

I can't find './../../client/index.js' at the code.
Is it deleted or renamed after an upgrade?

The server can run successfully, if remove this path:
`entry: ['./app.js'],`

Should the cli file is included?

### For Bugs; How can we reproduce the behavior?
run `node server.js` at path **examples\api\simple**

### PR DESCRIPTION
**Pull request by hiroppy**
fixes #1428

- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

Use `path.resolve` for windows.
I hope this change will work on windows as well.

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy do you test this manually?

**Comment by hiroppy** [comment]
Note: I tested only Mac OS because I don't have Windows. 

@evilebottnawi This is the sample code, but do you think that testing is necessary?

**Comment by evilebottnawi** [comment]
@hiroppy no, only manual testing

**Comment by hiroppy** [comment]
ok, so I'll install Microsoft Edge Developer to my pc. Wait for a little more plz.

**Comment by hiroppy** [comment]
This issue has been fixed.

**Pull request merged**
