### PR TITLE
Refactor remove warning

### PR DESCRIPTION
**Pull request by evilebottnawi**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Existing tests

### Motivation / Use-Case

Avoid warning, it is stable feature

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by hiroppy** [comment]
Oops, I have this.. https://github.com/webpack/webpack-dev-server/pull/2558

**Comment by evilebottnawi** [comment]
:+1:

**Comment by hiroppy** [comment]
@evilebottnawi sorry and thank you.

**Pull request closed without merging**
