### PR TITLE
Feature: add --stdin as an option in webpack.config.js

### PR DESCRIPTION
**Pull request by EslamHiko**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Test already exist 'should exit the process when SIGINT is detected' test in CLI.test

### Motivation / Use-Case
solve these issues : https://github.com/webpack/webpack-cli/issues/789 , https://github.com/webpack/webpack-dev-server/issues/1712

### Breaking Changes
No

### Additional Info
Minimum reproducible repo : https://github.com/EslamHiko/webpack-dev-server/tree/add-stdin-option
go to examples/cli/stdin and add that config : 
```
'use strict';

module.exports = {
  context: __dirname,
  entry: './app.js',
  devServer:{
    stdin:true
  }
};

```
Run `npm run webpack-dev-server` without `--stdin` flag
The server will accept input and closes when you exit CTRL+C/CTRL+D the same behavior when you add `--stdin` flag
if you don't add the option and run `npm run webpack-dev-server` without `--stdin` it won't accept input

### CODE REVIEW

**Comment by hiroppy** [comment]
I don't know this option is necessary. /cc @evilebottnawi

**Comment by EslamHiko** [comment]
@hiroppy Done

**Comment by EslamHiko** [comment]
@evilebottnawi I searched a lot & tried a lot to capture any input but I couldn't find a way to test if the CLI can accept input or not. 
But I have a Minimum reproducible repo here: https://github.com/EslamHiko/webpack-dev-server/tree/add-stdin-option
Here is a walkthrough to test it :
> go to examples/cli/stdin and add that config :
> 
> ```
> 'use strict';
> 
> module.exports = {
>   context: __dirname,
>   entry: './app.js',
>   devServer:{
>     stdin:true
>   }
> };
> ```
> Run `npm run webpack-dev-server` without `--stdin` flag
> The server will accept input and closes when you exit CTRL+C/CTRL+D the same behavior when you add `--stdin` flag
> if you don't add the option :
>
> ```
> 'use strict';
> 
> module.exports = {
>   context: __dirname,
>   entry: './app.js',
> };
> ```
> and run `npm run webpack-dev-server` without `--stdin` it won't accept input

**Comment by EslamHiko** [comment]
Closed for : https://github.com/webpack/webpack-dev-server/pull/2186

**Comment by evilebottnawi** [comment]
@EslamHiko you send many PRs to webpack-dev-server, i think we can invite your as contributor, do you want to continue help use?

**Comment by EslamHiko** [comment]
@evilebottnawi  Yes, sure I want to continue helping.

**Comment by evilebottnawi** [comment]
@EslamHiko now you are member :tada:

**Pull request closed without merging**
