### PR TITLE
Refactor remove unnecessary utils

### PR DESCRIPTION
**Pull request by alexander-akait**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Will fix current tests

### Motivation / Use-Case

Avoid unnecessary rules, avoid multiple require to speed up initial start

### Breaking Changes

Yes, you need to use the latest `webpack-cli` version

### Additional Info

No

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Comment by snitin315** [comment]
Let's fix CI.

**Comment by snitin315** [comment]
@alexander-akait  I can fix tests here if you don't have more changes locally.

**Comment by alexander-akait** [comment]
@snitin315 I am WIP on this :+1: Anyway feel free to finish tests in any stale PRs

**Review by snitin315 — APPROVED** [review]

**Comment by alexander-akait** [comment]
We will restore coverage after finish - just more tests

**Pull request merged**
