### PR TITLE
chore: fix sec vuln

### PR DESCRIPTION
**Pull request by anshumanv**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
NA

### Motivation / Use-Case
Fixes security vuln in next

### Breaking Changes
Shouldn't, bonjour was downgraded to secure version

### Additional Info
We may need to patch for v3 too, will do after confirmation

### CODE REVIEW

**Comment by ylemkimon** [comment]
Note `^3.3.0` would be vulnerable to the same bug, as the `dns-packet` was lifted out of `multicast-dns` and uses the same implementation.

**Comment by anshumanv** [comment]
yep will send for v3 as well

**Comment by ylemkimon** [comment]
@anshumanv I mean `bonjour@^3.3.0` by `^3.3.0`. Downgrading the dependency wouldn't help.

**Comment by ylemkimon** [comment]
@anshumanv Advisories are not published, but as it uses the same implementation, it'd be vulnerable to the same bug. I've contacted the maintainer.

**Comment by anshumanv** [comment]
Gotcha, then this won't solve it, thanks for heads up! Closing :)

**Pull request closed without merging**
