### PR TITLE
feat: add serveIndex icons

### PR DESCRIPTION
**Pull request by jlguenego**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### CODE REVIEW

**Comment by jlguenego** [comment]
Related to Issue #2440

**Comment by jlguenego** [comment]
image

Folders now have icons in front of each file ;)

**Comment by jlguenego** [comment]
before this pull request, directory looked poor without icons:
image

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
