### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [X] This is a **metadata update**

### For Bugs and Features; did you add new tests?
NA

### Motivation / Use-Case
Update deps at once + save CI time.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by rishabh3112** [comment]
@snitin315 can you fix security audit for `trim-newlines` package as well here? It has been patched, just need update in lock file.

**Comment by snitin315** [comment]
I tried, I think not possible because `trim-newlines` is defined in the lock file as `^3.0.0` and the patched version is `4.0.1`. I think we have to wait until https://github.com/conventional-changelog/get-pkg-repo/issues/60

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@snitin315 maybe you change nickname or email?  `licence/cla ` is broken

**Comment by anshumanv** [comment]
> @snitin315 maybe you change nickname or email? licence/cla is broken

Happening in all PRs https://github.com/webpack/webpack-dev-server/pull/3415, I think service down

**Review by anshumanv — APPROVED** [review]

**Comment by alexander-akait** [comment]
Let's ignore this :+1:

**Pull request merged**
