### PR TITLE
feat: add WEBPACK_SERVE env variable

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
yes.

### Motivation / Use-Case

Replaced by `WEBPACK_SERVE` in `webpack-cli`.

### Breaking Changes

replace `WEBPACK_DEV_SERVER` with `WEBPACK_SERVE`.

### Additional Info
no

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
No need to remove it, because some developers uses `webpack-dev-server` directly, let's rename to to `WEBPACK_SERVE`

**Review by alexander-akait — DISMISSED** [review]

**Comment by snitin315** [comment]
Something wrong with `webpack-4` CI 😞, investigating.

**Comment by alexander-akait** [comment]
@snitin315 Thanks for help, if you want the next PR - we need change `static` https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/normalizeOptions.js#L18 to `public` (some tests need to change too, but it is very easy)

**Comment by snitin315** [comment]
Will do next 👍.

**Review by hiroppy — APPROVED** [review]

**Comment by hiroppy** [comment]
hm, e2e seems fleky.

**Comment by alexander-akait** [comment]
@snitin315 CI cache broken, we need install webpack v4

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
