### PR TITLE
docs(README): add note in usage

### PR DESCRIPTION
**Pull request by bhavya9107**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

#1508

### CODE REVIEW

**Comment by bhavya9107** [comment]
> I think we should rephrase this, you can use webpack-dev-server without index.html, example using proxy

@evilebottnawi suggest possible ways of using webpack-dev-server(without index.html) that are to be included in the doc. Also, do I needa mention some sample code for each one of them?

**Comment by evilebottnawi** [comment]
@bhavya9107 better do this in `webpack` docs repo, not here

**Comment by evilebottnawi** [comment]
And provide link on this examples

**Comment by bhavya9107** [comment]
> @bhavya9107 better do this in `webpack` docs repo, not here

Could u provide me link with the link to that.

**Comment by bhavya9107** [comment]
> > @bhavya9107 better do this in `webpack` docs repo, not here
> 
> Could u provide me link with the link to that.
*Could u provide me with the link to that.

**Comment by evilebottnawi** [comment]
@bhavya9107 Here repo https://github.com/webpack/webpack.js.org

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack.js.org/pull/2813

**Pull request closed without merging**
