### PR TITLE
BREAKING CHANGE: use this.options.xxx 

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

yes

### Motivation / Use-Case

Use `this.options.xxx` instead of `this.xxx`.

### Breaking Changes

yes

### CODE REVIEW

**Comment by hiroppy** [comment]
I'll work on this after merging https://github.com/webpack/webpack-dev-server/pull/2531, because transportMode is broken in this pr.

**Comment by hiroppy** [comment]
hm, If we modify the sockPath(overwriting to this.options.sockPath), webpack-dev-server will be broken maybe... @Loonride can you know why this causes?

**Comment by Loonride** [comment]
> hm, If we modify the sockPath(overwriting to this.options.sockPath), webpack-dev-server will be broken maybe... @Loonride can you know why this causes?

@hiroppy I'm not sure, where is it being modified exactly? Maybe the webpack entry is being created with that sockPath before it is modified

**Comment by hiroppy** [comment]
@Loonride thanks, I'll check this pr again after merging #2593

**Comment by hiroppy** [comment]
CI is green. Thanks, @Loonride. So don't merge this before merging #2593.

**Comment by hiroppy** [comment]
@evilebottnawi Updated!

**Pull request merged**
