### PR TITLE
add --stdin functionality from webpack PR #1311 to webpack-dev-server

### PR DESCRIPTION
**Pull request by kevinold**
based on https://github.com/webpack/webpack/pull/1311

### CODE REVIEW

**Comment by sokra** [comment]
please fix the whitespaces (spaces -> tabs)

**Comment by sokra** [comment]
already support through `--watch-stdin` in webpack

**Comment by imranismail** [comment]
doesn't seem to work for me

`webpack-dev-server --watch-stdin --progress`

**Comment by imranismail** [comment]
Doesn't work for me and this PR fixed it.

**Pull request closed without merging**
