### PR TITLE
Find out if compiler is done over http

### PR DESCRIPTION
**Pull request by delijah**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Not sure how to test this...

### Motivation / Use-Case

On our system it takes a long time to build our stack. Since we are running visual tests on webpack-dev-server, our test client would like to know, if the dev server is ready / has built everything. This head request will provide this information.

### Breaking Changes

No

### Additional Info

I was not able to test this code. If someone could help me, that would be great.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I don't think we need this, you can use `before` for custom middleware

**Comment by evilebottnawi** [comment]
Thanks for the PR

**Comment by delijah** [comment]
Not sure if i understand that correctly. Where and how can i use `before`?

**Comment by delijah** [comment]
@evilebottnawi ok, but how to access `compiler.state` within the before callback?

**Comment by evilebottnawi** [comment]
@delijah let's add `compiler` argument to `before` and `after`

**Comment by evilebottnawi** [comment]
@delijah i will add this in near future

**Comment by delijah** [comment]
Ok cool, thank you 👍

**Pull request closed without merging**
