### PR TITLE
fixes #1616, allows retries to increase at each reconnect

### LINKED ISSUE #1616: [sockjs-client] fix exponential reconnect time
* Operating System: Debian
* Node Version: v11.6.0
* NPM Version: 6.5.0
* webpack Version: 4.28.3
* webpack-dev-server Version: 3.1.14

- [x] This is a **bug**

### Code

You can see the problem here:
https://github.com/webpack/webpack-dev-server/blob/v3.1.14/client-src/default/socket.js

### Expected Behavior

An exponential increase in time between reconnects with the sockjs server.

### Actual Behavior

As you can see in the code I linked, the method `onopen` resets the `retries` variable to 0, so retries is always 0, and `onclose` always tries to reconnect waiting the minimum time. Therefore the 'infinite logspam' solution doesn't work and people experience what is depicted in https://github.com/webpack/webpack-dev-server/issues/1604

Also, here (from https://github.com/webpack/webpack-dev-server/issues/1604 as well): 
50633098-6354a900-0f4a-11e9-95ba-22cbbc569438

### How can we reproduce the behavior?

Make the sockjs server close the connection (for example because the client has a bad origin header), the client will try to reconnect forever without respecting the intended timeout.

It is obvious looking at the code anyway.

### PR

I've already submitted a PR.

### PR DESCRIPTION
**Pull request by carlosgeos**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No

### Motivation / Use-Case

fixes #1616 

### Breaking Changes

None

### CODE REVIEW

**Comment by carlosgeos** [comment]
No idea how to test this sorry

**Comment by evilebottnawi** [comment]
@carlosgeos hm, can you provide example how we can tests this manually?

**Comment by carlosgeos** [comment]
Yes very easy:

1. Have a simple `webpack` project. Install `webpack-dev-server` version 3.1.11 (the bug in this version makes testing easier)
2. Start the dev server and open the console
3. You will see an infinite and continuous amount of `Invalid Host/Origin header` and `[WDS] Disconnected!`
4. Now change: https://github.com/webpack/webpack-dev-server/pull/1617/files#diff-921405d3577e8069eb36a2f7c859c075 and run the dev server again.
5. You will see a maximum of 10 reconnects (not infinite) and spaced out in time.

I also added some logs and did this and this is what I get:
OLD:
screenshot_20190109_111057

NEW:
screenshot_20190109_111022

**Comment by evilebottnawi** [comment]
@carlosgeos Thanks looks good for me! Can we add some comments about this behavior in code for `retries` variable? It will be good for future developers and avoid regressions, thanks

**Comment by carlosgeos** [comment]
Yes I'll do it

**Comment by hiroppy** [comment]
CI fails.

```
/home/travis/build/webpack/webpack-dev-server/test/Socket.test.js
  6:16  error  `../client-src/default/socket.js` import should occur before import of `./fixtures/simple-config/webpack.config`  import/order
✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by evilebottnawi** [comment]
@hiroppy can you reproduce problem with above repo?

**Comment by hiroppy** [comment]
@evilebottnawi  Which repo? this one? https://github.com/webpack/webpack-dev-server/pull/1617#issuecomment-452643037

I tested using `examples/cli/hmr` at master branch, but I didn't meet this error.

**Comment by evilebottnawi** [comment]
@hiroppy Yes, i can't reproduce too, we need reproduce problem

**Comment by hiroppy** [comment]
@carlosgeos Could you submit the reproducible repo because we weren't able to meet this error?

**Comment by carlosgeos** [comment]
Steps to reproduce:

1.- Clone https://github.com/carlosgeos/simple-webpack-repo
2.- `npm i` && `npm run start:dev`
3.- Open browser, go to localhost:8080, BUT mimic accessing the socket server externally from another tab/site. I used https://addons.mozilla.org/en-US/firefox/addon/simple-modify-header/ and changed the Origin header to something else. This way you will trigger the functionality of https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/socket.js
4.- You will see an infinite, 1-second spaced log of:

Screenshot_20190531_124630

It should be an exponential increase which was the intended feature.

I agree, this does not happen often, and it is not the normal use case, but it could happen. It's a small change for a small problem.

---

Options set in `simple-modify-header`:
Screenshot_20190531_125620

Previous `webpack-dev-server` versions (3.1.11) did not check the Origin header correctly so the header change was not even necessary.

**Comment by evilebottnawi** [comment]
Thank, agree it is bug, but nut sure about message output, i think we should rewrite:
```
 if (retries === 0) {
      handlers.close();
    } // Try to reconnect.
```
to
```
handlers.close();
```

For better message

**Comment by hiroppy** [comment]
@carlosgeos Could you rebase from master?

**Pull request closed without merging**
