### PR TITLE
fix: update CI

### PR DESCRIPTION
**Pull request by chenxsan**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

After upgrading webpack from 4.43.0 to 4.44.2 https://github.com/webpack/webpack-dev-server/pull/2764/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L12480, a lot of tests failed. Guess we should fix it first.

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
We are working in v4 branch, no need to update this

**Comment by chenxsan** [comment]
@evilebottnawi Do you mean pull request https://github.com/webpack/webpack-dev-server/pull/2761 will be merged into v4 not v3? I think you told webpack-dev-server v3 is going to support webpack v4 and v5? That's why I want to fix those CI problems first, or that pull request testing against webpack v4 will fail for webpack v4.

**Comment by chenxsan** [comment]
Anyway, I think I've found the reason of the issue, I'll make a PR to [watchpack](https://github.com/webpack/watchpack) first. And if you're willing to accept this PR fixing the CI, I can continue it, otherwise let's drop it.

**Comment by chenxsan** [comment]
`yarn jest` would pass while `yarn jest -- --coverage` would fail.

**Comment by evilebottnawi** [comment]
Fixed for v4, I think we don't need it for v3, because v3 is very deprecated, we need to do release ASAP and focus on webpack-dev-server v4, I want to close it, anyway thanks for the PR and help

**Pull request closed without merging**
