### PR TITLE
ci: make use of github-actions

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

drop azure-pipelines.

closes: https://github.com/webpack/webpack-dev-server/issues/2499

### CODE REVIEW

**Comment by hiroppy** [comment]
NOTE: lint CI is fixed by https://github.com/webpack/webpack-dev-server/pull/2708.

**Comment by hiroppy** [comment]
CI looks fine.

**Comment by hiroppy** [comment]
@evilebottnawi Modify the badge url, ptal

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
