### PR TITLE
BREAK CHANGES(cleint): rename keynames to camelCase

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

camelCase is very common in JavaScript world so I modified them from snake-case.

### Breaking Changes

Yep

### Additional Info

CI is broken so I'll fix it.

### CODE REVIEW

**Comment by hiroppy** [comment]
Wait for https://github.com/webpack/webpack-dev-server/pull/2734

**Review by evilebottnawi — COMMENTED** [review]
It creates breaking change for other plugins/servers/etc which connect to our socket server and send messages for reloading, I think it is really unnecessary to do it, no benefits from this

**Comment by hiroppy** [comment]
ok

**Comment by evilebottnawi** [comment]
Anyway thanks for your work

**Pull request closed without merging**
