### PR TITLE
Sockjs prefix config

### PR DESCRIPTION
**Pull request by kellyrmilligan**
**What kind of change does this PR introduce?**
This adds the capability to prefix the url that `sockjs-node` is served from. This is useful for having multiple applications in development being behind a reverse proxy. 

**Did you add or update the `examples/`?**

**Summary**

https://github.com/webpack/webpack-dev-server/issues/909

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by kellyrmilligan** [comment]
I need some guidance, in index.js for the client that gets built, i'm wondering 

```js
var socketUrl = url.format({
	protocol: protocol,
	auth: urlParts.auth,
	hostname: hostname,
	port: (urlParts.port === "0") ? self.location.port : urlParts.port,
	pathname: urlParts.path == null || urlParts.path === "/" ? "/sockjs-node" : urlParts.path
});
```

in what scenario does `urlParts.path` get used?

what other scenarios involve `/sockjs-node` on the client-side?

**Comment by kellyrmilligan** [comment]
updated to take a stab at this. it seems like the urlParts.path woudl be used when you pass a query string while including the hot client file. I am not sure this change needs to handle that scenario?

**Comment by kellyrmilligan** [comment]
also added an example doing it, although I can't seem to figure out adding historyapifallback into the mix to fully show a subapp. any ideas?

**Comment by kellyrmilligan** [comment]
@SpaceK33z what are your thoughts on this?

https://github.com/facebookincubator/create-react-app/pull/1887

depends on this being in place.

**Comment by Timer** [comment]
Pinging @d3viant0ne; we'd love to see some feedback/progression on this PR so we can land https://github.com/facebookincubator/create-react-app/pull/1887.

**Comment by Timer** [comment]
@kellyrmilligan would you be available to bring this up to date if we can get the ball rolling?

**Comment by kellyrmilligan** [comment]
Yes I can spend some time on it for sure. Been meaning to try and more directly ping someone so thanks for that

**Comment by d3viant0ne** [comment]
@kellyrmilligan - Get it rebased if you don't mind and  we'll get it queued up.

**Comment by kellyrmilligan** [comment]
:metal:

**Comment by kellyrmilligan** [comment]
@d3viant0ne @Timer updated to latest master. I've only been a consumer of webpack dev server in the past, so let me preface this pr with that. I am not sure i'm using the proper variable in the client side portion of this to accommodate the prefix.

**Comment by d3viant0ne** [comment]
FYI - This hasn't been forgotten, most of the people that can pick this up & actually do something with it are all busy i.r.l. I was hoping to get this done without having to ping Kees but it's looking like that's the way it's going to have to be.

**Comment by shellscape** [comment]
We wanted to get some more eyes on this, but after talking with @d3viant0ne we agreed that it was OK to merge. Keep an eye out for a new minor version of the module tomorrow.

**Comment by the-spyke** [comment]
Just updated my deps, and looks like this broke my app:

```
:8086//sockjs-node/iframe.html#vz40durl Failed to load resource: the server responded with a status of 404 (Not Found)
:8086//sockjs-node/210/zkmtecqi/jsonp?c=_jp.akv1ra3:1
Uncaught SyntaxError: Unexpected token <
webpack-internal:///630:146
[WDS] Disconnected!
```

**Comment by shellscape** [comment]
@the-spyke that's a bummer and I'm sorry that happened. But without for more info that's not very helpful. I'd suggest opening a new issue, following the issue template, and outlining more. Consider adding an example that would allow developers to reproduce the errors you're seeing.

**Comment by renchap** [comment]
An issue about this has been opened: #1021

**Pull request merged**
