### PR TITLE
Move loglevel from devDependencies to dependencies

### PR DESCRIPTION
**Pull request by athomann**
**What kind of change does this PR introduce?**
Bugfix

**Summary**
Moves logllevel from devDependencies to dependencies to fix bug in:
https://github.com/webpack/webpack-dev-server/issues/1000

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by madlordory** [comment]
+1 
unbelievable mistake

**Comment by ai** [comment]
+1 Got it in production

**Comment by sugarshin** [comment]
+1

**Comment by SpaceK33z** [comment]
Ouch, whoops sorry everyone.

**Comment by SpaceK33z** [comment]
Fixed in webpack-dev-server@2.6.1

**Pull request merged**
