### PR TITLE
refactor(routes): refactor utils/routes.js

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

yes

### Motivation / Use-Case

just refactoring.

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy What do you think about routes for next version? I think we should remove some of them

**Comment by hiroppy** [comment]
@evilebottnawi You mean some endpoints are unnecessary?

**Comment by evilebottnawi** [comment]
@hiroppy yes, i think we don't need this because it is legacy stuff

**Comment by hiroppy** [comment]
All endpoints?

**Comment by evilebottnawi** [comment]
@hiroppy need investigate using `index.bundle.js` directly is invalid, because it is require some options for detect what transportMode we use, also socker options can be invalid, i think we should remove usage using `script` tag with this route

**Comment by hiroppy** [comment]
@evilebottnawi ok, understood. I'll investigate it. May I merge this pr?

**Pull request merged**
