### PR TITLE
test(client): socket helper tests

### PR DESCRIPTION
**Pull request by Loonride**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

Added tests to confirm that the client `socket` helper is using client implementations correctly.

### Breaking Changes

None

### CODE REVIEW

**Comment by Loonride** [comment]
@evilebottnawi What do you think I should name it? It follows conventions of the `client` test directory, but you are right that maybe it is too generic.

**Comment by evilebottnawi** [comment]
Yes, just other name, maybe more complex, because name is misleading, any ideas?

**Comment by Loonride** [comment]
> Yes, just other name, maybe more complex, because name is misleading, any ideas?

How about `socket-util.test.js`?

**Comment by hiroppy** [comment]
hm, this file has already included in `utils/`, so I think `util` is unnecessary.

**Pull request merged**
