### PR TITLE
fix(run-open): delete extra slashe in openPage option

### PR DESCRIPTION
**Pull request by yinsang**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### CODE REVIEW

**Comment by yinsang** [comment]
> Need test

Actually, All tests in 'runOpen.test.js' is wrote by the wrong way.  'https://example.com/' is wrote as 'https://example.com'.
Do you mean I can rewrite All the tests in 'runOpen.test.js'?

**Comment by evilebottnawi** [comment]
Just add a new test

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.2`

**Comment by alexander-akait** [comment]
Sorry for delay :disappointed:

**Pull request closed without merging**
