### PR TITLE
fix: minor typo

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
N/A

### Motivation / Use-Case
Fix minor typo.

### Breaking Changes
N/A

### Additional Info
N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @evilebottnawi @hiroppy

**Comment by evilebottnawi** [comment]
@jamesgeorge007 please don't spam `cc`, we we see everything that you send and open

**Comment by jamesgeorge007** [comment]
> @jamesgeorge007 please don't spam `cc`, we we see everything that you send and open

oops! sorry about that :pray:

**Comment by jamesgeorge007** [comment]
@evilebottnawi thoughts :thinking:

**Pull request merged**
