### PR TITLE
Implement error overlay

### PR DESCRIPTION
**Pull request by SpaceK33z**
**What kind of change does this PR introduce?**
Feature

**Did you add or update the `examples/`?**
Yes

**Summary**
This adds an error overlay in the browser, like create-react-app has. It works very much like create-react-app's error overlay. In fact, I copied much code from it 😅 .

I asked on Twitter if people would [like this feature](https://twitter.com/keeskluskens/status/825008478536228865), and ~~everyone forgot Trump for a while~~ people were happy.

The error overlay is only enabled when you add the option `overlay: true` in your `devServer` config. It could be enabled by default, but that would kinda be a breaking change so *maybe* in v3.

Furthermore, it will only show errors, not warnings. I'm not sure yet if we should display warnings the same way. If we would do that, there also needs to be a way to disable it.

**Does this PR introduce a breaking change?**
Nope

### CODE REVIEW

**Comment by SpaceK33z** [comment]
If anybody would want to test this, that would be appreciated. [Info on how to test a PR](https://github.com/webpack/webpack-dev-server/blob/master/CONTRIBUTING.md#testing-a-pull-request).

**Comment by STRML** [comment]
A few comments:

1. `overlay` option works fine. :+1:
1. I'm not able to get the actual syntax error location from something like `<div></span>` - I just get the stack with `Module build failed`. Using HMR and `devtool: "eval"`. Is there further setup required?

**Comment by Restuta** [comment]
I am not using "webpack-dev-server" directly, I am using "webpack-dev-middleware", is there a way to have it as part of the middleware itself? @SpaceK33z

**Comment by karl** [comment]
Just tested this in our codebase at work and it behaved correctly as far as I could see. We would find this really useful for making it clear when compilation had failed.

We'd definitely use this if it was merged in!

**Comment by SpaceK33z** [comment]
@STRML, I just tested this in a project of mine with React and JSX. It looks like this when I change a `</div>` to `</span>`:

screen shot 2017-02-03 at 11 38 26

It didn't need any extra configuration. This was with `devtool: "eval"`. I haven't setup HMR though (don't have the time right now to test that out).

@Restuta, no, webpack-dev-middleware can't communicate to the webpage since it's only middleware. [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) does offer this functionality btw.

@karl, thanks for testing!

**Comment by Restuta** [comment]
@SpaceK33z I meant hot-middleware, sorry

**Comment by KutnerUri** [comment]
@SpaceK33z - is this still live? does it handle runtime errors?

I'm getting this less "sexy" overlay
Screen Shot 2022-02-22 at 17 51 46

**Pull request merged**
