### PR TITLE
refactor: remove unused method

### PR DESCRIPTION
**Pull request by alexander-akait**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

existing

### Motivation / Use-Case

we don't use it

### Breaking Changes

potentially yes, but it should be not used directly

### Additional Info

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
It is breaking change for v4, use `devServer.server`

**Comment by zbrcz** [comment]
Not sure I understand.

We are doing something like this:

```
const server = new WebpackDevServer(/* ... */);
server.use((req, res) => {
  res.end(/* ... */);
});
```

Now we get "TypeError: server.use is not a function". What to use instead of `server.use` to be able to tap into the request handling process?

Thanks.

**Comment by alexander-akait** [comment]
```
const devServer = new WebpackDevServer();

await devServer.start();

devServer.server.use(() => {});
```

**Comment by zbrcz** [comment]
Unfortunately, that just gives "TypeError: Cannot read property 'use' of undefined"... `devServer.server` is not defined.

**Comment by alexander-akait** [comment]
Check your code https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1601

**Comment by zbrcz** [comment]
It seems the error I reported in my previous message was due to some mistake in my code. Even after fixing it, I kept getting "TypeError: devServer.server.use is not a function", though. Ended up using `devServer.app.use`. Thanks for all your help!

**Pull request merged**
