### PR TITLE
add cors

### PR DESCRIPTION
**Pull request by Dakuan**
This fixes a bug when using a hot-loader. See https://github.com/gaearon/react-hot-loader/issues/56

### CODE REVIEW

**Comment by troutowicz** [comment]
This isn't really a bug. When doing local development, why would you need CORS enabled? If you want the ability to access the the webpack dev server's socket.io instance anywhere inside your local network, you can just use the `--host` CLI flag. This flag was not included in the documentation, I updated the docs.

**Comment by gilesbradshaw** [comment]
When you are writing an isomorphic application you want to do a hot reload of the client AND restart node.  Otherwise the two get out of sync when you next refresh the page.

**Comment by jedwards1211** [comment]
@troutowicz CORS is also necessary when integrating with an existing server like Meteor, where the HTML is served up on Meteor, but the webpack bundles are served up by webpack-dev-server on a different port.

**Comment by yinsang** [comment]
[chrome plugin](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi/reviews)

**Pull request closed without merging**
