### PR TITLE
refactor: rename client properties

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Yes updated existing ones

### Motivation / Use-Case
following changes for `client` option -
 
`host` to `webSocketHost`
`port` to `webSocketPort`
`path` to `webSocketPath`

### Breaking Changes
`client.host`, `client.port`, `client.path` were removed.

### Additional Info
None

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
I think we should union these options and remove the `public` in favor `socketURL`, example usage:
```
client: {
  socketURL: 'ws://hostname:port/path'
}
```

If you need provide only some of them developer can use `ws://0.0.0.0:0/path`.

`0.0.0.0` means pick `self.location.hostname`
`:0` means pick `self.location.port`

I already improve it here https://github.com/webpack/webpack-dev-server/pull/3159 for future

**Comment by alexander-akait** [comment]
If you help me with this will be great, I think it is one of the last braking change and we will do rc

**Comment by snitin315** [comment]
Let's do it 🚀

**Comment by anshumanv** [comment]
Stale, closing in favour of https://github.com/webpack/webpack-dev-server/pull/3309

**Pull request closed without merging**
