### PR TITLE
fix(run-open): introduce open instead of opn

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

modified

### Motivation / Use-Case

opn is deprecated.

### Breaking Changes

yes because open doesn't support Node6.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy Let's send the first PR with updating package.json/babel + drop old nodejs on CI for `v4` branch and then starts to update

**Comment by evilebottnawi** [comment]
Anyway good job!

**Comment by hiroppy** [comment]
@evilebottnawi I'm working on the updating deps on another pr.  please review this

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
