### PR TITLE
Remove depth limit from chokidar options

### PR DESCRIPTION
**Pull request by marcofugaro**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

The `watchContentBase` option would only watch only the root folder, this PR removes that limitation.

Discussion in #1694

The `watchContentBase` option will now watch the folder recursively

### CODE REVIEW

**Comment by marcofugaro** [comment]
@evilebottnawi
For now I've made the test that edits a nested file, but I should check that chokidar has been triggered and the browser has been refreshed. How do i go about testing this?

Could you give me more directions?

**Comment by evilebottnawi** [comment]
No need check is browser refreshed, anyway if you do this will be great (example e2e tests https://github.com/webpack/webpack-dev-server/blob/master/test/Client.test.js).

Main test is mocking `chokidar` and check event was handled (https://github.com/webpack/webpack-dev-server/blob/21687c3bfc95752957d16470b97d281001dc6a07/lib/Server.js#L954). More infromation about mocking https://jestjs.io/docs/en/mock-functions.html

**Comment by marcofugaro** [comment]
@evilebottnawi alright I wrote some code that should work, however I am having some troubles with connecting puppeteer to the server, am I doing something wrong?

image

**Comment by evilebottnawi** [comment]
maybe you already have app on 9001 port? Or you we need run test in serial

**Comment by marcofugaro** [comment]
@evilebottnawi jest is already being run with the `--runInBand`, so it should run one at a time.

Also no, I don't have anything on the 9001 port, it still gives the error even if I change the port.

**Comment by hiroppy** [comment]
@marcofugaro This test code should be fixed like below.

<details>

```diff
diff --git a/test/ContentBase.test.js b/test/ContentBase.test.js
index 4813372..70b57eb 100644
--- a/test/ContentBase.test.js
+++ b/test/ContentBase.test.js
@@ -20,7 +20,6 @@ const contentBaseOther = path.join(
 describe('ContentBase', () => {
   let server;
   let req;
-  afterEach(helper.close);
 
   describe('to directory', () => {
     beforeAll((done) => {
@@ -32,15 +31,21 @@ describe('ContentBase', () => {
       addEntries(config, options);
       server = helper.start(
         config,
-        {
+        Object.assign({}, options, {
           contentBase: contentBasePublic,
           watchContentBase: true,
-        },
+        }),
         done
       );
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request to index', (done) => {
       req.get('/').expect(200, /Heyo/, done);
     });
@@ -54,7 +59,8 @@ describe('ContentBase', () => {
 
       runBrowser().then(({ page, browser }) => {
         // wait for first load
-        page.goto('http://localhost:9001').then(() => {
+        page.goto('http://0.0.0.0:9001').then(() => {
+          done(); // TODO: change this
           // page reloaded after the first load,
           // meaning it watched the file correctly
           page.on('load', () => {
@@ -82,6 +88,12 @@ describe('ContentBase', () => {
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request to first directory', (done) => {
       req.get('/').expect(200, /Heyo/, done);
     });
@@ -103,6 +115,12 @@ describe('ContentBase', () => {
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request to page', (done) => {
       req
         .get('/other.html')
@@ -123,6 +141,12 @@ describe('ContentBase', () => {
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request to page', (done) => {
       req
         .get('/foo.html')
@@ -147,6 +171,12 @@ describe('ContentBase', () => {
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request to page', (done) => {
       req.get('/other.html').expect(200, done);
     });
@@ -167,6 +197,12 @@ describe('ContentBase', () => {
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request to page', (done) => {
       req.get('/other.html').expect(404, done);
     });
@@ -184,6 +220,12 @@ describe('ContentBase', () => {
       req = request(server.app);
     });
 
+    afterAll((done) => {
+      helper.close(() => {
+        done();
+      });
+    });
+
     it('Request foo.wasm', (done) => {
       req.get('/foo.wasm').expect('Content-Type', 'application/wasm', done);
     });

```

</details>

**Pull request merged**
