### PR TITLE
Add 'allowedHosts' option

### PR DESCRIPTION
**Pull request by orteth01**
**What kind of change does this PR introduce?**
feature/bugfix

**Did you add or update the `examples/`?**
no

**Summary**
Host checking was added by default in v2.4.3 for security reasons. Users now have to specify the host/URL being used to access the dev-server [more info here](https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a) 

This PR allows users to specify multiple hosts that that will pass the check. Recommended by @edmorley here: https://github.com/webpack/webpack-dev-server/issues/882#issuecomment-296799201

**Does this PR introduce a breaking change?**
no

**Example usage in webpack config:**

```js
devServer: {
    allowedHosts: [
        'exampleHost.com',
        'differentExampleHost.com',
        ...
    ]
}
```

**subdomain wildcard:**

mimicking django's `ALLOWED_HOSTS`, a value beginning with "." can be used as a subdomain wildcard. '.example.com' will match example.com, www.example.com, and any other subdomain of example.com.

```js
devServer: {
    allowedHosts: [
        '.example.com'
    ]
}
```

### CODE REVIEW

**Comment by mgol** [comment]
[Django docs](https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts) say:

> A value beginning with a period can be used as a subdomain wildcard: '.example.com' will match example.com, www.example.com, and any other subdomain of example.com.

Could this be added as well?

**Comment by orteth01** [comment]
@mgol I didn't realize that there were already a few tests for `Server.prototype.checkHost` 
https://github.com/webpack/webpack-dev-server/blob/master/test/Validation.test.js#L65-L118

I can either add tests for `allowedHosts` there or I can remove those tests because the tests that I added cover those cases. Which do you prefer?

**Comment by mgol** [comment]
@orteth01 I guess it makes sense to nest that under existing tests (a separate inner `describe` sounds good).

Note, though, that I'm just a user, not a member of Webpack's core team so you might want to wait for someone on the team to decide. I'm just providing my own feedback.

**Comment by orteth01** [comment]
> I guess it makes sense to nest that under existing tests (a separate inner describe sounds good).

Yea that makes more sense, I think. I've gone with that option. thanks, @mgol

**Comment by orteth01** [comment]
I've signed the CLA. not sure why that check is still waiting for the status to be reported....\

**Comment by orteth01** [comment]
There seem to be a few open issues that this PR would remedy. Any thoughts, @SpaceK33z ??

**Comment by ssilve1989** [comment]
What's the status on this?

**Comment by orteth01** [comment]
> What's the status on this?

@ssilve1989 waiting on review from one of Webpack's core team members

**Comment by prencher** [comment]
@SpaceK33z @sokra I hate to be that guy, but this is preventing us from moving to a more secure setup; The point of the change this inspired. Can we get movement on this PR?

I am happy to assist if I can.

**Comment by Justus-Maier** [comment]
Can I put an IP address with wildcards in here too? I sometimes get new IP from DHCP and I would like to share my current work with my collegues (just open a browser). Can this be done without me registering a local private domain?

**Comment by orteth01** [comment]
> Can I put an IP address with wildcards in here too?

Currently, you can add an ip address as an allowed host but not with wildcards.

Only the subdomain wildcard is supported, meaning that only the first part of your allowed host can be dynamic. In theory I guess you could have something like this
```
devServer: {
    allowedHosts: [
        '.123.123'
    ]
}
```
which would allow any IP's that take the form `*.*.123.123`. However, I think that would not be recommended, as it allows **any** ip that matches that pattern to access your dev server.

**Comment by mgol** [comment]
@orteth01 For IPs I'd expect a wildcard going in a different direction, e.g. `192.168.`.

**Comment by edmorley** [comment]
As I mentioned in some of the other threads, it should be safe to whitelist **all** IP-addresses-like hosts names by default, which would save people having to whitelist them manually.

**Comment by orteth01** [comment]
> it should be safe to whitelist all IP-addresses-like hosts names by default

@edmorley it seems like a separate PR would be appropriate for that. I'll create an issue.

**Comment by shellscape** [comment]
@orteth01 merged the PR, as its a solid feature and has been in waiting for quite some time, but we still need example/readme updates for this. we've got a little bit of time before we release, would be great if you would be able to add that.

**Comment by orteth01** [comment]
> we still need example/readme updates for this

@shellscape I'm more than happy to help with documentation! I'm assuming that I should update [this readme](https://github.com/webpack/webpack.js.org/blob/master/content/configuration/dev-server.md). Are there any other places where I should add information regarding this feature?

**Comment by shellscape** [comment]
@orteth01 awesome. yes, please do update that readme. It's also suggested to create an example directory to demo the option.

**Comment by Justus-Maier** [comment]
@orteth01 please also add some documentation for the disabling flag of the allowedHosts feature:
`config.devServer.disableHostCheck = true`
With security warnings obviously ;D

**Comment by Mario-Eis** [comment]
Can this be set via command line?

**Comment by orteth01** [comment]
> Can this be set via command line?

@Mario-Eis not currently. i'll try to get a PR open by the end of the week.

**Pull request merged**
