### PR TITLE
fix: prepend entrypoints instead of append

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

this resolves an issue with module federation

re #2692
### Motivation / Use-Case

Module Federation will not work with WDS in its current state

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Tests still need to be written

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by evilebottnawi** [comment]
In my TODO

**Comment by ScriptedAlchemy** [comment]
Thanks!

**Comment by Loonride** [comment]
@ScriptedAlchemy Did you test this locally, and did it solve the issue? If so, was it with webpack@5?

From my tests, it appears that this does not solve the problem for webpack@5. Webpack 5 seems to not handle entries correctly if they are added on after the compiler is created, regardless of if they are appended or prepended. Basically, if any entry is added onto the entry array, the module that was supposed to be exported will be ignored, and just an empty object will be exported, no matter what has been added to the entry array.

I got the same result as described here: https://github.com/webpack/webpack-dev-server/issues/2719#issuecomment-679114178

This may need to be solved on the webpack side, so that entries can be injected after the compiler is created without causing problems.

**Comment by alexander-akait** [comment]
Fixed in master, anyway thanks for the PR

**Pull request closed without merging**
