### PR TITLE
feat: export initialized socket client

### LINKED ISSUE #4261: Expose Socket Client for external integrations
### Feature Proposal

Allow external integrations to tap into the socket client of WDS in order to consume compilation events, such as build logs, errors, progress, etc.

Right now, the client is done as a module level singleton:

https://github.com/webpack/webpack-dev-server/blob/87401b4927c75f1c5114508216101fd1a3ec9e67/client-src/socket.js#L19

Perhaps we can assign it to some special global variable on `window`, or export this variable, so external parties can just consume the client.

### Feature Use Case

This is mainly for custom error overlays that include wider coverage outside of what WDS provides (`react-error-overlay`, overlay from `@pmmmwh/react-refresh-webpack-plugin`), but it would also enable client-only tooling to sniff on HMR lifecycle, build status and more.

It is not impossible to achieve this functionality right now since the `__webpack_dev_server_client__` global is defined, and we can use that as a starting point, but we would have to do two things that is not preferrable:

1. Duplicate socket URL logic - which tightly couples the code to 1 version of WDS (and we have to keep up with all the special cases handled here)
2. Duplicate socket connection - since we have to create the client from scratch, the connection would happen multiple times, which could be confusing to users (#4224, https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/279, https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/481)

### Inspirations

`webpack-hot-middleware`

https://github.com/webpack-contrib/webpack-hot-middleware/blob/e140693fa3f648c078a47a678d66b53579f28ee2/client.js#L148-L159

### PR DESCRIPTION
**Pull request by pmmmwh**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

~No new tests are added as I believe this is a simple change and no additional functionality is added, it just exposes a bit more of the private parts.~

Added a simple test for `null` value before init, and a "valid" client instance after init.

### Motivation / Use-Case

Fixes #4261
Fixes #4324

### Additional Info

I chose the simplest way to expose the initialized client, so consumers can just import the file and use it - but I'm also ok with setting it to some globals (on `globalThis`/`window`) if you think that's better (I'm unsure if mutable exports are implemented properly when compiled?).

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
Let's fix lint.

**Comment by pmmmwh** [comment]
I'm not sure if I should just do eslint ignore here, or should I do something more

**Comment by alexander-akait** [comment]
Just add `eslint-plugin-ignore` and small comment(s) why we need to it

**Comment by alexander-akait** [comment]
@pmmmwh Can we add small test cases (where we try to get client) to avoid future regressions?

**Comment by pmmmwh** [comment]
Added test!

**Comment by pmmmwh** [comment]
Completely rebased onto latest HEAD + fixed commitlint issue 😄

**Comment by alexander-akait** [comment]
Thanks

**Comment by alexander-akait** [comment]
@pmmmwh Published https://github.com/webpack/webpack-dev-server/releases/tag/v4.8.0

**Pull request merged**
