### PR TITLE
[2.x backport] perf(Server): don't enable all `stats` by default

### PR DESCRIPTION
**Pull request by kenotron**
- [x] This is a **bugfix**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **typo fix**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No - tests currently covered the scenario

### Motivation / Use-Case

Merging the same speedy change from v3.x code to v2.x (we still use it since v2 is slightly faster for inc builds still for us)

### Breaking Changes

No breaking changes

### CODE REVIEW

**Comment by kenotron** [comment]
@SpaceK33z I know this is super in maintenance mode (v2), but would you mind merging this one too?  The v2 branch somehow is faster than v3, so at scale, we're still having to use this.

**Comment by evilebottnawi** [comment]
@kenotron all good, v2 also in `maintenance mode`, because many people use `webpack@3`

**Comment by evilebottnawi** [comment]
@SpaceK33z friendly ping :+1:

**Comment by michael-ciniawsky** [comment]
This isn't really a patch as sadly as it is. I'm not sure if we can backport this tbh

**Comment by michael-ciniawsky** [comment]
Sry but this is a breaking chnage for the `v2.x` line, please upgrade to `v3.x` instead

**Pull request closed without merging**
