### PR TITLE
refactor: make use of `graceful-fs`

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?
No

### Motivation / Use-Case

No need to use a dependency just for using `fs.existsSync`. 

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Comment by alexander-akait** [comment]
`graceful-fs` and `fs` have some differents

> retries reading a file if read results in EAGAIN error.

**Comment by snitin315** [comment]
Then let's update more instances of `fs` with `graceful-fs`?

https://github.com/webpack/webpack-dev-server/blob/b0161e9852cdf41730e82aa43efe7e88f44a4f9d/lib/utils/getCertificate.js#L17

**Comment by alexander-akait** [comment]
Make sense

**Comment by snitin315** [comment]
Will do 👍🏻

**Review by alexander-akait — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]
👍

**Pull request merged**
