### PR TITLE
Remove header property value validation

### PR DESCRIPTION
**Pull request by wlindner**
This PR removes property validation for header properties.

**What kind of change does this PR introduce?**

bugfix

**Did you add or update the `examples/`?**
No changes were necessary.

**Summary**

The validation that was being used before this PR was preventing multiple cookies from being set (Set-Cookie), or multiple domains being used (Access-Control-Allow-Origin). The 'http' server supports strings or arrays, so this validation was preventing this functionality from working.

https://github.com/webpack/webpack-dev-server/issues/964

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by shellscape** [comment]
As a slight modification to your original PR description, this PR doesn't remove validation of header properties, but rather header property _values_.

Citing the spec is also useful when submitting PRs for scheme validation changes: https://trac.tools.ietf.org/html/draft-wright-json-schema-validation-01#page-11

The documentation will have to be changed once this is merged and published: https://webpack.js.org/configuration/dev-server/#devserver-headers-

Before we can approve this change, we need to add an additional test for headers set to an array, after this test: https://github.com/webpack/webpack-dev-server/blob/69239ce854dd0a4bdb752fbd78c47c348aa9f900/test/Routes.test.js#L60

**Comment by wlindner** [comment]
@shellscape Thanks for your quick response on this, looking forward to getting this included so we can use webpack-dev-server again.

**Comment by shellscape** [comment]
@wlindner ping. please see comments.

**Comment by wlindner** [comment]
@shellscape I just pushed a new commit that includes tests. I went ahead and restructured the tests in this file so that I could properly do the test setup: one testing headers as a string and one as an array. If this is not how you want it to be structured please let me know.

**Comment by shellscape** [comment]
@wlindner thanks for making those updates, and all your work on this PR so far. you've still got a linting error in CI that needs addressing, and the branch is out of date and should be updated.

**Comment by wlindner** [comment]
@shellscape I've made all the changes you requested, let me know if you need anything additional to receive this PR.

**Comment by shellscape** [comment]
@wlindner looks like you still have an issue with CI. Click the "details" link for the "continuous-integration/travis-ci/pr" item and examine the log to find out what's causing an issue. We can't merge until that's resolved.

**Comment by wlindner** [comment]
@shellscape ok, I think I did all the things you needed to prepare this PR. Let me know if I missed anything.

**Pull request merged**
