### PR TITLE
fix(package.json): make quotes windows compatible

### PR DESCRIPTION
**Pull request by Loonride**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No

### Motivation / Use-Case

Make quotes in `package.json` windows-compatible
https://github.com/webpack/webpack-dev-server/issues/1905

### Breaking Changes

None

### Additional Info

fixes https://github.com/webpack/webpack-dev-server/issues/1905

### CODE REVIEW

**Comment by hiroppy** [comment]
npm-run-all's author said, "To enclose glob in double quotes is always safe." I talked about this issue with him.

**Comment by evilebottnawi** [comment]
HM, single quotes should be work too, a lot of repos use npm-run-all and use single quotes and no problems :confused:

**Comment by hiroppy** [comment]
😂 sorry, I don't have windows pc, so I cannot investigate this issue.😞

**Comment by hiroppy** [comment]
Is is better to change lint ci from linux to windows if possible?

**Comment by evilebottnawi** [comment]
Linux is faster than windows so better use Linux for this

**Comment by evilebottnawi** [comment]
For me all works fine on Windows, Linux and Mac OS with single quotes, let's close this PR, no need this change

**Comment by Loonride** [comment]
This change makes the npm scripts actually work for me. I'm on Windows 7. Maybe it is different on other Windows versions, or different shells, but I tried 3 shells and it failed with single quotes on all of them. There is lots of evidence that it is a problem for other Windows users:

https://github.com/mikeal/watch/issues/109#issuecomment-228466730
https://github.com/prettier/prettier/issues/4561#issuecomment-392817015
https://github.com/prettier/prettier/issues/4804#issuecomment-402476898

**Comment by evilebottnawi** [comment]
It is only with prettier?

**Comment by evilebottnawi** [comment]
oh looks you are right

**Pull request merged**
