### PR TITLE
fix(tests): minor fix for transportMode.client test case

### PR DESCRIPTION
**Pull request by jamesgeorge007**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
N/A

### Motivation / Use-Case
There was a slight typo in #2116 that got unnoticed.

### Breaking Changes
N/A

### Additional Info
 N/A

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @evilebottnawi

**Comment by jamesgeorge007** [comment]
@hiroppy I guess you mean that it should be refactored to be:-
```js
options.transportMode: {
  client: 'sockjs'
}
```
:thinking:

**Comment by jamesgeorge007** [comment]
@hiroppy didn't get you :thinking:

**Comment by hiroppy** [comment]
https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/normalizeOptions.js#L20-L25

**Comment by jamesgeorge007** [comment]
@hiroppy so how should the respective case be instead :question:

**Comment by jamesgeorge007** [comment]
```js
options: {
  transportMode.client: 'sockjs'
}
```
Is this the required way :thinking:

**Comment by hiroppy** [comment]
Why do you introduce this change? 

We must add these cases.

string: transportMode: 'sockjs', 'ws'
object: transportMode.server, transportMode.client

And we've alerady had enough test cases.

**Comment by jamesgeorge007** [comment]
I assumed this from the diff (#2116) such that the change was specific to `clientMode` (transportMode.client)

**Comment by jamesgeorge007** [comment]
As seen from the test-case it is something specific to `transportMode client`:-
https://github.com/Loonride/webpack-dev-server/blob/aa17f7ca58eb3bd97a097f4901b58295acbe7334/test/e2e/TransportMode.test.js#L12-18

**Comment by jamesgeorge007** [comment]
@hiroppy So this PR doesn't make any sense at all :thinking:

**Comment by jamesgeorge007** [comment]
@evilebottnawi thoughts :thinking:

**Comment by evilebottnawi** [comment]
@jamesblight what is problem here?

We support, `transportMode: 'ws` and `transportMode: { client: 'ws' , `server`: 'ws'}`?

**Comment by jamesgeorge007** [comment]
@evilebottnawi as per what I see, the test was specific for `transportMode client` [here](https://github.com/Loonride/webpack-dev-server/blob/aa17f7ca58eb3bd97a097f4901b58295acbe7334/test/e2e/TransportMode.test.js#L12-19) 
As evident from the diff, the respective test case was specific to `options.clientMode` which should be set to `transportMode.client` right :thinking: 
Screenshot from 2019-08-09 15-47-41
Instead, the entire `transportMode` object was being set.

**Comment by jamesgeorge007** [comment]
> @jamesblight what is problem here?
wrong user mentioned :sweat_smile:

**Comment by jamesgeorge007** [comment]
> @jamesblight what is problem here?

wrong user mentioned :sweat_smile:

**Comment by evilebottnawi** [comment]
I think test is right here

**Comment by jamesgeorge007** [comment]
@evilebottnawi @hiroppy 
```js
options: {
  clientMode: 'sockjs'
}
```
was updated to be:-
```js
options: {
  transportMode: 'sockjs'
}
```
As per what I infer, instead of having `clientMode` and `serverMode` #2116 introduced `transportMode` as:-
```js
transportMode: {
  client: '',
  'server: ''
}
```

Hence, `options.transportMode.client` should be an equivalent of `options.clientMode` right :thinking:
Instead the respective case made use of just `options.transportMode` which made me confused :confused:

**Comment by jamesgeorge007** [comment]
Apologies for the trouble here. Kindly correct if I'm wrong :pray:

**Comment by jamesgeorge007** [comment]
Apologies for the trouble here. Kindly correct me if I'm wrong :pray:

**Comment by evilebottnawi** [comment]
`options.clientMode` and `options.serverMode` were removed, now only `transportMode` option

**Comment by jamesgeorge007** [comment]
Even `transportMode` comprises of `client` and `server` entries right?

**Comment by evilebottnawi** [comment]
@jamesgeorge007 yes, you can set `transportMode: { client: myImplementation, server: 'ws}` for example

**Comment by Loonride** [comment]
@jamesgeorge007 

When we just had:

```
options: {
  clientMode: 'sockjs'
}
```

We were relying on the fact that the default serverMode was also `sockjs`, so that server and client could communicate. This is still the case, but in the future, the default mode will be changed to `ws`.

This is better, because it specifies both the client and server modes explicitly:

```
options: {
  transportMode: 'sockjs'
}
```

since it is equivalent to:

```
options: {
  transportMode: {
    client: 'sockjs',
    server: 'sockjs'
  }
}
```

**Pull request closed without merging**
