### PR TITLE
feat: add webpack as argument to before and after options

### PR DESCRIPTION
**Pull request by evilebottnawi**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

Allow to get information from webpack in `before` and `after`

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Comment by hiroppy** [comment]
Which do you prefer modifying webpack-dev-server's eslint config or eslint-config-webpack?

**Comment by evilebottnawi** [comment]
@hiroppy `eslint-config-webpack` https://github.com/webpack-contrib/eslint-config-webpack

**Comment by hiroppy** [comment]
@evilebottnawi eslint-config-prettier overwrite this rule.

I found that eslint-config-prettier was overriding the rules.(curly: off)

So, we have to change the order https://github.com/webpack/webpack-dev-server/blob/master/.eslintrc#L2 or write this rule to webpack-dev-server's eslintrc.

**Comment by evilebottnawi** [comment]
hm, it is strange, need investigate why prettier disable `curly`, because prettier don't add `{` and `}`

**Comment by hiroppy** [comment]
eslint-config-prettier set 0 😞

https://github.com/prettier/eslint-config-prettier/blob/dd8511b107e5adaaa107a2f8d83d9298018e895b/index.js#L9

**Comment by evilebottnawi** [comment]
@hiroppy https://github.com/prettier/eslint-config-prettier/blob/dd8511b107e5adaaa107a2f8d83d9298018e895b/README.md#curly, we need change order, yep

**Comment by hiroppy** [comment]
Yeah, but we are setting `"extends": ["webpack", "prettier"]` now, so the setting of eslint-config-webpack is overwritten because the setting of curly is written in eslint-config-prettier

**Comment by evilebottnawi** [comment]
@hiroppy we need fix :+1:

**Comment by hiroppy** [comment]
@evilebottnawi for now, I created #1761.

**Pull request merged**
