### PR TITLE
Fix check for webpack/hot/log when setting HMR log level

### PR DESCRIPTION
**Pull request by lbogdan**
**What kind of change does this PR introduce?**
Bugfix.

**Did you add or update the `examples/`?**
Not needed.

**Summary**
Some time ago I authored [PR #926](https://github.com/webpack/webpack-dev-server/pull/926). Which, strangely enough, caused [issue #1049](https://github.com/webpack/webpack-dev-server/issues/1049).

The original code was
```js
  var hotCtx = require.context("webpack/hot", false, /^\.\/log$/);
  if(hotCtx.keys().length > 0) {
    hotCtx("./log").setLogLevel(level);
  }
```
Somehow I was under the impression that `hotCtx.keys()` can only return `[]` or `["./log"]`, and with this assumption, the check `hotCtx.keys().length > 0` is correct. For some strange reason, as per issue #1049, it returned `["../package.json", "./console", "./formatters"]`, which doesn't match the regex at all, so I don't really know what happened there. In this case, of course, the check becomes wrong.

Now, this is the fix for #1049 in [PR #1050](https://github.com/webpack/webpack-dev-server/pull/1050)
```js
  if(hotCtx.keys().length > 0) {
    var contextKeys = hotCtx.keys();
    if(contextKeys.length && contextKeys["./log"]) {
      ...
```
which doesn't work, because `contextKeys` is an array, so `contextKeys["./log"]` will always be `false`.

So the correct check would be `if (hotCtx.keys().indexOf('./log') !== -1) { ...`.

**Does this PR introduce a breaking change?**
No.

### CODE REVIEW

**Comment by lbogdan** [comment]
Cc @johan-lejdung.

**Comment by johan-lejdung** [comment]
Ah damn, of course it's an array.. Don't know what I was thinking :)  If I could, I would approve this change!

The build seems to fail, but not related to this file. There seem to be a linting error in Server.js:

```
/home/travis/build/webpack/webpack-dev-server/lib/Server.js
  142:17  error  Strings must use singlequote  quotes
✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.
```

**Comment by lbogdan** [comment]
What's even stranger is that it fails only on node 6 and 4, 8 is ok. :smile:

**Comment by johan-lejdung** [comment]
Quickly looked through the changelog for node 8 and there were a lot of Array changes, maybe they allow such access now.

**Comment by lbogdan** [comment]
That's an eslint error, so I don't see any reason why it would work differently in node 8 vs. node 4 or 6. Anyway, fixed it in https://github.com/webpack/webpack-dev-server/pull/1098.

**Comment by lbogdan** [comment]
Any news on this?

**Comment by shellscape** [comment]
@lbogdan you're a rock star for getting these fixes in. very much appreciated! but I beg of you some additional patience please 😄  we're all human on this side, and to say the last two weeks have been personally trying would be an understatement. please note that it may take a week or so to get a patch release out. I'll be out of town and I don't like to release unless I'm around to put out any fires that pop up.

**Comment by lbogdan** [comment]
@shellscape Thank you for your kind words, they might not necessarily reflect the reality! :smile:
That was just a follow up, sorry if I came off as impatient, I was just curious about an update. I know OSS is made out of people's personal time, and I really appreciate these people and their hard work!

**Pull request merged**
