### PR TITLE
chore(deps): update dev dependencies

### PR DESCRIPTION
**Pull request by GChuf**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### Motivation / Use-Case

updates dev dependencies, fixes 5 high vulnerabilities

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I hate flacky tests, I will fix it in near future

**Comment by hiroppy** [comment]
No flacky, currently, npm is down.

**Comment by GChuf** [comment]
Can you run the tests again?

**Comment by GChuf** [comment]
@hiroppy it was a mistake, i noticed it too. it should be fixed now

**Comment by GChuf** [comment]
I tried to include watchpack 1.7. but the tests reported that 'fsevents.watch is not a function'. So I reverted back to 1.6.
It would be good to fix that, because newer watchpack uses chokidar v3 instead of chokidar v2.

**Pull request merged**
