### PR TITLE
Update dependencies in V2 branch, fix compatibility with Node 10

### PR DESCRIPTION
**Pull request by Volune**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Updated travis.yml to test Node 10

### Motivation / Use-Case

`webpack-dev-server` 2 depends on an older version of `spdy` which is not compatible with Node 10.
See spdy-http2/handle-thing#5

I updated other dependencies with `npm audit fix` at the same time, it should fix a few vulnerabilities.

Don't know if you still maintain the v2 branch.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy some projects like ruby-rails stull use old version, we should fixes only compatibility/security issue when we release `v4` we official stop supporting `v2` branch, so we can merge this and release as patch

**Comment by hiroppy** [comment]
Oh, I did not know. OK, I'll review this pr.

**Comment by ujenjt** [comment]
Hey, we also use v2 branch, so it would be great to have this fixes in next v2 versions.

**Comment by evilebottnawi** [comment]
@ujenjt can you test this PR manually?

**Comment by ujenjt** [comment]
> @ujenjt can you test this PR manually?

Sure. I can test this PR with several projects which use `webpack-dev-server` v2 and check if it works. What kind of test do you want me to do? Any advice how to test better?

**Comment by evilebottnawi** [comment]
@ujenjt nothing unusual just run and do what you usually do when developing

**Comment by ujenjt** [comment]
Just tested `git://github.com/Volune/webpack-dev-server.git#v2-dependencies` version with my webpack config - it works ok for me both with node `v10.15.3` and `v8.11.3`.

**Comment by hiroppy** [comment]
@ujenjt Thank you for creating test repo!

**Comment by ujenjt** [comment]
Hey, thanks a lot for merging this to v2 branch. When we can expect this has been published to npm?

**Comment by evilebottnawi** [comment]
@ujenjt ~24 hours

**Pull request merged**
