### PR TITLE
fix: Changed this.options.info to this.logger.info

### PR DESCRIPTION
**Pull request by Xrumet**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No tests so far

### Motivation / Use-Case

Cannot run dev server because of exception

### Breaking Changes

No breaking change I think

### CODE REVIEW

**Comment by Xrumet** [comment]
Hi, @alexander-akait may you take a look on this PR and pickup/cherry pick this commit if it valid (I am not sure, but checked it and it works for me)

**Comment by alexander-akait** [comment]
We need to add tests, I will look how to fix it

**Comment by Xrumet** [comment]
Thanks! I appreciate it!...

**Comment by Xrumet** [comment]
Created new PR to pass "commit message" check. Please see: #2910

**Pull request closed without merging**
