### PR TITLE
Backport support for configuration as Promise in Webpack v1

### PR DESCRIPTION
**Pull request by mathieumg**
**What kind of change does this PR introduce?**
- [x] Bugfix

**Does this PR introduce a breaking change?**
- [x] No

**Other information**:

Backports the fix in #419 to webpack-dev-server v1 since v1 of Webpack itself supports config as Promise. Change looks more complex than it really is, it's just because a lot of code is getting wrapped in a function.

### CODE REVIEW

**Comment by mathieumg** [comment]
@SpaceK33z It's been a month today, I don't mean to be impatient but would it be possible to take a look at this? It's essentially a two-liner that is already in Webpack 1, just need to have it in the dev server as well. Thanks!

**Comment by SpaceK33z** [comment]
@mathieumg Honestly I wasn't planning on doing another v1 release, since v2 is right around the corner and now we're in release candidate already. However, if I have the time this weekend I'll see if I can do another v1 release.

**Comment by mathieumg** [comment]
Cool, thanks for the information. That would be appreciated to "close the book" on v1. Like I said, it's cool that the Promise config was backported from v2 to v1, it's just impractical to use it since it wasn't backported to the dev server at the same time. Thanks!

**Comment by mathieumg** [comment]
@SpaceK33z Sorry to bother you, do you think it would be possible to merge this? It seems to be the last v1 PR still open. Thanks a lot!

**Comment by SpaceK33z** [comment]
No, I'm sorry. I have been closing webpack 1 specific PR's for a while. webpack 2 is released now and we'll only focus on critical bugfixes in v1.

**Comment by SpaceK33z** [comment]
Oh I kinda forgot that this was a bugfix not a feature. I'll see if I have some time later today.

**Comment by SpaceK33z** [comment]
np, released as `webpack-dev-server@1.16.3`. Sorry for the long waiting time.

**Comment by richtera** [comment]
:+1: Works

**Pull request merged**
