### PR TITLE
chore(deps): update package-lock.json

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

run `audit fix`.

```

>= 4.17.12

├─┬ @commitlint/cli@8.0.0
│ ├─┬ @commitlint/lint@8.0.0
│ │ ├─┬ @commitlint/parse@8.0.0
│ │ │ ├─┬ conventional-commits-parser@2.1.7
│ │ │ │ └── lodash@4.17.14  deduped
│ │ │ └── lodash@4.17.14  deduped
│ │ ├─┬ @commitlint/rules@8.0.0
│ │ │ └─┬ @commitlint/ensure@8.0.0
│ │ │   └── lodash@4.17.11 
│ │ └── lodash@4.17.11 
│ ├─┬ @commitlint/load@8.0.0
│ │ ├─┬ @commitlint/resolve-extends@8.0.0
│ │ │ └── lodash@4.17.11 
│ │ └── lodash@4.17.11 
│ └── lodash@4.17.11 
```

These PRs have merged but they haven't published new version yet, so we cannot fix.(because they lock lodash's version)
https://github.com/conventional-changelog/commitlint/commit/4cb979df81328684467fd0dad130440ce725831d
https://github.com/conventional-changelog/commitlint/pull/724

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
commitlint still have problem :confused:

**Comment by evilebottnawi** [comment]
Try to full remove package-lock and install again package with new package-lock

**Comment by hiroppy** [comment]
wow, good timing. updated.

**Pull request merged**
