### PR TITLE
explicit hot when hotOnly in options.

### PR DESCRIPTION
**Pull request by arjunkathuria**
### What kind of change does this PR introduce?
bugfix / refactor confusing behaviour

### Did you add or update the examples/?
No.

### Summary

When `hot-only` option is supplied, the `hot` option also needs to be set to true for the `hot-only` option to work as intended which for some users, creates confusion. 

This PR removes the need to turn both `hot` AND `hot-only` on for devServer, when specifying hot-only as it sets hot to true internally for the user.  

### Does this PR introduce a breaking change?
No.

### Other information
cc- @shellscape, were we looking for something like this ?

### CODE REVIEW

**Comment by shellscape** [comment]
@arjunkathuria thanks for taking the time to put this together. please note that pull request templates typically aren't optional and it's generally not considered good form to remove their content. please edit the PR description using the template (https://github.com/webpack/webpack-dev-server/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and we'll have a look at the PR afterward :)

**Comment by arjunkathuria** [comment]
@shellscape updated.

**Comment by shellscape** [comment]
@arjunkathuria thanks

I'm looking at [Server.js#L39](https://github.com/webpack/webpack-dev-server/blob/da188a6359b372d7885bde1fe204b5b835ff3466/lib/Server.js#L39) and [addDevServerEntrypoints.js#L9](https://github.com/webpack/webpack-dev-server/blob/85de417fd5592efc5448758bf550d7d34e670f60/lib/util/addDevServerEntrypoints.js#L9) and within webpack-dev-server there seems to be an explicit difference between the two. Overriding the value of `options.hot` doesn't seem wise, as it'll execute code the user may not have wanted. It could also be considered a breaking change.

According to [this comment](https://github.com/webpack/webpack-dev-server/issues/877#issuecomment-310925554) the real issue lies within webpack itself. Given all of this, it seems that there are two fairly clear solutions that lie outside of webpack-dev-server;

1. add `HotModuleReplacementPlugin` manually
2. file a pull request with the [main webpack repo](https://github.com/webpack/webpack/) to account for the `hot-only` command line arg with regard to injection of `HotModuleReplacementPlugin`

But it doesn't look like the best solution is going to be in this project.

**Comment by arjunkathuria** [comment]
hupmh, alright, guess we could close this then ?

**Comment by shellscape** [comment]
Sure, can do. If you find more info that suggests the solution should live here, we can reopen.

**Pull request closed without merging**
