### PR TITLE
Refactor test

### PR DESCRIPTION
**Pull request by alexander-akait**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

here tests

### Motivation / Use-Case

refactor all test so CI should be stable green now

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Comment by alexander-akait** [comment]
Some tests freeze :confused: keeping investigation...

**Review by anshumanv — APPROVED** [review]

**Comment by alexander-akait** [comment]
Freeze only on webpack v4, investigating

**Comment by alexander-akait** [comment]
Great :tada:

**Comment by alexander-akait** [comment]
Also tests are faster, I will remove more `setTimeout`/`setInterval` and we will faster more

**Pull request merged**
