### PR TITLE
Union sock options

### PR DESCRIPTION
**Pull request by EslamHiko**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Used existing tests

### Motivation / Use-Case
It's in the To Do list

### Breaking Changes
Using sockHost, sockPath and sockPort options will be invalid. they must be used in the new clientSocketOptions option.

### CODE REVIEW

**Comment by hiroppy** [comment]
@EslamHiko If you want to change something(e.g. add new feature, breaking changes, etc...), please submit an issue because we need to discuss before implementation. Thanks.

**Comment by evilebottnawi** [comment]
Yes, we should do this for next branch, also we still need discussion how handle CLI arguments for this

**Comment by EslamHiko** [comment]
@evilebottnawi I'll change the base branch to next, and for CLI arguments I handled them in lib/utils/createConfig.js

**Comment by EslamHiko** [comment]
@hiroppy @evilebottnawi Sorry I accidentally merged this PR into next branch. shoud I revert or is it ok?

**Pull request merged**
