### PR TITLE
ported fix for #612 to 1.x

### PR DESCRIPTION
**Pull request by skwakman**
**Please check if the PR fulfills these requirements**
- [ ] An example has been added or updated in `examples/` (for features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
See #612 

**What is the new behavior?**

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the following... 

* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

**Comment by skwakman** [comment]
Thanks for the merge. Any idea on when 1.x gets a new release?

**Comment by SpaceK33z** [comment]
My plan was to wait a bit to see if there were other bugs for 1.x (don't want to do too many releases), but if there's nothing in a week I'll release a new version.

**Comment by skwakman** [comment]
Ah ok, I'll wait for it then. Thanks!

**Comment by skwakman** [comment]
@SpaceK33z perhaps it's time for a release?

**Comment by SpaceK33z** [comment]
@skwakman, done, `1.16.2`.

**Pull request merged**
