### PR TITLE
feat/addSockPath

### PR DESCRIPTION
**Pull request by zhangyuang**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
in cli.test.js

### Motivation / Use-Case

make up sockPath argv

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Thanks for PR.

/cc @hiroppy

**Comment by hiroppy** [comment]
We should add a description.
https://webpack.js.org/configuration/dev-server/#devserversockpath

Could you submit a pr to https://github.com/webpack/webpack.js.org ?

**Comment by hiroppy** [comment]
Thanks!

**Comment by zhangyuang** [comment]
> We should add a description.
> https://webpack.js.org/configuration/dev-server/#devserversockpath
> 
> Could you submit a pr to https://github.com/webpack/webpack.js.org ?

ok，it's my honor

**Comment by sheldonh** [comment]
Can't wait to see this released.

**Pull request merged**
