### PR TITLE
feat(addDevServerEntryPoints): exclude client scripts for`node` targets

### LINKED ISSUE #1256: webpack Multiple Targets
### Code

```js
// webpack.config.js
module.exports = [
  {
    entry : {
      app: './src/app'
    },
    output: {
      path: path.resolve(__dirname, 'dist/')
      filename: 'assets/js/app.js',
      chunkFilename: `assets/js/${getAssetName('[hash]', '[name]')}.js`
    },
    devServer: {
      hot: true
    }
  },
  {
    entry : {
      app: './src/app.server'
    },
    output: {
      path: path.resolve(__dirname, 'dist/server')
      filename: 'app.js',
      chunkFilename: '[name].js',
      libraryTarget: 'commonjs2'
    },
    target: 'node'
  }
];
```
### Run
```shell
npx webpack-dev-server
```

### Expected Behavior
- ~~_The client app entry add `webpack/hot/only-dev-server` `webpack/hot/dev-server` etc._~~
- The client app entry add https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js file, from at line: https://github.com/webpack/webpack-dev-server/blob/master/lib/util/addDevServerEntrypoints.js#L23
- The server app entry no add.

### Actual Behavior
All added.

### For Bugs; How can we reproduce the behavior?
Example edit: https://github.com/webpack/webpack-dev-server/blob/master/lib/util/addDevServerEntrypoints.js#L22
```diff
    [].concat(webpackOptions).forEach((wpOpt) => {
+     if (wpOpt.target === 'node') return;
      if (typeof wpOpt.entry === 'object' && !Array.isArray(wpOpt.entry)) {
        Object.keys(wpOpt.entry).forEach((key) => {
          wpOpt.entry[key] = devClient.concat(wpOpt.entry[key]);
        });
      } else if (typeof wpOpt.entry === 'function') {
        wpOpt.entry = wpOpt.entry(devClient);
      } else {
        wpOpt.entry = devClient.concat(wpOpt.entry);
      }
    });
```

### For Features; What is the motivation and/or use-case for the feature?
server side rendering

### PR DESCRIPTION
**Pull request by sanonz**
### Type 

- [x] Feature

### Issues

- Fixes #1256 
- Fixes #1441

### SemVer

- [x] Minor

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@sanonz Are you still interested in eventually continuing this PR ?

**Comment by sanonz** [comment]
What else do I need to do?

**Comment by sanonz** [comment]
It's ok?

**Comment by evilebottnawi** [comment]
@sanonz Yes

**Comment by jojo-apollo** [comment]
Any idea when this will be resolved? It's currently breaking my build.

**Comment by evilebottnawi** [comment]
Need rebase, CI failed

@jojo-apollo feel free to recreate the PR

**Comment by jojo-apollo** [comment]
Yup, if he isn't able to reply soon, I'll probably just rebase this PR and move on.

**Comment by hiroppy** [comment]
@sanonz Could you rebase?

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/1775

**Pull request closed without merging**
