### PR TITLE
chore(renovate): add rangeStrategy: bump

### PR DESCRIPTION
**Pull request by hiroppy**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

no

### Motivation / Use-Case

fixes: #1882

### Breaking Changes

no

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy let's unpin all dev dependencies (adding `^`)

**Comment by hiroppy** [comment]
fixed

**Comment by hiroppy** [comment]
rebased

**Comment by hiroppy** [comment]
@evilebottnawi review plz

**Pull request merged**
