### PR TITLE
test: fix RegExp

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
already present

### Motivation / Use-Case
fix snapshot issue

### Breaking Changes
None

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Hope it will fix the problem with CI

**Comment by alexander-akait** [comment]
macos is very slow :disappointed:

**Review by alexander-akait — APPROVED** [review]

**Comment by snitin315** [comment]
All green 💯

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Comment by snitin315** [comment]
@alexander-akait can you share the roadmap ?

**Comment by alexander-akait** [comment]
@snitin315 I don't have strong roadmap right now, but I can do it tomorrow, right now we need fix it https://github.com/webpack/webpack-dev-server/pull/2920/, PR is solved, but we need rewrite test, I can give invite your and can can finish tests in my PR, thanks again

**Comment by snitin315** [comment]
Sounds good 👍🏻 . Please send the invite.

**Comment by alexander-akait** [comment]
You are part of `webpack-dev-server` and `webpack-dev-middleware` repos, so you can finish my PR, thanks

**Pull request merged**
