### PR TITLE
docs: add `--web-socket-server`

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

yes

### Motivation / Use-Case

Add `--web-socket-server`.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Review by anshumanv — COMMENTED** [review]
Can add some examples

**Comment by alexander-akait** [comment]
Yep, or fix exiting example(s)

**Comment by snitin315** [comment]
I will update 👍🏻

**Comment by snitin315** [comment]
Done ✅

**Comment by alexander-akait** [comment]
Let's improve this, ideally we should use to get all arguments, but because we supported webpack v4, we need specify them, let's add test for this, fix schema and add necessary args:

```
const webpack = require('webpack');
const schema = require('./lib/options');

console.log(webpack.cli.getArguments(schema))
```

**Comment by alexander-akait** [comment]
Here fix for schema https://github.com/webpack/webpack-dev-server/pull/3315, feel free to merge when it will be green and improve CLI args (should be easy)

**Comment by snitin315** [comment]
I think we can introduce the following in public API -

- `Server.getCliArguments()` - return all cli-flgs, 
- `Server.processArgs(args, config, values)` - process args via `webpack.cli.processArguments(args, config, values)` .

Then use these in `webpack-cli`, and we can get rid of `cli-flags.js` in v5.

**Comment by alexander-akait** [comment]
@snitin315 Yes, this is the right direction, but we still support v4, so we don't have this API, we will implement it in the next major release, now I think we can copy paste them in our flags and add tests to ensure we nothing missing

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
