### PR TITLE
Fix issue #1316

### PR DESCRIPTION
**Pull request by JayAndCatchFire**
- [x] This is a **bugfix**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **typo fix**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
I did not.  I absolutely want to, but it appears that the `client-src/default/index.js` file has no tests at the moment.  Or if it does, I couldn't find them in the `test` directory.

I would really love some help and/or guidance on how best to test this code.

### Motivation / Use-Case
See #1316 for the bug this addresses.

### Breaking Changes
There's a _possibility_ that this could cause unnecessary reloads in other situations.  I don't think it will, but I'm not 100% sure it won't, especially since this bit of code doesn't seem to have any tests right now.

### CODE REVIEW

**Comment by JayAndCatchFire** [comment]
What's going on with travis-ci?  It's been stuck in yellow dot status for 15 hours.

**Comment by JayAndCatchFire** [comment]
@sokra @shellscape @SpaceK33z Can someone please give travis-ci a kick?  It's been stalled for 2 days.

**Comment by SpaceK33z** [comment]
Looking into this PR right now.

**Comment by SpaceK33z** [comment]
I don't know what is going on with Travis but I'm going to merge this since I confirmed it works locally.

Thanks again @JayAndCatchFire!

**Pull request merged**
