### PR TITLE
V4

### PR DESCRIPTION
**Pull request by hiroppy**
- [x] This is a **bugfix**
- [x] This is a **feature**
- [x] This is a **code refactor**
- [x] This is a **test update**
- [x] This is a **docs update**
- [x] This is a **metadata update**

## Breaking Changes 

- Drop Node@6,8 so the minimum version is Node@10
- `hot` enabled by default
- The default `transportMode` is switched from `sockjs` to `ws`
- Remove `hotOnly` and `hot` accepts `boolean` and `only`
- Remove `before`, `after`, and `setup` and add `onBeforeSetupMiddleware` and `onAfterSetupMiddleware`
- Remove `key`, `cert`, `pfx`, `pfx-passphrase`, and `requestCert` from CLI and webapck.config.js
  - for the next version, please use `https.{key|cert|pfx|passphrase|requestCert}`
  - see https://webpack.js.org/configuration/dev-server/#devserverhttps
- Remove `inline` and `iframe/live mode`
- Remove `lazy` and `filename` 
- Remove `features` 
- Delete some internal options variables, so please use `this.options.xxx`
- The `log`, `logLevel`, `logTime`, `noInfo`, `quiet`, `reporter` and `warn` options were removed in favor of built-in webpack logger, please use https://webpack.js.org/configuration/other-options/#infrastructurelogginglevel to enable and set up logging output
- the `hot` value prefers the CLI `--hot` flag over the configuration `hot` option - it is a fix
- rename `clientOptions` to `client`
- Remove `fs`, `index`, `mimeTypes`, `publicPath`, `serverSideRender`, and `writeToDisk` in favor of `dev` option for any `webpack-dev-middleware` configuration
- Upgrade `webpack-dev-middleware` to `v4`, which includes many breaking options changes
- Remove `stats` option and `color` CLI flag in favor of webpack `stats` option
- Remove `socket` option
- Remove `contentBase`, `contentBasePublicPath`, `serveIndex`, `staticOptions`, `watchContentBase`, `watchOptions` in favor of `static`
- Minor `createConfig` util API changes
- `disableHostCheck` and `allowedHosts` removed in favor of `firewall`
- Yes, the client uses the port of the current location (location.port, equivalent to sockPort: 'location'), by default. To get existing behavior, set the client.port with the port you'd like to set to, e.g.:
- Added setupExitSignals option. Takes a boolean and if true (default on CLI), the server will close and exit the process on SIGINT and SIGTERM
- server.listen() will find free port if this.options.port is not set and port argument is not passed
- Print a warning if options.port and port passed as an argument is different
- Added CLI calling webpack serve.
- server.listen() now returns a Promise, which will resolve to server.listeningApp, after finding the free port.
- bin/options.js is removed.
- profile (--profile) option is removed, to print profile data, set progress: 'profile' (--progress profile).
- progress (--progress) option is moved to client, set client: {progress: true} (--client-progress).
- Yes, the client uses the hostname of the current location (location.hostname), by default. To get existing behavior, set the client.host with the hostname you'd like to set to, e.g.: const server = new Server(compiler, { client: { host: hostname, } }); server.listen(port, hostname);
- sockHost, sockPath and sockPort options were removed in favor the client option (#2593)
- cacert CLI option and ca option are removed and moved to https.ca (#2564)

### Fixes

fix(client): use location protocol on ipv6 any (::) host (#2868)

### For Bugs and Features; did you add new tests?

Yep

### Motivation / Use-Case

We decided to release a new version as V4.

### Breaking Changes

Yep

### Additional Info

**DON'T USE SQUASH AND MERGE**

### CODE REVIEW

**Comment by hiroppy** [comment]
Lint CI will fail because `BREAKING CHANGE` prefix doesn't recognize.

**Comment by Loonride** [comment]
@hiroppy https://github.com/webpack/webpack-dev-server/pull/2593

**Comment by dannyphillips** [comment]
Any updates on when this will be released?

**Comment by evilebottnawi** [comment]
@dannyphillips next week, I am working on webpack-dev-middleware major release

**Comment by piecyk** [comment]
> I am working on webpack-dev-middleware major release

@evilebottnawi ping me if there is anything i can help 👍

**Comment by evilebottnawi** [comment]
@piecyk yes, this issue on my top

**Comment by gandhiamarnadh** [comment]
Any updated time line for the release ?

**Comment by evilebottnawi** [comment]
@gandhiamarnadh hope this week

**Comment by hiroppy** [comment]
@alexander-akait Yes! GoGo!

**Comment by alexander-akait** [comment]
@hiroppy yep, I will do it today :+1:

**Comment by ylemkimon** [comment]
Two missing breaking changes:
- `sockHost`, `sockPath` and `sockPort` options were removed in favor the `client` option (#2593)
- `cacert` CLI option and `ca` option are removed and moved to `https.ca` (#2564)

**Comment by alexander-akait** [comment]
@ylemkimon thanks, I will check every PR to when write CHANGELOG to make sure we haven't missed anything

**Comment by alexander-akait** [comment]
Time to release `webpack-dev-server@4-beta.0`, WIP on CHANGELOG

**Comment by ylemkimon** [comment]
I think this should have been merged via a merge commit or rebase merging.

**Comment by alexander-akait** [comment]
@ylemkimon yes, you are right here, but we have very dirtly commit history here, so I prefer to squash it, we will avoid it in future

**Comment by alexander-akait** [comment]
Found strange thing with our client, we loaded not bundled client, WIP on this

**Comment by alexander-akait** [comment]
Yes we have a bug, not easy to fix, so I am doing release and try to fix it tomorrow, we should use `index.bundle.js` from `client/default/`

**Comment by alexander-akait** [comment]
Also found bug we write `stats` in `process.stderr` in `webpack-dev-middleware`, but should use `process.stdout`

**Comment by alexander-akait** [comment]
@ylemkimon https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0, maybe you can help us more?
Found bugs:
- we should use index.bundle.js from client/default/, now we use `index.js`
- we write stats in process.stderr in webpack-dev-middleware, but we should use process.stdout
- `publicPath` can be `'auto'` or `''`, we need fix logging https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/status.js#L9 `typeof publicPath !== "undefined"`

**Comment by ylemkimon** [comment]
@alexander-akait I've tested the beta in one of my projects and it works nicely. Thank you for the great work! I currently don't have much time but will try.

> we write stats in process.stderr in webpack-dev-middleware, but we should use process.stdout

Doesn't dev-server and middleware use webpack's InfrastructureLogger?

**Comment by alexander-akait** [comment]
> Doesn't dev-server and middleware use webpack's InfrastructureLogger?

yes, but for stats, we should not use logger, because logger always use stderr (diagnostic)

**Pull request merged**
