### PR TITLE
refactor: added additional entries helper

### LINKED ISSUE #3698: [Docs]: This migration-v4.md doc not have a change logs for addDevServerEntrypoints
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

### PR DESCRIPTION
**Pull request by alexander-akait**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [x] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

fix #3698 + refactor our code for plugin support

### Breaking Changes

No

### Additional Info

I think it is the last refactor before implement plugin support

### CODE REVIEW

**Comment by alexander-akait** [comment]
@snitin315 @anshumanv We should fix our docs here https://webpack.js.org/guides/hot-module-replacement/, example in migration guide

**Comment by alexander-akait** [comment]
I decide do not add new API, because it is have some limitations and edge cases, better to do it manually, also added small example

**Comment by snitin315** [comment]
> @snitin315 @anshumanv We should fix our docs here https://webpack.js.org/guides/hot-module-replacement/, example in migration guide

I will update 👍

**Comment by snitin315** [comment]
https://github.com/webpack/webpack.js.org/pull/5353

**Pull request merged**
