### PR TITLE
fix(Server): don't use `spdy` on `node >= v10.0.0` 

### PR DESCRIPTION
**Pull request by addaleax**
- [x] This is a **bugfix**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **typo fix**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

This does add Node 10 to the test matrix. There do not seem to be any existing tests for `https://` support, though, so I added one, even though it does not function as a regression test (one would actually have to explicitly use spdy/http2 for that).

### Motivation / Use-Case

This fixes the bug reported at:

- https://github.com/nodejs/node/issues/21665
- https://github.com/webpack/webpack-dev-server/issues/1449

### Breaking Changes

This should not affect any user agents that detect protocol support themselves (like they should), in particular not browsers.

### Additional Info

Another option that was considered was reverting the change that led to this in Node 10.

However, the `spdy` module is built in a very fragile manner, and unfortunately it seems unreasonable to expect that anything we can do inside of Node would be more than a stop-gap solution.

(See e.g. https://github.com/spdy-http2/node-spdy/issues/333 for an attempt to reach out to the `spdy` maintainers about this problematic.)

### CODE REVIEW

**Comment by addaleax** [comment]
Updated the test with an increased timeout because of the on-the-fly key generation.

**Comment by Kovensky** [comment]
Unfortunately, just changing the module to http2 won't work because of https://github.com/expressjs/express/issues/3388

Express doesn't seem to actually use node's request/response stuff but uses custom ones which are then `setPrototypeOf` to the node versions, and because of that it actually will not work correctly and crashes as soon as an h2 request happens.

**Comment by addaleax** [comment]
@Kovensky Without having looked into it deeper, from https://github.com/expressjs/express/pull/3390#issuecomment-408646774 and below, it looks like there might be some movement in that area? :)

**Comment by addaleax** [comment]
Btw, are the recommendations for trying out pull requests in the CONTRIBUTING.md accurate? See e.g. https://github.com/nodejs/node/issues/21665#issuecomment-410003250

**Comment by leup** [comment]
Any news on this one ?

**Comment by michael-ciniawsky** [comment]
I think this is definitely blocked by https://github.com/nodejs/node/issues/21665 and https://github.com/expressjs/express/issues/3388 atm

**Comment by addaleax** [comment]
> I think this is definitely blocked by nodejs/node#21665 and expressjs/express#3388 atm

@michael-ciniawsky I’m not sure if I’m understanding you correctly, but *this PR* is not blocked on either of these issues. It fixes the first one, and the second one is just something to keep in mind for the future (fully migrating from SPDY to the built-in HTTP/2 module in Node would be dependent on it being solved).

What this PR *may* be blocked on is this issue, reported by somebody who tried this code out: https://github.com/nodejs/node/issues/21665#issuecomment-410208986

I don’t know enough about webpack-dev-server to figure out whether that issue is actually related, and if so, in what way. (And as @Kovensky said, automated testing is hard here & I’m not sure how to do it well.)

**Comment by michael-ciniawsky** [comment]
Should we better remove the dependency on `spdy` entirely ? 🙃 It doesn't seemed to be promoted for `http/2` explicitly nor is there an option to enable `http2`, so we may get away with that :D

**Comment by michael-ciniawsky** [comment]
Released in [`v3.1.7`](https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.7) 🎉

**Comment by avocadee** [comment]
Can we cherry-pick this fix to the latest 2.11.5 and bump up the version to 2.11.6?
Webpack 3 works with 2.x.x, not 3.x.x.

**Comment by avocadee** [comment]
cherry-picked https://github.com/webpack/webpack-dev-server/pull/2316 for webpack-dev-server 2.x.x for webpack3 users using nodejs 10

**Pull request merged**
