### PR TITLE
use contentBase from webpack config - fixes #597

### LINKED ISSUE #597: contentBase in webpack.config is ignored
webpack: 2.x 
webpack-dev-server: 2.1.0-beta.3
OSX 10.x

**Current behavior:**

When specifying a contentBase in your webpack.config file (and running webpack-dev-server from the command line, without any arguments), it is ignored & overwritten with the current path

**Expected/desired behavior:**

contentBase from the config file should be used

This bug was introduced by commit be9efdaa2e4539cd90eab27494a965c500c03320

### PR DESCRIPTION
**Pull request by wouterverweirder**
Bugfix for issue #597

### CODE REVIEW

**Comment by MoOx** [comment]
This fix looks good to me!

**Comment by SpaceK33z** [comment]
Thanks. This has the consequence though that `--content-base` is ignored if you set it in your webpack config. I think that's fine for now, just need to make sure it will be mentioned in the changelog.

**Comment by MoOx** [comment]
Maybe we could display a warning if a user specify both? Would help a lot :)

**Comment by SpaceK33z** [comment]
Yeah, that would be very nice. PR welcome. I'll work on it in after today if nobody sends a PR.

**Comment by MoOx** [comment]
The tricky part is that argv[content-base] is filled by default, so very tricky to catch when the user specify something from here...

**Comment by SpaceK33z** [comment]
You could check if `arg["content-base"]` is the same as `process.cwd()`... bit hacky though. It would mean that there is an edge-case, if you specify exactly your PWD then it doesn't work. But if there is no other way, that's better than nothing.

**Comment by MoOx** [comment]
> But if there is no other way, that's better than nothing.

Do not add default in yargs? (and define default later, like it was before)?

**Comment by SpaceK33z** [comment]
Yeah that also would be possible. Just need to make sure that it is still possible to explicitly disable contentBase (see #464).

**Comment by SpaceK33z** [comment]
@MoOx, are you planning to do a PR with this? Will wait with a new release if so.

**Comment by MoOx** [comment]
Don't have the time atm. Sorry :)

**Pull request merged**
