### PR TITLE
fix(server): fix setupExitSignals usage

### PR DESCRIPTION
**Pull request by Loonride**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No, should I add tests for `setupExitSignals`?

### Motivation / Use-Case

Fixes problem with `setupExitSignals` mentioned in: https://github.com/webpack/webpack-dev-server/issues/1479

An alternative to this approach is simply to get rid of `setupExitSignals`, but I think it's better to keep the helper and just change the function a bit.

### Breaking Changes

Altered `setupExitSignals` function API.

### CODE REVIEW

**Comment by Loonride** [comment]
> Not sure, how it is solve problem

Before, we were just passing undefined into the function. The function could not see when the variable was set to something else outside of the function.

Here, I am passing an object into the function. The `setupExitSignals` helper will be able to see when the properties of this object are updated from outside of the function.

**Comment by evilebottnawi** [comment]
@Loonride can we add tests fir this case?

**Comment by Loonride** [comment]
> @Loonride can we add tests fir this case?

Yes I will do that soon.

**Comment by Loonride** [comment]
@evilebottnawi It looks like husky is not working for me. Usually works for me on Windows 7, but I'm on Ubuntu 16.04 right now. Possibly just a bad `npm install` or something. Anyway, that means `commitlint` was not run here. Could this cause a problem with the commit messages?

**Comment by evilebottnawi** [comment]
@Loonride 
> Could this cause a problem with the commit messages?

don't worry, i will fix commit message before merge (I often correct them for a better changelog), anyway using good commit message help me to do it :smile:

**Comment by hiroppy** [comment]
Thanks

**Pull request merged**
