### PR TITLE
fix grammar error in status.js

### PR DESCRIPTION
**Pull request by ericestes**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [X ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

Fixes a grammar error in a console log.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
It is not grammatical error https://en.wikipedia.org/wiki/Fallback

**Comment by ericestes** [comment]
It is. When used as a verb it’s two words: https://en.m.wiktionary.org/wiki/fall_back#English

**Review by alexander-akait — COMMENTED** [review]
Thanks for the PR, but `fallback` is valid word in programming world

**Comment by ericestes** [comment]
@alexander-akait it is not a valid verb in any world. Do you consider "fallbacked" to be valid?

**Pull request closed without merging**
