### PR TITLE
fix: allow to open browser with --open-page

### PR DESCRIPTION
**Pull request by snitin315**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Yes.

### Motivation / Use-Case

Fixes https://github.com/webpack/webpack-dev-server/issues/2993

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Can we add tests?

**Comment by snitin315** [comment]
Investigating how to add one for this.

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
