### PR TITLE
feat: overlay displays unhandled promise rejection

### PR DESCRIPTION
**Pull request by malcolm-kee**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes

### Motivation / Use-Case

`overlay.runtimeErrors` should capture unhandled Promise rejection, as it's still runtime error, just async in nature.

### Breaking Changes

Not breaking change.

### Additional Info

Part of #3689

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by yoyo837** [comment]
How do I make unhandled promise rejection not overlay displays, so that it behaves the same as before.

**Comment by yoyo837** [comment]
> How do I make unhandled promise rejection not overlay displays, so that it behaves the same as before.

```diff
overlay: {
++runtimeErrors: false,
  errors: true,
  warnings: false,
},
```

This is the same behavior as before.

**Comment by keremcanb** [comment]
This feature gave us so much headache that we had to downgrade to the previous version.

**Comment by alexander-akait** [comment]
@keremcanb just disable it using options

**Comment by keremcanb** [comment]
We are running on CRA, which is not ejected. Also we don't want to disable
all runtime error messages.

**Comment by alexander-akait** [comment]
You can filter them, sorry we will not remove this feature

**Comment by tomasztomys** [comment]
It should be break change!

**Pull request merged**
