### PR TITLE
fix for #625 broken historyApiFallback

### PR DESCRIPTION
**Pull request by mac2000**
fixing broken historyApiFallback, with this one - tests are passed and we can use custom index or rewrites property of historyApiFallback

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Thanks!

**Comment by aves84** [comment]
@SpaceK33z And serving the files without extensions or with `disableDotRule` is broken again. Great job :/

**Comment by SpaceK33z** [comment]
@aves84, this solution doesn't break previous behavior. If you find a solution that doesn't break the old behavior (that is, showing the directory index instead of the page set with historyApiFallback), I'll happily merge a PR.

**Comment by aves84** [comment]
@SpaceK33z in #625 I already wrote this solution - you need to extract `serveIndex` from `contentBase` to independent meddleware.

I don't interested anymore making PR, everyone of which are reverted :/

I will prefer just to switch back to browserSync with normal behaviour.

**Comment by SpaceK33z** [comment]
@aves84, I can understand your frustration. I didn't understand your solution in #625, but now I get it.

The commit cb1b32fa6c57ec3ae9d16be129279df9448cb29f should fix the behavior for both of you. @aves84 and @mac2000, could you verify this? Sorry for the inconvenience.

**Comment by aves84** [comment]
@SpaceK33z, for me it works fine, thank you.

**Comment by mac2000** [comment]
@SpaceK33z @aves84 confirming things are working with this commit, glad that everyone will be happy again!

**Comment by SpaceK33z** [comment]
Great. Thanks for your help!

**Comment by SpaceK33z** [comment]
Fix is released in `2.1.0-beta.8`.

**Pull request merged**
