### PR TITLE
iOS Safari 10 bug where SockJS couldn't be found

### PR DESCRIPTION
**Pull request by abcd-ca**
**What kind of change does this PR introduce?**
bug fix on iOS Safari 10 (iOS 10)

**Did you add or update the `examples/`?**
No, not applicable, no API changes

**Summary**

Fixes iOS Safari 10 bug. At the root, this works around a bug where Safari's eval's scope was getting confused.  Something to do with [this issue](https://stackoverflow.com/questions/46036960/evaluated-expression-const-variable-scope-in-safari)

[bug reference](https://github.com/webpack/webpack-dev-server/issues/1090#issuecomment-352537184)

**Does this PR introduce a breaking change?**

No

**Other information**

No

### CODE REVIEW

**Comment by shellscape** [comment]
@abcd-ca please fill out the pull request template, those aren't optional. we ask that of everyone.

**Comment by abcd-ca** [comment]
@shellscape how's that?

**Comment by abcd-ca** [comment]
not clear why Travis CI is failing

**Comment by shellscape** [comment]
Better, but as a practice you shouldn't remove portions of a template. Looks like you clipped 

> Did you add or update the examples/?

Templates (issues and pull requests) are usually there to help everyone interacting with you out :)

Looks like there are some failures in CI that need to be addressed.

**Comment by shellscape** [comment]
Clicking on the [Details](https://travis-ci.org/webpack/webpack-dev-server/builds/318263257?utm_source=github_status&utm_medium=notification) link for Travis will show you the builds that failed. Looks like you didn't link before pushing :)

**Comment by abcd-ca** [comment]
@shellscape I added that missing part of the template. Next time I'll leave the template there and modify

**Comment by abcd-ca** [comment]
@shellscape I can't see what it is that needs fixing exactly. I don't see anything I can click on to give me an explanation in the Travis CI error view

**Comment by abcd-ca** [comment]
will re-issue pr to fix travis issue

**Comment by shellscape** [comment]
@abcd-ca you don't have to reissue anything. you just need to run `npm run test` locally and push a fix to the same branch

Here's the sequence in which you should click on Travis links
Imgur
Imgur

And here's the log in Travis that shows the error
Imgur

Always run `npm run test` before creating a PR for the project :)

**Comment by abcd-ca** [comment]
@shellscape thanks for reminding me to pull the repo and run tests before issuing PR. Pushed a fix. Once PR is merged, do you know how I update my project to get the fix? Never been clear on that as it seems you would maybe have to issue a new release and somehow master may not be current with npm but I'm not too sure how that all works.

**Comment by shellscape** [comment]
@abcd-ca thanks for your patience on this one. we've merged it.

**Pull request merged**
