### PR TITLE
feat: add `magicHtml` option

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [x] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Yes

### Motivation / Use-Case

add `magicHtml` option.

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by 0rvar** [comment]
So, what does this `magicHtml` option do?

**Comment by NicolasBonduel** [comment]
@0rvar [The doc](https://webpack.js.org/configuration/dev-server/#devservermagichtml) is not very clear.
I believe is allows you to access some files without using their extension in the browser.

This image is from [this stackoverflow from over 5 years ago](https://stackoverflow.com/questions/37027400/webpack-dev-server-displays-listing-of-magic-html), but I think it best describes what the magicHtml option does.


Also, it seems to corroborate what I see in the [unit tests of this PR](https://github.com/webpack/webpack-dev-server/pull/3717/files#diff-d9d8306aad440357cef0f5d05770d0f5ee9c8dc7ca570b9189cc2b2aa58903deR35).

**Comment by snitin315** [comment]
@0rvar @NicolasBonduel we also have an example https://github.com/webpack/webpack-dev-server/tree/master/examples/magic-html

**Comment by ylemkimon** [comment]
@0rvar It automatically generates HTML, which includes the specified JS file, via the path without `.js` extension.

**Pull request merged**
