### PR TITLE
set default mode to development

### PR DESCRIPTION
**Pull request by NaNdreas**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
If this needs any tests I would appreciate some help what type of test, and where to add it

### Motivation / Use-Case
Set default `mode` to `development`. webpack config and CLI option will override the default if provided. 
See #1560 and #1327 

### Additional Info
As far as I could tell the devServer options (just below the line changed in this PR) are only picked up from the first array item if the webpack config is an array(?). So I used the same principle for detecting `mode` in the config.

### CODE REVIEW

**Comment by NaNdreas** [comment]
Hi @ooflorent 

Personally I think what Webpack's warning is really saying (the reason behind it) is "_Hey, I don't know if you want production or development, please specify or the result may be really wrong_". That makes sense in Webpack's case, because from running `webpack` there's no way to tell if the user wants production or development. 

But in this case, from `webpack-dev-server`, we do know that the user wants (or should have) development, so I don't see the reason to ask for it. 

Webpack will still warn when the user wants to build a production build with the `webpack` command

I could definitely be missing something though, maybe you're thinking of a specific scenario?

**Comment by evilebottnawi** [comment]
@NaNdreas 
> EDIT: to be clear it's not my decision in the end, I have no power here hehe, I just added my view on it.
I will look at tests meanwhile

We need feedback from other developers

**Comment by MatTheCat** [comment]
For now there are 78 :+1: on https://github.com/webpack/webpack-dev-server/issues/1327

> With this change, the warning vanishes which is not correct in my opinion.

The warning will appear when `webpack` is used.

I heard a lot about “zero configuration” and “sensible defaults”. Is it not sensible for webpack-**dev**-server to imply a **dev** enviroment?

**Comment by odinho** [comment]
IMHO this sounds like a sane default (so one extra random developer there).

@NaNdreas: If you rebase, Travis should re-run and hopefully not fail.

**Comment by evilebottnawi** [comment]
@NaNdreas we need add tests and we can merge this

**Comment by NaNdreas** [comment]
Hi, 
I will not have access to a laptop in december, if anyone else feel like taking over this PR, feel free. If nobody worked on it when I am back around new years, I can look at it.
Thanks

**Comment by NaNdreas** [comment]
Hi,
I've started looking at the tests and how to effectively test this change, but I'm lost when looking at other tests and don't have the time to deep dive into it. I will have to leave this one as it is now sorry. 

Feel free to take this PR anyone who wants to write the tests. 

Thanks

**Comment by evilebottnawi** [comment]
Done in master

**Pull request closed without merging**
