### PR TITLE
fix: respect `NODE_PATH` env variable

### PR DESCRIPTION
**Pull request by snitin315**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
No.

### Motivation / Use-Case

Porting changes from https://github.com/webpack/webpack-cli/pull/3411

Reference https://github.com/webpack/webpack-cli/issues/3355

### Breaking Changes
No.

### Additional Info
No.

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Le't simprove this using:
```js
if (typeof process.env.NODE_PATH !== undefined) {
 // Logic
}
```

I think we need the same change in `webpack-cli` and `webpack` itself, can you fix it? thank you

**Comment by alexander-akait** [comment]
hm, from docs:

> NODE_PATH is still supported, but is less necessary now that the Node.js ecosystem has settled on a convention for locating dependent modules. Sometimes deployments that rely on NODE_PATH show surprising behavior when people are unaware that NODE_PATH must be set. Sometimes a module's dependencies change, causing a different version (or even a different module) to be loaded as the NODE_PATH is searched.

And

> Additionally, Node.js will search in the following list of GLOBAL_FOLDERS:

> 1: $HOME/.node_modules
> 2: $HOME/.node_libraries
> 3: $PREFIX/lib/node

Also paths on windows and linux are platform specific (and windows can has multiple paths separated by `;`), so fix is not simple as I thought.

So I see two solutions here:
1. Don't support it, but it can be paintful for some developers
2. Fix our logic and handle all cases (not sure how we can handle `$HOME` and `$PREFIX`)

I am working on `2.`

**Comment by alexander-akait** [comment]
@snitin315 Found easy solution, we should use it in `webpack-cli`/`webpack`

**Comment by alexander-akait** [comment]
Also it should be after `node_modules` check

**Comment by snitin315** [comment]
Nice solution, I'll update in webpack/webpack-cli 👍🏻

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
