### PR TITLE
fix: show detailed error in overlay for webpack 5

### LINKED ISSUE #2786: Webpack 5 dev server doesn't show detail error in overlay
# Bug report

the dev server doesn't show detail error in overlay in webpack 5

**What is the current behavior?**

the overlay message doesn't show the compiler error, maybe the error scheme change in webpack 5?
 
image

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/cvgellhorn/webpack-boilerplate
vi webpack.dev.js # add overlay in devServer
npm run dev
```

**What is the expected behavior?**

show the detail error like webpack4

**Other relevant information:**
webpack version:  5.2.0
Node.js version:  14.8.0
Operating System:  mac os 10.14.6
Additional tools: npm v6

### PR DESCRIPTION
**Pull request by snitin315**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Not yet

### Motivation / Use-Case
Fixes #2786, fixes #2760

### Breaking Changes
No

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
Thanks, I will fix CI problem today/tomorrow and merge it

**Comment by evilebottnawi** [comment]
I think we need increase timeout in some tests

**Comment by evilebottnawi** [comment]
We need fix tests, please run it locally

**Comment by snitin315** [comment]
I see a different test is failing each time. I will check it locally.

**Comment by ylemkimon** [comment]
I can confirm all tests pass locally. I think we need a retry logic for flaky tests. Until then could you try closing and reopening the PR?

**Comment by evilebottnawi** [comment]
@ylemkimon we are try it many times, I think we need fix tests, because after this change the problem appears

**Pull request merged**
