### PR TITLE
support sslPaths option for custom certificates

### LINKED ISSUE #107: Add option for providing own SSL certificate
Right now it's hardcoded to use the self-signed one in the repo. Would be nice to easily swap that out.

### PR DESCRIPTION
**Pull request by pstoica**
Fixes #107

### CODE REVIEW

**Comment by sokra** [comment]
Instead of providing a path to key/cert/ca, add options to pass key/cert/ca buffer directly. No need for an additional indirection. Keep in mind you can write JS in webpack config file. You can fs.readFileSync there.

``` js
...
devServer: {
  key: fs.readFileSync(...),
  cert: fs.readFileSync(...),
  ca: fs.readFileSync(...)
}
```

**Comment by pstoica** [comment]
Gotcha, fixed unless you also needed Buffer/String typechecking.

**Comment by pstoica** [comment]
Would you be able to do a version bump to include this soon? I've been using a git repo/branch that has the prepublished files.

**Comment by ruudk** [comment]
I'd like a version bump too.. Really want to use this feature!

**Pull request merged**
