### PR TITLE
fix: options.overlay forget assign to options.clientOverlay

### PR DESCRIPTION
**Pull request by 869288142**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### Motivation / Use-Case

overlay option is not work on V4. I spent some time debugging and find the reason that overlay option is not assign clientOverlay

### Breaking Changes

no Breaking Changes

### CODE REVIEW

**Comment by alexander-akait** [comment]
Because overlay was removed in favor `client.overlay`, it was described in CHANGELOG

**Comment by 869288142** [comment]
> Because overlay was removed in favor `client.overlay`, it was described in CHANGELOG

Thanks you reply. I can not find it on master's changelog. when i push PR, I find the commit about it.  when i use 4.0.0-beta.0 version, i only pass options.overlay to webpack-dev-server.  i  can  use webpack alias to modiy the file now.   I look forward to solving this problem in the next version.

**Comment by alexander-akait** [comment]
How you run `webpack-dev-server`?

**Comment by 869288142** [comment]
> How you run `webpack-dev-server`?

I run `webpack-dev-server@4.0.0-beta.0` with webppack V5.

**This is my devServer Option**

``` js
    devServer: {
      static: {
        directory: './dist',
      },
      overlay: {
        warnings: true,
        errors: true
      }
    },
```
`package.json`

``` json
  "scripts": {
    "dev": "webpack serve --open --config=./webpack.dev.config.js",
  }, 
```

**when i use options.overlay, it not work**

``` js
    client: {
      overlay: {
        warnings: true,
        errors: true
      }
    }
```
**when i use `client.overlay`, it cause `configuration.client has an unknown property 'overlay'`**

the reduceRepo url is https://github.com/869288142/webpack4-best-pratice.git. 

**Follow these steps**

``` shell
git checkout webpack5
yarn 
yarn dev
```

**Comment by alexander-akait** [comment]
Very strange, I will look at this tomorrow, thanks for the PR

**Comment by schursin** [comment]
bump!

**Comment by alexander-akait** [comment]
Expected, `overlay` was moved to `client.overlay`, you need to use:
```js
{
  devServer: {
    client: { 
      overlay: true
    }
  }
}
```

**Pull request closed without merging**
