### PR TITLE
fix: add prefix for invalidate endpoint

### PR DESCRIPTION
**Pull request by EslamHiko**
- [x] This is a **bugfix**
- [x] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?
Yes

### Motivation / Use-Case
as @sokra suggested : https://github.com/webpack/webpack-dev-server/pull/2493#pullrequestreview-405542308

### Breaking Changes
a change in the endpoint from `/invalidate` to `/webpack-dev-server/invalidate`.

### CODE REVIEW

**Comment by hiroppy** [comment]
CI fails

**Comment by evilebottnawi** [comment]
@hiroppy I think it is due regression with output

**Comment by evilebottnawi** [comment]
@EslamHiko can you rebase?

**Comment by EslamHiko** [comment]
@evilebottnawi CI is green :smile:

**Pull request merged**
