### PR TITLE
feat: display documentation links on errors

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [X] This is a **code refactor**
- [X] This is a **test update**
- [ ] This is a **docs update**
- [X] This is a **metadata update**

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Maybe we should do it for all loaders and plugins and webpack itself too

**Review by alexander-akait — APPROVED** [review]

**Comment by snitin315** [comment]
> Maybe we should do it for all loaders and plugins and webpack itself too

Good idea, I will update and send PRs 👍🏻

**Comment by alexander-akait** [comment]
we need fix CI problems

**Comment by snitin315** [comment]
@alexander-akait fixed 👍🏻

**Comment by alexander-akait** [comment]
@snitin315 please rebase

**Comment by snitin315** [comment]
@alexander-akait done 👍🏻

**Comment by snitin315** [comment]
fixing conflicts.

**Review by rishabh3112 — APPROVED** [review]

**Review by anshumanv — APPROVED** [review]

**Review by alexander-akait — COMMENTED** [review]
We have small problems in schema-utils, I thinking fix it before merge it...

**Comment by snitin315** [comment]
> We have small problems in schema-utils, I thinking fix it before merge it...

Oh, what needs to be fixed in `schema-utils`?

**Comment by alexander-akait** [comment]
We don't add link for `anyOf`/etc, you can look at our snapshots

**Comment by snitin315** [comment]
> We don't add link for `anyOf`/etc, you can look at our snapshots

I will fix it 👍

**Pull request merged**
