### PR TITLE
fix(deps): Replace `rimraf` with `rm`, move `rimraf` to a dev dep

### PR DESCRIPTION
**Pull request by askoufis**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [x] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

No fixes or features

### Motivation / Use-Case

Now that this package's minimum supported node version is high enough, and given the relatively simple use case that `rimraf` is used for at runtime, IMO it's worth just using node's `rm` instead (via `graceful-fs`).

There is one more `rimraf` usage inside a test, but I figured that could stay. Happy to remove that too, though `rimraf` is still used as a CLI so it has to stay at least as a dev dep.

### Breaking Changes

None

### Additional Info

None

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Great job :+1:

**Comment by askoufis** [comment]
Should I rename the commit so commitlint will pass?

**Comment by alexander-akait** [comment]
Ignore it, I will rename when will merge

**Comment by alexander-akait** [comment]
Looks like github actions is down - https://www.githubstatus.com/, I will rerun it when it will work

**Pull request merged**
