### PR TITLE
Add "mimeTypes" option to schema

### PR DESCRIPTION
**Pull request by xiaoyann**
**What kind of change does this PR introduce?**

Bugfix

**Did you add or update the `examples/`?**
No need

**Summary**

mimeTypes is a valid option from webpack-dev-middleware, but it can't  pass validation

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by shellscape** [comment]
Please update the tests and CLI options as well.

**Comment by xiaoyann** [comment]
ok

**Comment by xiaoyann** [comment]
need not to update the CLI options

**Comment by shellscape** [comment]
@xiaoyann why don't you think we need to add this option to the CLI?

**Comment by xiaoyann** [comment]
@shellscape Because "mimeTypes" should be an object like "headers" option. So, you can't use by CLI. you should define it in "devServer".

**Comment by shellscape** [comment]
That's a rather subjective opinion. Thanks very much for taking the time to put together a PR for this, but we're going to pass on adding this feature at the moment. Instead, we'll be implementing a pass-through API option that will allow people to pass any options to sub-components that they'd like without having to modify the options schema.

**Comment by xiaoyann** [comment]
Thank you for your guidance and look forward to this feature.

**Comment by olsonpm** [comment]
@shellscape 

> Instead, we'll be implementing a pass-through API option that will allow people to pass any options to sub-components that they'd like without having to modify the options schema

Is this already being worked on?  I don't see relevant code in v3, another branch nor a PR.  I will start the work if nobody's started.  I got here due to needing access to the mimeTypes option.

**Pull request closed without merging**
