### PR TITLE
fix: clean 'close' event listeners on socket server after generating new proxy config.

### PR DESCRIPTION
**Pull request by cwj0417**
- [x] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

yes, test cases added.

### Motivation / Use-Case

when pass a function to proxy config. every time firing `handler` function, a new proxyServer were set, and events on old proxyServer has not been cleared.

### Breaking Changes

no

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
Thank you

**Comment by alexander-akait** [comment]
Ignore failed CI, we will fix it soon

**Comment by cwj0417** [comment]
I removed  optional chaining and nullish coalescing operator to make code compatible with lower node versions.
I'm sorry for not noticing before.

**Comment by alexander-akait** [comment]
@snitin315 I want to merge it (you can do it too), will be it hard to rebase the next?

**Comment by snitin315** [comment]
No rebase won't be hard. But we can directly merge it in the next branch too

**Pull request merged**
