### PR TITLE
test: enable --hot-only test case

### PR DESCRIPTION
**Pull request by snitin315**
- [ ] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [x] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Enabled test.
### Motivation / Use-Case

Enable test case for `--hot-only`

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Comment by snitin315** [comment]
I think we can support `webpack --hot=only` now and remove `--hot-only`

**Comment by alexander-akait** [comment]
Yes, we should fix it

**Comment by snitin315** [comment]
I will do it 👍🏻

**Pull request merged**
