### PR TITLE
webpack-dev-server v4 -window is not defined #2970

### PR DESCRIPTION
**Pull request by janlent1**
- [X] This is a **bugfix**
- [ ] This is a **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **docs update**
- [ ] This is a **metadata update**

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Oh, we just remove it in near future, it was workaround for beta

**Comment by janlent1** [comment]
@alexander-akait okay cool. Will it then work in the future as well?

**Comment by alexander-akait** [comment]
Yes, we jsut remove this lines, you can do it here

**Comment by janlent1** [comment]
@alexander-akait is this better? https://github.com/webpack/webpack-dev-server/pull/2971/commits/1b18f8ef065a8d7e97be0f77fe83527bc727587f

**Comment by alexander-akait** [comment]
Yep, thanks

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by janlent1** [comment]
@alexander-akait  CLA?

**Comment by janlent1** [comment]
@alexander-akait  Accepted!

**Comment by alexander-akait** [comment]
Can you use email used for CLA for commits, you cans see that they are white and not assign to user

**Comment by janlent1** [comment]
I updated my local git config email. How can i know verify it??

**Comment by janlent1** [comment]
so signed it.

**Comment by alexander-akait** [comment]
@janlent1 First commit doesn't have `email`, need rewrite

**Comment by janlent1** [comment]
@alexander-akait so now :) Thanks for the patience :)

**Comment by janlent1** [comment]
@alexander-akait is there anything missing still?

**Comment by janlent1** [comment]
@alexander-akait  this is also similar in here node_modules/webpack-dev-server/client/default/utils/reloadApp.js at rootwindow.location.reload()
the rootwindow is not defined in the webworker self object

**Comment by alexander-akait** [comment]
@janlent1 Let's fix it too

**Comment by janlent1** [comment]
@alexander-akait is there a message that can be sent to the mainthread that triggers the reload?

**Comment by alexander-akait** [comment]
Just close/open

**Comment by janlent1** [comment]
@alexander-akait what?

**Comment by alexander-akait** [comment]
If you need rerun CI, just close PR and open again, github rerun CI in this case

**Comment by janlent1** [comment]
> @alexander-akait is there a message that can be sent to the mainthread that triggers the reload?

@alexander-akait i meant for the webworker if it tries to trigger the reload ... isnt that possible inside e node_modules/webpack-dev-server/client/default/utils/reloadApp.js if you have a entry as a webworker and this code inside the entry?

**Comment by alexander-akait** [comment]
Sorry, I can't understand

**Comment by janlent1** [comment]
@alexander-akait hi is the lowered codecov going to be an issue? should i write some tests?
Thanks,
Jan

**Comment by alexander-akait** [comment]
> @alexander-akait hi is the lowered codecov going to be an issue? should i write some tests?

All fine

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
